### ISSUE TITLE
Rare startup crash with empty macros file 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1001]
https://pastebin.com/duXp8pZR

I've never been able to reproduce this for some reason. 

It looks like sometimes, people will get a crash on a launch after their first one, because filewriter created a completely blank file somehow, without writing the blank json array to it, so when it goes to load macros, it just crashes because there isn't a proper json array. 

This shouldn't happen, as shown in testing, if you create a blank file and then try to save the config, it will write a blank json array to it.

**Comment by dominikaaaa** [comment]
![Screenshot_20200702-171653](https://user-images.githubusercontent.com/17222512/86409960-ea8df480-bc87-11ea-97c8-7be4db8930b0.png)
example ^ literally empty

**Comment by dominikaaaa** [comment]
```
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:899)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at me.zeroeightsix.kami.util.Macro.readFileToMemory(Macro.kt:34)
```
since pastebin link died

**Comment by humboldt123** [comment]
Dont fix it

**Comment by dominikaaaa** [comment]
???? why not

**Comment by humboldt123** [comment]
so people set macros

**Comment by dominikaaaa** [comment]
pretty counter intuitive. I'd rather fix the crash, it's not up to me if people use features of the mod or not

**Comment by dominikaaaa** [comment]
This still happens to only windows users

**Comment by Xiaro** [comment]
This should now be closed since it is all in try catch
