### ISSUE TITLE
"RAM Used" displays as "free" in the Info box

### ISSUE THREAD

**Issue by Titaniumtown** [kami-blue/client#1002]
**Describe the bug**
click on the Info box displays used ram as free

**To Reproduce**
1. Go to Client, InfoOverlay
2. Click on RAM Used
4. Look at Info box, see that a new line "xxxmB free" appears

**Expected behavior**
the new line should say "xxxmB Used"

**Screenshots**
![Screenshot from 2020-07-01 14-57-12](https://user-images.githubusercontent.com/11786225/86281211-2dc66580-bbab-11ea-94e0-216de0d9804c.png)

**Comment by dominikaaaa** [comment]
No it shouldn't, it displays the free ram

**Comment by Titaniumtown** [comment]
well, it doesnt. Because i sure dont think minecraft is using 20gb of ram.

**Comment by dominikaaaa** [comment]
uhhhh it uses 2x whatever you set as the max java args. If you can find some way to confirm that the code is outputting the wrong number, I'd be happy to change it but the code it's using is supposed to give you the "free" ram, so ¯\\\_(ツ)_/¯

**Comment by cookiedragon234** [comment]
If you set the max to be 10, it will be 10, not 20 lmao

**Comment by dominikaaaa** [comment]
I've always had Java use twice the max that I give it. If that's just a me thing, I don't know
