### ISSUE TITLE
Traveling Speed Option In DiscordRPC Module

### ISSUE THREAD

**Issue by sourTaste000** [kami-blue/client#1008]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
Traveling speed in DiscordRPC, like ` 20HP | Travling at 254.02km/h `

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dominikaaaa** [comment]
![dominikaaaa org-2020-07-03-17-24-26](https://user-images.githubusercontent.com/17222512/86498032-0fe73500-bd52-11ea-9651-71a4c9c84665.png)

**Comment by sourTaste000** [comment]
life is good
do not consider death uwu
