### ISSUE TITLE
Elytraflight acceleration feature

### ISSUE THREAD

**Issue by silverxd** [kami-blue/client#1015]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm elytraflying on oldfag and due to my garbage internet I start lagging back when starting to fly fast. It would benefit people who like a bit more maneuverability when flying around, so the speed starts off slow and slowly rises higher. This would help you move around tight spaces while being able to go fast if you want to.
**Describe the solution you'd like**
I would like if there was an acceleration slider so the speed gradually rises to the set max. An example can be found in ~~WWE Client~~ ~~Sun Client~~ Inertia Utility Mod.

**Describe alternatives you've considered**
Alternatives are manually changing elytraflight speed or using macros to bind different speed to different keys, however that is a rather annoying way to approach this issue.

**Additional context**
![image](https://user-images.githubusercontent.com/57298235/86530055-1397ca80-bebe-11ea-9901-000d8f667098.png)

It could look something like this

**Comment by dominikaaaa** [comment]
> I start lagging back when starting to fly fast.

That's not because of your internet, it's because you hit the speed limit. Previously, on oldfag, you used to be able to use acceleration to go up to 1000km/h +, but now it's hard capped at 129km/h

**Comment by dominikaaaa** [comment]
Meaning, you should be using the default speed for oldfag

**Comment by silverxd** [comment]
I might've failed to express myself correctly. When I get lucky with my start, I can fly fine at my specified top speed. Only the start is glitchy. Speed 2.39 works completely fine for me on oldfag.

**Comment by dominikaaaa** [comment]
Uhhh I don't have that issue ngl. But yea, this could be possible.

**Comment by silverxd** [comment]
Yea for example on WWE my start was a lot more stable when I enabled acceleration

**Comment by dominikaaaa** [comment]
[Here](https://cdn.discordapp.com/attachments/573955213879410689/729813710310473848/1015-ElytraFlightAcceleration.patch) is this as a patch file. Another ElytraFlight update is currently pending so this won't be pushed until that's done

**Comment by dominikaaaa** [comment]
#1023
