### ISSUE TITLE
have a second chat box for whispers

### ISSUE THREAD

**Issue by eliasfakhiri** [kami-blue/client#1019]
**Is your feature request related to a problem? no 

**Describe the solution you'd like*
a way to change chat boxes like badlion client private chat and normal minecraft chat except for whispers and normal chat

**Describe alternatives you've considered**
/ignore everyone on 2b

**Comment by dominikaaaa** [comment]
I don't see how this would be useful, you can disable whispers entirely, and chat filter and antispam can get rid of 99% of spam in a few seconds of configuring.
