### ISSUE TITLE
module that doesn’t load chunks

### ISSUE THREAD

**Issue by eliasfakhiri** [kami-blue/client#1021]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
be able to fly around in un loaded chunks so you can find loaded chunks easier so it’s easier to find bases
**Describe alternatives you've considered**
newchunks but that’s for noobs
**Additional context**
no

**Comment by dominikaaaa** [comment]
You can't just pick and choose which chunks to load client side. You can't know if it's new chunks or not until it was actually loaded
