### ISSUE TITLE
`;set <module> <setting> toggle` should work for enum (mode switching) settings as well

### ISSUE THREAD

**Issue by Xiaro** [kami-blue/client#1027]
**Is your feature request related to a problem? Please describe.**
I have to make separated macro for setting to different mode. Kinda annoying.

**Describe the solution you'd like**
Make it so it changes the setting in cycle

**Describe alternatives you've considered**
Or make macro runs different command each time pressed

**Additional context**

**Comment by l1ving** [comment]
Closed in 3a7868c
