### ISSUE TITLE
remove baritone

### ISSUE THREAD

**Issue by eliasfakhiri** [kami-blue/client#1030]
**Is your feature request related to a problem? Please describe.**
who tf uses that shit and it’s broken with other clients cuz rendering gray

**Describe the solution you'd like**
code.delete baritone kami blue

**Describe alternatives you've considered**
delete kami blue until baritone gone

**Additional context**
no delete

**Comment by StijnSimons** [comment]
🤡

**Comment by dominikaaaa** [comment]
No. Baritone integration is very useful to other people and there's already an issue which is opened to fix the leaking GL states. you can build it without baritone yourself if you want
