### ISSUE TITLE
Autocrystal add/fix

### ISSUE THREAD

**Issue by brightorangee** [kami-blue/client#1034]
If there is anyway possible to add salhacks 2.05 autocrystal ? Everything i love about the client just want to have one client for everything. I'm not sure on the troubles it would be to do that as i'm trying to learn java right now in a online class.

thank you :)

**Comment by dominikaaaa** [comment]
KAMI Blue writes original code, it doesn't paste already skidded code.

**Comment by dominikaaaa** [comment]
Also this is Salhack's CA 
![image](https://user-images.githubusercontent.com/17222512/87256045-aa83fa00-c45d-11ea-8ef0-13fdaf1d7e81.png)
and this is KAMI Blue's (written before Salhack)
![image](https://user-images.githubusercontent.com/17222512/87256050-af48ae00-c45d-11ea-96b8-1900aafb1f7b.png)

**Comment by dominikaaaa** [comment]
they couldn't even change the variable names or math, they just copied it over lmao
