### ISSUE TITLE
A Pearl Alert and also an armor alert, just like BreakWarning.

### ISSUE THREAD

**Issue by iSeros** [kami-blue/client#1035]
Alrighty so, time to explain.

**Pearl Alert**
This module, will draw a customizable ESP to the pearl and in chat, it will tell you something like this with the direction the pearl was thrown to:
"PLAYER234 has threw a pearl towards North!"

**Armor Alert**
Alrighty so, this module will have a option from 0-100 that will alert you. For example, the number that has been chosen in that option will be shown on screen.
When your armor hits the number chosen, it will draw text below your crosshair and say, the X is a placeholder:
"Your armor is below X%!"

**Comment by dominikaaaa** [comment]
First one: #256 

Also ArmorHUD already has an option for the other one
