### ISSUE TITLE
Bread on installer

### ISSUE THREAD

**Issue by humboldt123** [kami-blue/client#1043]
**Describe the bug**
Bread

**To Reproduce**
1. Double Click Jar
2. There will might be bread???

**Expected behavior**
There is not a bread normally

**Screenshots**
bread?
![Ec8Mp3SX0AABdXB](https://user-images.githubusercontent.com/38266782/87557450-eb5e5780-c685-11ea-8629-fd5b51bc4021.jpg)

**Additional context**
The bread called me a mean name >:(

**Comment by GPJmp** [comment]
Yes

**Comment by dominikaaaa** [comment]
It's a 1/50 chance smh

**Comment by zisis912** [comment]
LMAO

**Comment by zisis912** [comment]
I have experienced bread in the latest installer too, you must repoen the issue

**Comment by humboldt123** [comment]
It's an intended feature.
