### ISSUE TITLE
Installer doesn't support multimc

### ISSUE THREAD

**Issue by sourTaste000** [kami-blue/client#1047]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Make installer support multimc.

**Describe alternatives you've considered**
death?????

**Additional context**
N/A

**Comment by dominikaaaa** [comment]
Imo it you know what multimc is then you don't need an installer.

**Comment by dominikaaaa** [comment]
Ehhh actually finding which instance and selecting it and stuff would be a pain in the ass because it's not a permanent path, meanwhile you can just drag the jar into the instance icon in Multimc

**Comment by sourTaste000** [comment]
lol just put it on low priority

**Comment by sourTaste000** [comment]
mfw
