### ISSUE TITLE
Display all types of processes in Baritone GUI

### ISSUE THREAD

**Issue by mankool0** [kami-blue/client#1048]
**Is your feature request related to a problem? Please describe.**
Currently the Baritone GUI that displays the current process only works if the process is a "CustomGoalProcess", and if Baritone is doing something else then nothing is displayed.

**Describe the solution you'd like**
In this snippet
https://github.com/kami-blue/client/blob/264a51edb7436490002743d6933971dd677efe8d/src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java#L304-L309

instead of using `BaritoneAPI.getProvider().getPrimaryBaritone().getCustomGoalProcess().getGoal()` you can use `BaritoneAPI.getProvider().getPrimaryBaritone().getPathingControlManager().mostRecentInControl().get()`

Here's an example of what it might look like:
```
if (!frameFinal.isMinimized() && BaritoneAPI.getProvider().getPrimaryBaritone().getPathingControlManager().mostRecentInControl().isPresent()) {
    if (MODULE_MANAGER.isModuleEnabled(AutoWalk.class) && MODULE_MANAGER.getModuleT(AutoWalk.class).mode.getValue().equals(AutoWalk.AutoWalkMode.BARITONE)) {
        processes.addLine("Current Process: AutoWalk (" + AutoWalk.direction + ")");
    } else {
        processes.addLine("Current Process: " + BaritoneAPI.getProvider().getPrimaryBaritone().getPathingControlManager().mostRecentInControl().get().displayName());
    }
}
```
An in-game screenshot of what it looks like:
![image](https://user-images.githubusercontent.com/8884398/87700823-d0561b00-c74b-11ea-8ea7-d9d6a1ca313e.png)
![image](https://user-images.githubusercontent.com/8884398/87701174-5ffbc980-c74c-11ea-909c-ae60ce0a8696.png)

**Comment by dominikaaaa** [comment]
I was wondering how to fix that, thank you!

Honestly with all the effort you put into the formatting it would've been faster to make a pull, but I'll take anything I can get. Gimme a minute, this is an easy fix

**Comment by dominikaaaa** [comment]
Huh. 
![image](https://user-images.githubusercontent.com/17222512/87703904-867c2d80-c769-11ea-9e79-bd90a1f5b906.png)
![image](https://user-images.githubusercontent.com/17222512/87703952-9ac02a80-c769-11ea-9608-d320650a55f3.png)
```java
                if (MODULE_MANAGER.isModuleEnabled(AutoWalk.class) && MODULE_MANAGER.getModuleT(AutoWalk.class).mode.getValue().equals(AutoWalk.AutoWalkMode.BARITONE)) {
                    processes.addLine("Current Process: AutoWalk (" + AutoWalk.direction + ")");
                } else {
                    Optional<IBaritoneProcess> process = BaritoneAPI.getProvider().getPrimaryBaritone().getPathingControlManager().mostRecentInControl();

                    String processName = BaritoneAPI.getProvider().getPrimaryBaritone().getCustomGoalProcess().getGoal().toString();

                    if (process.isPresent()) {
                        processName = process.get().displayName();
                    }

                    processes.addLine("Current Process: " + processName);
                }
```
I added the if statement because it was crashing without it. Any idea why this doesn't work the same?

**Comment by dominikaaaa** [comment]
@mankool0 ^

**Comment by mankool0** [comment]
I tried your code and it crashes me on `String processName = BaritoneAPI.getProvider().getPrimaryBaritone().getCustomGoalProcess().getGoal().toString();` probably because the goal is null when the world is loading in. 
Also are you getting the goal to remove the "Custom Goal" in the status?
Because in that case this works for me:
```java
                if (MODULE_MANAGER.isModuleEnabled(AutoWalk.class) && MODULE_MANAGER.getModuleT(AutoWalk.class).mode.getValue().equals(AutoWalk.AutoWalkMode.BARITONE)) {
                    processes.addLine("Current Process: AutoWalk (" + AutoWalk.direction + ")");
                } else {
                    Optional<IBaritoneProcess> process = BaritoneAPI.getProvider().getPrimaryBaritone().getPathingControlManager().mostRecentInControl();

                    if (process.isPresent()) {
                        if (process.get() instanceof CustomGoalProcess) {
                            processes.addLine("Current Process: " + ((CustomGoalProcess) process.get()).getGoal().toString());
                        } else {
                            processes.addLine("Current Process: " + process.get().displayName());
                        }
                    }
                }
```
Giving me this:
![image](https://user-images.githubusercontent.com/8884398/87707720-7018a680-c756-11ea-922e-895d7380088b.png)
![image](https://user-images.githubusercontent.com/8884398/87707748-7d359580-c756-11ea-94a1-6d783315faea.png)
![image](https://user-images.githubusercontent.com/8884398/87707802-90486580-c756-11ea-80f5-03221288e0e6.png)

**Comment by dominikaaaa** [comment]
Same result with that code, `#farm` doesn't show anything
