### ISSUE TITLE
Add a MultiTask module.

### ISSUE THREAD

**Issue by luyten-h** [kami-blue/client#1049]
Alrighty, so this MultiTask module does a very simple thing.

When you have a Crystal in your  offhand, and any sort of item, both of the actions of those items can be made. For example:

Crystal in Offhand - Pickaxe in Mainhand - You mine enemies, and place crystals on the obsidian you're mining at the same time.

Crystal in Offhand - Gapple in Mainhand - You wanna faceplace someone, but dont have the right CrystalAura for it, well you can eat a gapple and crystal people manually at the same time! (Of course there would be a Explode-only crystalaura enabled, without place enabled)

**Comment by dominikaaaa** [comment]
I'm like 99% sure both Aura and CrystalAura support multitasking

**Comment by cookiedragon234** [comment]
https://github.com/cookiedragon234/Luchadora/blob/master/src/main/kotlin/cookiedragon/luchadora/module/player/MultiTaskModule.kt

**Comment by dominikaaaa** [comment]
ok cooker

**Comment by itsokk** [comment]
is this done or i can make a pr?

**Comment by dominikaaaa** [comment]
This issue is still open
