### ISSUE TITLE
Kami Blue Bedrock

### ISSUE THREAD

**Issue by DonJTru** [kami-blue/client#1051]
umm skrub said it but yeah
![Capture](https://user-images.githubusercontent.com/43910974/87740389-eccb7500-c796-11ea-9228-ad2ca9733473.PNG)

**Comment by dominikaaaa** [comment]
what the fuck is this issue for??

**Comment by humboldt123** [comment]
kami blue pocket edition obviously

**Comment by DonJTru** [comment]
Make sure it supports 1.16 MCPE (bedrock) Can you make it support Xbox 360, Xbox One, PS4, PS3, Nintendo Switch, Nintendo Switch lite, Nintendo WiiU, Nintendo 3DS, Nintendo *NEW* 3DS XL, Nintendo 2DS, Windows 10, Android, IOS, Amazon Kindle, MineChat (for android), MineChat (for IOS), Windows Phone, FireOS, Gear VR, Samsung Galaxy Store, AppleTV.
Please Allow for Relms Servers And LAN games.

**Comment by DonJTru** [comment]
You can allways just make another Kami Skid for this right? (or a horion skid: [Horion](https://github.com/horionclient))

**Comment by dominikaaaa** [comment]
no

**Comment by DonJTru** [comment]
please?

**Comment by DonJTru** [comment]
please?
like please?
