### ISSUE TITLE
Bedrock Support, (my old issue was closed so I thought I would reopen it, you must have closed it by mistake)

### ISSUE THREAD

**Issue by DonJTru** [kami-blue/client#1052]
Make sure it supports 1.16 MCPE (bedrock) Can you make it support Xbox 360, Xbox One, PS4, PS3, Nintendo Switch, Nintendo Switch lite, Nintendo WiiU, Nintendo 3DS, Nintendo *NEW* 3DS XL, Nintendo 2DS, Windows 10, Android, IOS, Amazon Kindle, MineChat (for android), MineChat (for IOS), Windows Phone, FireOS, Gear VR, Samsung Galaxy Store, AppleTV.
Please Allow for Realms, Servers, And LAN games.

_Originally posted by @DonJTru in https://github.com/kami-blue/client/issues/1051#issuecomment-659789295_

**Comment by DonJTru** [comment]
Like I want to 1v1 people on CrystalPVP but on bedrock because I dont have a pc, I only have a chromebook.

**Comment by dominikaaaa** [comment]
I said no
