### ISSUE TITLE
I think your Cat might have closed it, So I opened it again!

### ISSUE THREAD

**Issue by DonJTru** [kami-blue/client#1053]
Like I want to 1v1 people on CrystalPVP but on bedrock because I dont have a pc, I only have a chromebook.

_Originally posted by @DonJTru in https://github.com/kami-blue/client/issues/1052#issuecomment-659793040_

**Comment by DonJTru** [comment]
![Capture](https://user-images.githubusercontent.com/43910974/87741877-631da680-c79a-11ea-8387-7c007703f168.PNG)

**Comment by DonJTru** [comment]
People voted yes for it!

**Comment by humboldt123** [comment]
Why cant you rewrite it in C# smh

**Comment by dominikaaaa** [comment]
I said no.
