### ISSUE TITLE
ElytraFlight + InventoryMove gets you kicked on oldfig.

### ISSUE THREAD

**Issue by fw4hre0xxq** [kami-blue/client#1065]
When using ElytraFlight packet mode on oldfag with InventoryMove also enabled, you're likely to get kicked, especially when moving just after logging in or strafing. This doesn't seem to happen with autowalk. I'm using speed 2.39999999

**Comment by dominikaaaa** [comment]
InventoryMove just passes the keys back to the game, meaning oldfag has some sort of inventory opened check

**Comment by l1ving** [comment]
I can't reproduce this anymore. Please reopen if you can find a way to reproduce it, I'm not sure what I'm doing any different.
