### ISSUE TITLE
Periodically save settings 

### ISSUE THREAD

**Issue by Xiaro** [kami-blue/client#1069]
**Is your feature request related to a problem? Please describe.**
KAMI Blue only save the settings when exiting the game normally. So it won't save if the game crashed or terminated.

**Describe the solution you'd like**
Save the settings automatically every 1 min or longer (Can be configured by user)

**Describe alternatives you've considered**
Saving the settings when ever it gets changed

**Comment by dominikaaaa** [comment]
KAMI Blue does actually save the settings if it crashes, I tested it to be sure it worked. If another mod redirects the mixin it uses, it won't work for crashes
