### ISSUE TITLE
Saturation in Info tab.

### ISSUE THREAD

**Issue by dexterfoxy** [kami-blue/client#1070]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I want to add an option to show the saturation value in the info bar.

**Describe alternatives you've considered**
There are none in KAMI Blue.

**Additional context**
N/A

**Comment by dominikaaaa** [comment]
Why would you want it in info? HungerOverlay already shows it over the hunger bar
