### ISSUE TITLE
Obsidian miner for crystal pvp

### ISSUE THREAD

**Issue by HelpMopDog** [kami-blue/client#1072]
**Is your feature request related to a problem? Please describe.**
No promlem just idea
**Describe the solution you'd like**
I would like possibly just a built in feature to the auto cryztal mechanic in kami blue or a whole new feature as a whole i would like a feature that would mine out obsidian boxed around enemies who cryztal aura is  targetting
**Describe alternatives you've considered**
Possibly somthing that will mineout all types of blocks around people possibly when they are mining away amd using baritone to block up there path.
**Additional context**
Nope

**Comment by dominikaaaa** [comment]
Ehhh I'm closing this as won't fix because it's not that useful and it would be pretty unreliable

**Comment by Xiaro** [comment]
Ehh well I was planning to impl it as part of combat update lol

**Comment by dominikaaaa** [comment]
lmfao
