### ISSUE TITLE
Ingame account switcher

### ISSUE THREAD

**Issue by varrooonn** [kami-blue/client#1079]
**Is your feature request related to a problem? Please describe.**
A new feature request: an Ingame account switcher, where the minecraft account can be changed in-game rather than closing the game, signing into another account etc...

**Describe the solution you'd like**
A part where the minecraft account can be signed in immediately with selection of a button, where the passwords are securely stored and can be signed in very easily.

**Describe alternatives you've considered**
none 

**Additional context**
an already created mod: https://www.curseforge.com/minecraft/mc-mods/in-game-account-switcher/files

**Comment by dominikaaaa** [comment]
Already suggested, #12

**Comment by varrooonn** [comment]
okay
