### ISSUE TITLE
Autocomplete doesn't work for optional arguments

### ISSUE THREAD

**Issue by KMatias123** [kami-blue/client#1080]
Autocomplete doesn't work when a command has optional arguments.

1. Open chat.
2. Type a command that has over 2 arguments and the 2nd argument can be whatever.
3. Try to autocomplete.
4. The word does not autocomplete.

The module name in ;bind or ;renamemodule should autocomplete.

**Comment by dominikaaaa** [comment]
The autocomplete for `;toggle` works fine for me. It looks like this is specific to some commands

**Comment by KMatias123** [comment]
i think it breaks when it has 2 args and the other 1 is optional

**Comment by dominikaaaa** [comment]
Thanks, that's immensely helpful. I'll look into that

**Comment by dominikaaaa** [comment]
![Screenshot_20200731_194539](https://user-images.githubusercontent.com/17222512/89088472-7c138380-d366-11ea-8d67-82c6e560d97d.png)
Confirmed
