### ISSUE TITLE
falling glitch (2b2t)

### ISSUE THREAD

**Issue by techhotspot** [kami-blue/client#1088]
**Describe the bug**

**To Reproduce**
idk i just joined 2b2t and i started falling
**Expected behavior**
i fell past bedrock than my game frose
**Screenshots**
https://media.discordapp.net/attachments/738199919336226887/738548219960754266/unknown.png?width=1204&height=677
**Additional context**

**Comment by dominikaaaa** [comment]
Freecam and Elytraflight are incompatible. #530

This has also been reported in this discord a grand total of nine (9) times today

**Comment by techhotspot** [comment]
> Freecam and Elytraflight are incompatible. #530
> 
> This has also been reported in this discord a grand total of nine (9) times today

wow lol sorry
