### ISSUE TITLE
ViewModel / ItemModel

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1089]
I can't believe nobody has suggested this yet.

It lowers the item in your offhand. Maybe even an option for main hand

- [ ] option for item rotation
- [ ] option for item height

**Comment by Doogie13** [comment]
I know this is an old issue but could the module be able to toggle arm models and the ability to move viewmodels away from the player?  

Example: ![Screenshot_20201030-215411.png](https://user-images.githubusercontent.com/62295632/97760203-80cd0c80-1afa-11eb-8e1f-b64fb35f0a6e.png)

**Comment by l1ving** [comment]
That's what I meant by "option for item rotation / height", thanks for the image

**Comment by zisis912** [comment]
when are you planning to implement this

**Comment by l1ving** [comment]
Updated

**Comment by zisis912** [comment]
does anyone know of a forge mod that does this?

**Comment by l1ving** [comment]
No idea, but it shouldn't be too hard to implement.

**Comment by zisis912** [comment]
it shouldn't be too hard if you are a coder, but i can't make it
