### ISSUE TITLE
ElytraFlight crashes when enabling inside the void in some servers 

### ISSUE THREAD

**Issue by moom0o** [kami-blue/client#1090]
**Describe the bug**

When trying to open your elytra above the end void while elytraflight is enabled your game will freeze.
**To Reproduce**
1. Go to the end
2. Go to a side where you can jump into the void
3. Turn on elytra flight while straight above the void
4. The game will freeze

**Expected behavior**
Your elytra should open and you will be able to fly

**Screenshots**
https://streamable.com/a9rfpk (video)

**Additional context**

Still happens in latest version, didnt bother to report a bug before

**Comment by dominikaaaa** [comment]
Are you in singleplayer?

**Comment by moom0o** [comment]
no, it's a server

**Comment by dominikaaaa** [comment]
Which server?

**Comment by moom0o** [comment]
1b1t.tk

**Comment by Xiaro** [comment]
It was cause by the getGroundPosY function, the for loop will goes endless if there is no blocks below. I already fixed in the render updates branch
