### ISSUE TITLE
AntiFog breaks after a relog or dimension change 

### ISSUE THREAD

**Issue by dunix12345** [kami-blue/client#1092]
**Describe the bug**
when i use liquid vision on future with kami it dont work 

**To Reproduce**
1. Enable AntiFog
2. Relog
3. Look into lava

**Expected behavior**
you should be able to see inside lava without the fog

**Comment by dominikaaaa** [comment]
That's a bug with KAMI by itself, you need to toggle the module

**Comment by dominikaaaa** [comment]
Oh you're talking about future. God I'm tired. AntiFog does the same thing as LiquidVision, just don't use both
