### ISSUE TITLE
Switch capes and rpc to 1 file

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1102]
I'd rather have it all in 1 JSON for organizations sake. Also there's no reason for capes to be the full URL, just the 10 / 13 is enough.

Please do **not** work on this, I have to do it myself due to the spreadsheet I have to make, as the amount of capes / rpc users is inconsistent

**Comment by natan515** [comment]
What does good-first-issue mean?

**Comment by l1ving** [comment]
![image](https://user-images.githubusercontent.com/17222512/99157848-b21d0f00-269a-11eb-9bdc-503549cf3377.png)

**Comment by natan515** [comment]
U gave it to your self but nice.
