### ISSUE TITLE
AutoTool with Switch Back not working

### ISSUE THREAD

**Issue by jumboman32** [kami-blue/client#1105]
When using the "AutoTool" module with the "SwitchBack" setting enabled, it does not switch to the best tool.

1. Turn on AutoTool with SwitchBack enabled.
2. Attempt to mine a block/Attack an entity.

The module should automatically switch to the best tool to mine the block or attack the entity.

version: kamiblue-1.1.7-2c49753a-release

**Comment by dominikaaaa** [comment]
I need a video of this issue because it works fine for me

**Comment by jumboman32** [comment]
Started working.
