### ISSUE TITLE
Add an option to change fonts

### ISSUE THREAD

**Issue by zisis912** [kami-blue/client#1106]
Add an option to change fonts. There will be a search bar that will search all the fonts installed on your system, and you can pick whichever you want.

**Comment by iBuyMountainDew** [comment]
Not really necessary. The mod [SmoothFonts](https://www.curseforge.com/minecraft/mc-mods/smooth-font) already accomplishes this goal and it is widely used.

**Comment by dominikaaaa** [comment]
Duplicate of #790
