### ISSUE TITLE
GUI Scaling

### ISSUE THREAD

**Issue by ToasterBathMaster** [kami-blue/client#1107]
**Is your feature request related to a problem? Please describe.**
Yes. My issue with Kami would be the lack of GUI scaling. I play on a rather small screen, and when I open the ClickGUI for Kami, the modules take up too much room and overlap. This makes everything really messy and difficult to navigate. 

**Describe the solution you'd like**
Make a GUI scaler that is independent of the actual Minecraft GUI scale.

**Describe alternatives you've considered**
You could make the scale/slider in a GUI module in the ClickGUI.

**Additional context**
n/a

**Comment by dominikaaaa** [comment]
That's impossible due to how KAMI GUI was designed. See #68, #201 #116, #88 and most importantly, #790
