### ISSUE TITLE
PlayerModel bug

### ISSUE THREAD

**Issue by dunix12345** [kami-blue/client#1125]
**Describe the bug**
any player model is almost xray like and enchants are over the entire texture even air

**To Reproduce**
idk was there by default with new update

**Expected behavior**
the player model should look normal but it looks very odd

**Screenshots**
![2020-08-07_20 55 23](https://user-images.githubusercontent.com/58926771/89701931-92828780-d8f0-11ea-957d-a8801afadcd0.png)

**Additional context**
seemed to happen more in newest update and my mods folder is worldDL, kami, fullscreenwindowed, ingame account switcher minimap mod

**Comment by dominikaaaa** [comment]
Probably related to #995

**Comment by dominikaaaa** [comment]
Closed in favor of #769
