### ISSUE TITLE
AutoObsidian gets you stuck in GUi loop

### ISSUE THREAD

**Issue by karson-d** [kami-blue/client#1127]
**Describe the bug**
GUI loop, can't get out of enderchest gui at all

**To Reproduce**
1. Go to where autoObsidian is
2. turn it on
3. place enderchest

**Comment by dominikaaaa** [comment]
I need a video of this happening on the latest version.

**Comment by dominikaaaa** [comment]
Closed, inactivity. Reopen with requested information.
