### ISSUE TITLE
The ranged option (tracers) can't be disabled

### ISSUE THREAD

**Issue by iamral** [kami-blue/client#1130]
**Describe the bug**
It looks like the ranged option can't be disabled

**To Reproduce**
1)Turn on tracers
2)Try to disable ranged
3)Nothing happens

**Expected behavior**
I expected tracers to change their color, but it didn't happen

**Screenshots**
https://i.imgur.com/26CbIu5.png

**Comment by Xiaro** [comment]
This isn't a bug. Only the color for players is configurable. But I can add option to change color for other types of entity

**Comment by dominikaaaa** [comment]
Yes. I think it would make more sense to have a custom color option for all entities
