### ISSUE TITLE
Improved NameTags

### ISSUE THREAD

**Issue by luyten-h** [kami-blue/client#1132]
NameTags.

Like in Future, but with a outline and it has a option for instead of filling the screen with enchantments, it just shows "Max" if they're above (should never happen) or the same as the max enchantments. Let's you add ping, health, gamemode, etc.

**Comment by dominikaaaa** [comment]
If you feel that #673 isn't detailed enough then leave a comment there

**Comment by luyten-h** [comment]
What about the "Max" thing and outline?

**Comment by dominikaaaa** [comment]
> then leave a comment there

**Comment by FluorideHistorian** [comment]
🐒
