### ISSUE TITLE
Installer Should **not** have Stable option

### ISSUE THREAD

**Issue by humboldt123** [kami-blue/client#1133]
In an effort to I guess coerce KAMI Blue users into using the Nightly because it is both more stable and has more features, the installer should not have the stable option. Furthermore, there shouldn't be a "Stable" version as it is now, but rather the current "Nightly" would be the new "Stable" and users would have the option to download branches such as antiafk, holefiller, and avoid, as these would be the new "Betas", which I think is a much more self explanatory name than Nightly.

**Comment by dominikaaaa** [comment]
Uh yea no. My entire point of removing choice is because more buttons is too confusing for users 


Adding an easy way for users to download half finished versions which are hundreds of commits old is no bueno

I'd much rather replace stable button with a button that chooses a custom install path

**Comment by humboldt123** [comment]
> I'd much rather replace stable button with a button that chooses a custom install path

To this extent can we also add MultiMC support? The whole thing was "if you're smart enough to install MultiMC; you can manually install KAMI Blue" but alot of people asking for help saying the installer wasn't working for MultiMC on the help channels in the discord seem to prove this wrong.

For example a user should be able to select if they want to install the client to
a) the vanilla .minecraft folder
b) A multimc instance
c) their own path

**Comment by dominikaaaa** [comment]
.... just make the button open a folder path

**Comment by humboldt123** [comment]
Yes but for the sake of simplicity on the users end, do you think everyone will know what their MultiMC path is?

**Comment by dominikaaaa** [comment]
If you're using multimc you can figure it out

**Comment by humboldt123** [comment]
> If you're using multimc you can figure it out
There are some people who can't. Its not like everyone knows how to google search effectively.

**Comment by dominikaaaa** [comment]
Then they can drag and drop it into the mods tab in Multimc?? it's not that hard

**Comment by sourTaste000** [comment]
perfect grammar moments

**Comment by l1ving** [comment]
Don't fix, see #1376
