### ISSUE TITLE
Write Coords and blocks found with StashFinder to a file

### ISSUE THREAD

**Issue by drees5** [kami-blue/client#1141]
It would be helpful if StashFinder could write the coordinates and number of blocks at a coordinate to a file, this would improve StashFinder as you would be able to go AFK and return with the coordinates and size of any bases found.

When finding a point of interest, write the data to a file containing the coordinates of the blocks, and the number of blocks in the chunk. Also reading from the file and outputting to chat would be more convenient than having to check the file manually.

At the moment the only way to do this (that I know of) is to save all chat messages, and then search through later for occurrences of "stashfinder".

**Comment by drees5** [comment]
My bad I should have checked the current system in-game, I didn't realize that the waypoints contained the coordinates and number of blocks already.

**Comment by dominikaaaa** [comment]
Yea lol. You can do `;wp stashes` to list only stashes as well
