### ISSUE TITLE
SelectionHighlight and Freecam Issue

### ISSUE THREAD

**Issue by jumboman32** [kami-blue/client#1149]
With SelectionHighlight and Freecam enabled, if you Freecam underground through blocks the blocks are still highlighted and it can be hard to see.

A good solution would be to disable SelectionHighlight when Freecam is active or two disable this feature while you are inside of blocks.
![2020-08-09_21 28 45](https://user-images.githubusercontent.com/68603817/89746407-79f8a580-da87-11ea-9bbe-a6580cf79053.png)

**Comment by dominikaaaa** [comment]
Done
