### ISSUE TITLE
InventoryViewer without PlayerModel enabled turns everything gray

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#1152]
![](https://cdn.discordapp.com/attachments/679996949335900190/742204517163991090/unknown.png)

**Comment by dominikaaaa** [comment]
The user that reported this issue cannot reproduce it after restarting Minecraft.

**Comment by dominikaaaa** [comment]
NVM. will test tomorrow

**Comment by itsokk** [comment]
same issue happened when in spectator mode, maybe its schematicas fault? (i had salhack and kblue installed and its bundled with schematica)

**Comment by dominikaaaa** [comment]
I have no idea what is at fault. I'll test tomorrow morning

**Comment by dominikaaaa** [comment]
I've confirmed this bug. Enabling InventoryViewer by itself causes chat and everything to turn gray. Enabling PlayerModel at the same time fixes it. 

This is caused by the last change removing preItemRender() and postItemRender(), as in the old version, enabling both PlayerModel and InventoryViewer breaks PlayerModel
