### ISSUE TITLE
AutoLog when player enters render distance 

### ISSUE THREAD

**Issue by fw4hre0xxq** [kami-blue/client#1155]
**Is your feature request related to a problem? Please describe.**
The AutoLog in future has an option to automatically log out regardless of health when a player who isn't on your friends list enters render distance. I'd like something similar in Blue.

**Describe the solution you'd like**
Seems like adding an option to autolog on render to autolog, and another option to autolog even if it's a friend, for maximum configurability.

**Describe alternatives you've considered**
Adding the feature to the VisualRange module.

**Additional context**

**Comment by dominikaaaa** [comment]
Ngl autolog as a whole needs to be rewritten, the original code is pretty eh and doesn't even disconnect you properly

**Comment by fw4hre0xxq** [comment]
yeah, it would also be nice if autolog did what other clients do and put "disconnected because player foo entered render distance" or "disconnected because 18 health"

**Comment by dominikaaaa** [comment]
I have no idea how that works. Maybe it's a custom GUI? Either way we need a better solution

**Comment by Xiaro** [comment]
Mixin into disconnect gui and modify the text

**Comment by Xiaro** [comment]
Oh, actually you can just add a listener for GuiScreenEvent, replace the event screen with a modified one.
