### ISSUE TITLE
GUI Suggestion

### ISSUE THREAD

**Issue by ezBot03** [kami-blue/client#1156]
Is your feature request related to a problem?
Answer: No.

Describe the solution you'd like
Add an option in the GUI to have curved edges to make it better for some ppl with OCD (like me)

**Describe alternatives you've considered**
There are other clients, but they have less modules. 

**Additional context**
No screenshots tbh, self-explanatory, the sharp edges on the module pages in the clickGUI should have an option to be made curved.

**Comment by dominikaaaa** [comment]
Leave a comment on #790 please, that's the master list for all GUI suggestions.

**Comment by dominikaaaa** [comment]
actually I did it myself already
