### ISSUE TITLE
Kill Aura Bug.

### ISSUE THREAD

**Issue by TopHatMedic** [kami-blue/client#1158]
**Describe the bug**
Idk how it happened, got killed by an enderman while using aura, go to get my gear, kill another enderman. Turn off aura. I go to a base mate aura punches him. I restarted and checked my other clients. Nothing. I have to switch clients befcause of this :(

**To Reproduce**
I have no clue how to.

**Expected behavior**
Once I turned off aura it shouldn't hit my basemate.

**Screenshots**

**Additional context**

**Comment by FluorideHistorian** [comment]
its literally impossible for aura to hit someone without it being on

**Comment by dominikaaaa** [comment]
That's not possible, you have aura enabled. Add them as a friend if you don't want aura to hit them.

**Comment by Xiaro** [comment]
♿

**Comment by itsokk** [comment]
rofl
