### ISSUE TITLE
More functionality in Freecam

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1160]
**Describe the bug**
Similar to  #1149 Trajectories doesn't disable on freecam, and keeps highlighting, even undergrownd (see screenshots).

**To Reproduce**
1. Turn on Freecam and Trajectories
2. See "error"

**Expected behavior**
Just like SelectionHighlight it should disable on Freecam.

**Screenshots**
![Screenshot_20200810_193958](https://user-images.githubusercontent.com/69328977/89838715-7fbfbb00-db5b-11ea-85e6-f5e1f1648586.png)
![Screenshot_20200810_195039](https://user-images.githubusercontent.com/69328977/89838992-31f78280-db5c-11ea-8de5-7d72f2f7ebad.png)

**Additional context**
None.

**Comment by dominikaaaa** [comment]
Actually SelectionHighlight doesn't disable in freecam, it disables when your head is in a block. Same solution tho

**Comment by dominikaaaa** [comment]
thanks for the bug report, it's an easy fix

**Comment by omninope** [comment]
Oh, my bad.
About the Trajectories: I think it should disable completly, because the projectile isn't going to land anywhere near the highlighted block (just an idea tho) and probably reenable once Freecam is disabled.

**Comment by dominikaaaa** [comment]
In ImpactDevelopment/ImpactIssues#912, this was suggested

> Some cool things that could be tacked on:
> - Right click a block while in freecam, your real player paths to it? Kind of like a RTS game
>   - If you have ender pearls, it could also throw an ender pearl to get there lol
> - Break or place blocks while in freecam, the real player realizes those changes using the structure builder or something. I guess it would be creative instead of spectator mode then? 
> - lol left click an entity while in freecam, it enables kill aura and starts following

maybe for now we can disable it if freecam is enabled, but in the future it would be cool to keep that in mind for #530

**Comment by l1ving** [comment]
Reopening this because the last comment wasn't fulfilled
