### ISSUE TITLE
SelectionHighlight doesn't know how to render entities such as Hypixel fireballs

### ISSUE THREAD

**Issue by asdfcube** [kami-blue/client#1168]
**Describe the bug**
When a ghast fireball hits me the game crashes

**To Reproduce**
1. Go to hypixel
2. Join a bedwars game
3. Have an alex or steve shot a fireball at u
4. Game crashes

Crash reports:
[crash-2020-08-11_20.55.23-client.txt](https://github.com/kami-blue/client/files/5060581/crash-2020-08-11_20.55.23-client.txt)
[crash-2020-08-11_20.59.08-client.txt](https://github.com/kami-blue/client/files/5060582/crash-2020-08-11_20.59.08-client.txt)
[crash-2020-08-11_21.47.21-client.txt](https://github.com/kami-blue/client/files/5060583/crash-2020-08-11_21.47.21-client.txt)
[crash-2020-08-11_21.54.39-client.txt](https://github.com/kami-blue/client/files/5060585/crash-2020-08-11_21.54.39-client.txt)
[crash-2020-08-11_22.42.59-client.txt](https://github.com/kami-blue/client/files/5060586/crash-2020-08-11_22.42.59-client.txt)
[crash-2020-08-12_11.18.19-client.txt](https://github.com/kami-blue/client/files/5060587/crash-2020-08-12_11.18.19-client.txt)
[crash-2020-08-12_12.03.54-client.txt](https://github.com/kami-blue/client/files/5060588/crash-2020-08-12_12.03.54-client.txt)
[crash-2020-08-12_12.05.31-client.txt](https://github.com/kami-blue/client/files/5060589/crash-2020-08-12_12.05.31-client.txt)

**Comment by FluorideHistorian** [comment]
👀

**Comment by dominikaaaa** [comment]
It looks like selection highlight can't figure out how to render fireballs??

**Comment by asdfcube** [comment]
> It looks like selection highlight can't figure out how to render fireballs??

ooooooooooooooo i try disabling it

**Comment by asdfcube** [comment]
> It looks like selection highlight can't figure out how to render fireballs??

ty it works
