### ISSUE TITLE
CrystalAura + Freecam = oops

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1174]
**Describe the bug**
Related to #1040, activating Freecam with CrystalAura enabled places crystals on myself.

**To Reproduce**
1. Turn on CrystalAura with "Place" on
2. Turn on Freecam
3. Have a heart attack?

**Expected behavior**
Crystals should not be placed on the freecaming player.

**Screenshots**
Don't think it's necessary.

**Additional context**

**Comment by dominikaaaa** [comment]
Closed the other one as this has more info

**Comment by omninope** [comment]
I noticed someting else: While on Freecam testing this behavior, with CrystalAura enabled, after moving close to the player 3 or 4 times the Freecam movement becomes extremely weird, stopping, slowing down and speeding up again.
