### ISSUE TITLE
SelectionHighlight HitSideOnly doesn't work properly on tall grass and dead bush

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#1186]
![image](https://user-images.githubusercontent.com/17222512/90290834-97918a80-de4c-11ea-8bd2-52719c0ad103.png)
![image](https://user-images.githubusercontent.com/17222512/90290819-93656d00-de4c-11ea-9c0e-5c02addef2f3.png)

**Comment by Xiaro** [comment]
How

**Comment by dominikaaaa** [comment]
look at the pictures. I'm assuming it happens because minecraft always returns north for those models?????

**Comment by Xiaro** [comment]
Closed due to unable to reproduce the error
https://cdn.discordapp.com/attachments/672537344682754086/747311246612758559/2020-08-24_00-27-24.mp4
https://cdn.discordapp.com/attachments/672537344682754086/747311559260504134/2020-08-24_00-29-00.mp4
