### ISSUE TITLE
Rare crash with InventoryManager because it's too fast 

### ISSUE THREAD

**Issue by sourTaste000** [kami-blue/client#1188]
**Describe the bug**
Crashed when I have scaffold and InventoryManager on at the same time.

**To Reproduce**
1. Enable scaffold and InventoryManager.
2. Get yourself some blocks
3. Start scaffolding very fast
4. Should crash

**Expected behavior**
Shouldn't crash, and refill inventory as expected.

**Screenshots**
![-2020-08-14-16-58-52](https://user-images.githubusercontent.com/47074495/90300478-7f6f3a80-de4f-11ea-880a-f63e4dcb50a8.png)
![-2020-08-14-16-58-37](https://user-images.githubusercontent.com/47074495/90300479-80a06780-de4f-11ea-8263-ecc30fe5cb8b.png)

**Additional context**
https://paste.ee/p/HvD6n
https://paste.ee/p/wvvBG

**Comment by Xiaro** [comment]
`mc.displayGuiScreen()` is not thread safe, that might be the cause

**Comment by dominikaaaa** [comment]
That's probably it lmfao

**Comment by dominikaaaa** [comment]
I've seen this exact stacktrace happen with other clients as well

**Comment by sourTaste000** [comment]
The paste expired

**Comment by sourTaste000** [comment]
should i make another one lol

**Comment by dominikaaaa** [comment]
Yea, paste it into a comment I guess

**Comment by sourTaste000** [comment]
its fixed in the latest version :joy:

**Comment by dominikaaaa** [comment]
How?

**Comment by sourTaste000** [comment]
cannot reproduce

**Comment by Xiaro** [comment]
Not yet actually, it still runs `mc.displayGuiScreen()` on a different thread. I am working on a fix
