### ISSUE TITLE
Add a russian language to kami blur (i can help in translation)

### ISSUE THREAD

**Issue by phonkplugg** [kami-blue/client#1190]
Because of the kami blue being famous in russia, somebody cant translate modules because they dont know english language, so we can help them in doin a russian language into the kami blue. I can translate any module, and tip to the module, if u want to : )

**Comment by dominikaaaa** [comment]
I'm happy for people to help out and I'm glad people want to translate this, but I already suggested this in #797, and also a module to translate chat messages (#999). 

Currently it's not possible for users to translate the client, we will try to make it possible with the new GUI which we're currently working on.
