### ISSUE TITLE
;say command allows 0 arguments 

### ISSUE THREAD

**Issue by myrh-w** [kami-blue/client#1194]
im get kicked from the server when I write the ;say command without arguments

1. Join server
2. type in chat ";say "
3. See error

I expected the command not work or send an empty line.

![javaw_im2XZANUCj](https://user-images.githubusercontent.com/68443801/90313576-5bc2f780-df16-11ea-9b5f-241878e0f39e.png)

**Comment by dominikaaaa** [comment]
Enable nopacketkick

This isn't really a bug, you can't send an empty message. We can add some safety to prevent stupid users from trying to send an empty message
