### ISSUE TITLE
TemporaryPauseProcess sets eating to false if not safe to cancel and it makes disabling AutoEat impossible 

### ISSUE THREAD

**Issue by Fich420** [kami-blue/client#1195]
**Describe the bug**

-Autoeat stays toggled on. Not sure why this is happening, Happened with a clean install of forge 14.23.5.2854 on kami version kamiblue-1.1.7-0dc04225-release. 

**To Reproduce**
-Turn autoeat on

**Expected behavior**
-Autoeat stays toggled on no matter how many times its clicked, or even ;t autoeat.

**Screenshots**
-I am aware future is installed in the clip, the originated when future was not installed and installing future broke autoeat I think? So it was the only way to not have my mc player not spam right click while playing. 
-https://youtu.be/HnpfZwr_MJ4
   ^bug in action

**Additional context**
-Autoeat will stay toggled on and will RAPIDLY scroll through the hotbar while right click is being spammed. Havent found a way to stop this besides dropping food and not picking it back up.

**Comment by dominikaaaa** [comment]
The scrolling issue is in a seperate bug report. It happens when you have certain food in more then 1 slot in your hotbar

**Comment by dominikaaaa** [comment]
This specific issue is probably caused by TemporaryPauseProcess setting eating to false when it's not safe to cancel 

![Screenshot_20200815-112634.png](https://user-images.githubusercontent.com/17222512/90315532-5485f480-deea-11ea-9096-5ca140a827a0.png)

**Comment by dominikaaaa** [comment]
something to note is on disable() calls unpause

**Comment by Fich420** [comment]
> 
> 
> The scrolling issue is in a seperate bug report. It happens when you have certain food in more then 1 slot in your hotbar

Interesting because I /only/ had cooked fish in my inv

**Comment by dominikaaaa** [comment]
uwu :3

If you had more then 1 stack / the stack was split up that's why it would happen.

**Comment by Fich420** [comment]
> 
> 
> uwu :3
> 
> If you had more then 1 stack / the stack was split up that's why it would happen.

Just realized, only had one stack of cooked fish (37 to be exact) BUT I also had spider eyes in my inv and rotten flesh. Does autoeat read those as foodstuffs? If so, that might also be something worth looking into depending how much time you have / want to put into this

**Comment by dominikaaaa** [comment]
Hmmm autoeat is supposed to explicitly ignore slider eyes and rotten flesh. Super weird, I'll have to look into that
