### ISSUE TITLE
Lawn Mower

### ISSUE THREAD

**Issue by darkerinkk** [kami-blue/client#1199]
So I have a idea for a feature what it is, is were when you turn it on the the grass near you breaks it would be good for removing grass near your project or if you need seeds

**Comment by FluorideHistorian** [comment]
sounds like nuker locked into one thing which imo is pretty stupid just make a nuker that allows you to select what blocks to break

**Comment by dominikaaaa** [comment]
^ Yea. This would be better fitted as an option inside #763, and you can already accomplish this with `;b mine grass tallgrass`
