### ISSUE TITLE
Extremely low fps using freecam on 2b

### ISSUE THREAD

**Issue by usnet-000** [kami-blue/client#1204]
**Describe the bug**
I get extremely low fps (3-6) when i use Freecam un 2b2t

**To Reproduce**
1. Join 2b2t.org
2. Turn on Freecam
3. Voilà low fps

**Expected behavior**
Normal fps

**Comment by dominikaaaa** [comment]
#530

**Comment by usnet-000** [comment]
How's this a duplicate and when will the rewrite happen?

**Comment by dominikaaaa** [comment]
#530 would just move RenderEntity and fix this issue as a side effect. #530 is milestoned for v1.1.7
