### ISSUE TITLE
Baritone listening to commands without any prefix.

### ISSUE THREAD

**Issue by Nathan-Webb** [kami-blue/client#1210]
**Describe the bug**
Baritone will respond to commands despite not using `#` or `;b` to call it. 
**To Reproduce**
1. Go into a world.
2. Type a baritone command without a prefix
3. Baritone will respond.

**Expected behavior**
Baritone will ignore the command

**Screenshots**
Gif of the bug in action:
https://i.imgur.com/N3HD7RX.gif

**Additional context**
It didn't seem like this is a baritone issue, unless its something super recent, as I checked the repository and I couldn't find anything except https://github.com/cabaletta/baritone/issues/611 which seems to have been resolved as the code was refactored? Not entirely sure.

**Comment by dominikaaaa** [comment]
That's not a bug, that's a Baritone feature. Run `#prefixControl false` to disable this.
