### ISSUE TITLE
BedAura Request

### ISSUE THREAD

**Issue by Florinel787** [kami-blue/client#1218]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

It's not necessarily a problem since CrystalAura exists, but being limited to obsidian and bedrock and having to position yourself so you don't kill yourself or so you can do more damage to the enemy is a bit frustrating.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

I want BedAura to be similar to CrystalAura, since the principles are the same (place and go boom). If I were to describe the feature from 0 it would be: 
Check if player is in the Nether or the End; 
Check for enemies; 
Check for flat surfaces with a minimum length of 2 blocks; 
Pick bed from inventory/hotbar and place as close to the enemy as possible; 
Use bed; 
Repeat;
(Optional) Profit!

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

I haven't found any public alternatives for this feature, yet. That's why I'm trying my luck with you, guys.
The only alternative I could come up with would be adding beds to CrystalAura and the necessary checks. (is player in nether/end, does the player have beds, are there any 2+ block-long surfaces) 

**Additional context**
_Add any other context or screenshots about the feature request here._

I am not sure if I am allowed to send youtube links, since that's where I've first seen the feature, but I'm going to risk it: https://www.youtube.com/watch?v=x4tAdQ_OLWg
EDIT: Somehow they managed to make it place beds on single blocks, that would be nice to have here, too

**Comment by dominikaaaa** [comment]
#1212
