### ISSUE TITLE
Crash when using elytraflight

### ISSUE THREAD

**Issue by ilan1009** [kami-blue/client#1219]
**Describe the bug**
Client crashes when using elytra flight. Does not crash when using other clients elytraflight.

**To Reproduce**
1. Go on '1.12 (Happens to me on 0b0t.org)'
2. Turn on elytra flight
4. Travel for 3-10 minutes

**Expected behavior**
Not supposed to happen.

**Video attached, may be NSFW (Toxic chat)**
https://streamable.com/y3gorc
**Additional context**
On 0b0t when crash occurs, You get the fake message from leeunderscore (anticheat).

**Comment by dominikaaaa** [comment]
Is this supposed to be a troll or something?

You're using salhack and impact in that video, you didn't provide a crash log nor kami blue version and lee is known for crashing people who he doesn't like. This isn't a KI Blue issue

**Comment by ilan1009** [comment]
Version latest, Crash log https://pastebin.com/uCDQ1DfM. No crash error in there.

**Comment by dominikaaaa** [comment]
Yea, the server is causing a recursive loop. This isn't a KAMI Blue issue, this is your server owner being shitty and "patching" certain speeds by hanging your game.

**Comment by ilan1009** [comment]
But it doesn't crash with other clients...

**Comment by dominikaaaa** [comment]
Yea and it doesn't crash with other server owners. You're getting manually hanged by leee

**Comment by ilan1009** [comment]
he doesnt just stand there 24/7 and crash ppl lmao, its an anticheat.
I get your point tho, But this has never happened to anyone on the server before. May be a problem with my minecraft.
