### ISSUE TITLE
Baritone goes back and forth sometimes in AutoObsidian

### ISSUE THREAD

**Issue by jumboman32** [kami-blue/client#1221]
When AutoObsidian runs out of ender chests to mine (sometimes) it will not search a shulker to grab more and will move back and forth like it is picking up an item. This is a somewhat random bug, but may be related to InventoryManager's "AutoRefill" option.

If it happens to me again, I will link a recording of the bug happening to this issue.

**Comment by dominikaaaa** [comment]
The moving back and forth is a baritone issue.

Can you attach an issue and your settings?

**Comment by jumboman32** [comment]
assumeWalkOnLava true
traverseFlowingLiquids true
placeNetherrackOnLavaSources true
allowParkourAscend false
blocksToAvoid crafting_table,furnace,lit_furnace,chest,trapped_chest,standing_sign,wall_sign,obsidian,portal,ender_chest,standing_banner,wall_banner,bedrock
blocksToAvoidBreaking crafting_table,furnace,lit_furnace,chest,trapped_chest,standing_sign,wall_sign,obsidian,portal,ender_chest,standing_banner,wall_banner,bedrock
rightClickSpeed 1
failureTimeoutMS 2000
chatControl false
shortBaritonePrefix true
buildRepeat 0,0,1
builderTickScanRadius 3
https://gyazo.com/d521214e87f8d6d3615362376e00f29c

**Comment by dominikaaaa** [comment]
I meant autoobsidian settings

**Comment by jumboman32** [comment]
https://gyazo.com/76c06948a55ccb7e736116ffc2ac6dcf

**Comment by dominikaaaa** [comment]
ty

**Comment by dominikaaaa** [comment]
First video you sent is a baritone bug as far as I know

**Comment by jumboman32** [comment]
and to note: this bug was happening with the default settings without "search shulker"

**Comment by dominikaaaa** [comment]
I'll leave this open if someone knows how to fix it, but afaik you can only cancel baritone and try again

**Comment by l1ving** [comment]
This should theoretically be fixed
