### ISSUE TITLE
Auto strnth

### ISSUE THREAD

**Issue by HelpMopDog** [kami-blue/client#1224]
**Is your feature request related to a problem? Please describe.**
No problem and i dont see many clients with it or at all
**Describe the solution you'd like**
I would like some sort of feature that drinks stnth when in a whole with someone else along with that somthing that re drinks it everytime it runs out
**Describe alternatives you've considered**
Maybe somthing that would shoot you with a strth arrow also it could be with all types of potions and arrows when they run out of some sort of thing along those lines
**Additional context**
![image](https://user-images.githubusercontent.com/68680918/90584654-efe7c580-e187-11ea-979e-90d9a8ce0f61.png)

**Comment by HelpMopDog** [comment]
me dribnking strenth like

**Comment by dominikaaaa** [comment]
I don't see why this would be useful.
