### ISSUE TITLE
Option to pause Baritone InventoryManager

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#1225]
Due to 2b2t disabling moving items while walking / crouching / whatever, it's a must to pause Baritone in order to bypass this.

**Comment by Xiaro** [comment]
I think it does already?
https://github.com/kami-blue/client/blob/c28c9b720cdadea87726aca10f8ae5721a83c8aa/src/main/java/me/zeroeightsix/kami/module/modules/player/InventoryManager.kt#L133-L139
