### ISSUE TITLE
AutoObsidian - Modify auto-disable feature to support automatic reconnects

### ISSUE THREAD

**Issue by harritaco** [kami-blue/client#1228]
**Is your feature request related to a problem? Please describe.**
When I'm kicked, and reconnect to the queue server AutoObsidian automatically turns off because there is "No valid position for placing shulker box / ender chest nearby"

**Describe the solution you'd like**
Ideally the check won't run until you're in the overworld or nether dimension. This would allow for more automation as you could continue paving if you were kicked or the server was reset. 

**Describe alternatives you've considered**
For the moment I've just been toggling AutoObby when I get back in game. 

[Screenshot](https://media.discordapp.net/attachments/634010851128639508/745863947906711632/unknown.png)

**Comment by l1ving** [comment]
Fixed in https://github.com/kami-blue/client/commit/e83516bb7ddfb5b4cc15829fae69dc7a08de1b1c
