### ISSUE TITLE
Scaffold should spoof rotations and tower differently to work on stricter anticheats. 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1244]
tldr 2b2t patched scaffold yet again for no good reason

**Comment by dominikaaaa** [comment]
This should now be easier to do with the new packet manager

**Comment by omninope** [comment]
Some observations:
Tested on commit ca431ce71413dc70523ad2f9673fcdbd0e20b42e and Scaffold doesn't even work properly on anything other than a lag-free singleplayer world. Tested on oldfag.org, 8b8t.xyz and 9b9t.com on NORMAL and LEGIT modes with various tick delays, Tower enabled or not and it just rubberbands, places blocks weirdly and randomly. Also Scaffold have a surprisingly hard time switching to a slot with a block if the player is holding something like food or a tool.
KAMI Blue version 1.1.6 Scaffold works almost perfectly out of the box for some reason, and without switching slots if the player is holding something else.

Some suggestions:
- Option to sneak while placing so the player can use block entities with a GUI (for example: ender chest, furnace);
- Bring back the ability to scaffold while holding something else.

**Comment by l1ving** [comment]
That means that probably the new event system broke scaffold.
