### ISSUE TITLE
Remove hardcoded blacklist for Search

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#1245]
Since the performance update and adding max blocks to Search, it's no longer needed. Instead, move the blacklist to the warning list.

**Comment by Xiaro** [comment]
Actually, no. All the blocks found will be stored in the main list first. And then the blocks that are out of limit will be not be added to the render list.
The reason of having 2 list is all for the sake of map color. This is why I said removing it.

**Comment by dominikaaaa** [comment]
Oh I see. So you still need a blacklist so it's not calculating a million bedrock.

I don't see how map colors is related? I'm talking about the hardcoded blacklist when you add blocks to search

**Comment by Xiaro** [comment]
> Oh I see. So you still need a blacklist so it's not calculating a million bedrock.
> 
> I don't see how map colors is related? I'm talking about the hardcoded blacklist when you add blocks to search

Map color = 2 list = lag if tons of blocks

**Comment by dominikaaaa** [comment]
Oh I get it. I was more concerned about general performance, but true
