### ISSUE TITLE
LogoutLogger extremely rarely causes constant lag spikes for that session, on certain hardware 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1251]
Tested on AMD Ryzen with an NVIDIA GPU. 

Apparently it doesn't happen all the time, you have to relog until it happens, and then it consistently happens. No idea if related.

I believe this line is causing it:

https://github.com/kami-blue/client/blob/ef0bff9813c66c9397f48a2e1ae79dd8dfa4e760/src/main/java/me/zeroeightsix/kami/mixin/client/MixinGuiPlayerTabOverlay.java#L34

**Comment by Xiaro** [comment]
Isn't that ExtraTab?

**Comment by dominikaaaa** [comment]
LogoutLogger uses that apparently. I'm currently investigating this with indrit, don't worry about it for now

**Comment by l1ving** [comment]
that specific section of MixinGuiPlayerTabOverlay.java was rewritten, I'd be surprised if this still happens

**Comment by Xiaro** [comment]
That was just the smooth brain code in LogoutLogger.kt, It had nothing to do with the mixin 🗿

**Comment by l1ving** [comment]
It doesn't happen anymore anyways
