### ISSUE TITLE
Modified camera level from going down in Elytraflight is incompatible with all tracers

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1252]
**Describe the bug**
While using ElytraFlight with tracers enabled for StorageESP and Search, if the player goes down the tracers desync and render above the player.

**To Reproduce**
1. Download kamiblue-1.1.7-d2c4173d-release.jar;
2. Enable ElytraFlight and start flying, enable StorageESP and Seach with Tracers on;
3. Go down by pressing lshift;
4. The tracers desync from the players eye position.

**Expected behavior**
Tracers stay alighned with players eye.

**Screenshots**
No.

**Additional context**
Didn't test with other modules that also render a tracer on screen.

**Comment by dominikaaaa** [comment]
I need a video of this.

**Comment by omninope** [comment]
Ok, but that will take some time because I haven't recorded a video in over a decade.

**Comment by omninope** [comment]
Video done
[https://streamable.com/1n7fje](url)

**Comment by dominikaaaa** [comment]
Oh I know what this is. It's caused by the recent view level change to elytraflight
