### ISSUE TITLE
Potion Effects UI crashes the game upon entering a world if the player has any effects applyed

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1257]
**Describe the bug**
Entering a world with Potion Effects UI enabled (showing on screen), and with active potion effects, crashes the game. Tested on single and multiplayer, with a clean install and nothing else enabled.

**To Reproduce**
1. Download kamiblue-1.1.7-655d2be0-release.jar;
2. Load a world, enable Potion Effects UI, and get any potion effect (tested with gapples);
3. Close everyting;
4. Reopen the client;
5. Try entering a world;
6. Crash

**Expected behavior**
_Probably_ shouldn't crash, i think.

**Screenshots**
Not necessary.

**Additional context**
Crash report [https://pastebin.com/YfrfgADt](https://pastebin.com/YfrfgADt)

**Comment by dominikaaaa** [comment]
```
java.lang.ArithmeticException: / by zero
	at me.zeroeightsix.kami.util.PotionInfo.formattedTimeLeft(PotionInfo.kt:13)
```
oopsy
