### ISSUE TITLE
Crash when loading a world

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1261]
**Describe the bug**
On a clean install, just after joining a world, single or multiplayer, the game crashes.

**To Reproduce**
1. Download and install kamiblue-1.1.7-6db2b038-release.jar;
2. Load any world;
3. Crash.

**Expected behavior**
The world loads fine.

**Screenshots**
No.

**Additional context**
Crash report [https://pastebin.com/w0bUFgDg](https://pastebin.com/w0bUFgDg)

**Comment by dominikaaaa** [comment]
```
java.lang.IncompatibleClassChangeError: Expected non-static field baritone.api.utils.BetterBlockPos.field_177990_b
	at baritone.j.a(Unknown Source)
```
disable `-noverify`, baritone bug

**Comment by dominikaaaa** [comment]
https://github.com/cabaletta/baritone/issues/1185
https://github.com/kami-blue/client/issues/1093

**Comment by omninope** [comment]
Oh god, that's what i get for messing with stuff that i don't fully understand. I'm sorry about the inconvenience.

**Comment by dominikaaaa** [comment]
All good lmfao
