### ISSUE TITLE
Aimbot aims at feet

### ISSUE THREAD

**Issue by Voxel6991** [kami-blue/client#1262]
**Describe the bug**

Kami Blue's aimbot module aims at the feet of a player (or more accurately the center of the bottom face of an entity's hitbox) instead of their head or body.

**To Reproduce**

1. turn on aimbot
2. aim at player
3. shoot foot

**Expected behavior**
Aimbot aims at the eye position or the center of the target.

**Screenshots**

![image](https://user-images.githubusercontent.com/70432663/91634114-ba6e8380-e9a2-11ea-984f-2d0f2c7a8d85.png)

**Additional context**
At some point in the 1.17 betas the aimbot changed from aiming at the eye position of the target, to the middle of the target, and now to the bottom of the target. I'll figure out the versions in which this change happened sometime tomorrow.

**Comment by dominikaaaa** [comment]
> **Update Aimbot:** Make a choice on which part of the player's body the aimbot will be.

Moving this from #1267, as it first better here as a solution to this issue.
