### ISSUE TITLE
mcprison.com fix auto-mine on the beacons

### ISSUE THREAD

**Issue by Slhsmile** [kami-blue/client#1268]
Go to the server and write /warp robot and turn on auto-mine on beacons. After you turn it on and try to farm beacons instead of a pickaxe, switch to 1 slot where the backpack is located, but you can only break these beacons with a pickaxe. That's the problem, you need an auto-mine to break the beacons with a pickaxe.

**Comment by dominikaaaa** [comment]
In the future you'll be able to do `#autoMine false`

This exact issue was documented here: https://github.com/cabaletta/baritone/issues/1334

See #1269 for reference.
