### ISSUE TITLE
Potential TpsSync crash 

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#1277]
If the user has LoginMessage or some other program to start baritone when connecting, if you have TpsSync enabled and it wants to mine, it's possible it will crash because LagCompensator returns 0 for the first second after connecting, since it hasn't had time to calibrate.

I had to fix PotionInfo crashing for the same reason in https://github.com/kami-blue/client/commit/a66d954fb58a52ca151dc5ee18be24b97d4575de

TpsSync uses it here: https://github.com/kami-blue/client/blob/ef0bff9813c66c9397f48a2e1ae79dd8dfa4e760/src/main/java/me/zeroeightsix/kami/mixin/client/MixinPlayerControllerMP.java

**Comment by Xiaro** [comment]
max(tps, 0.1)?

**Comment by dominikaaaa** [comment]
hm?

**Comment by dominikaaaa** [comment]
oh I see what you're saying. that would've been a better solution for potionui

**Comment by Xiaro** [comment]
> oh I see what you're saying. that would've been a better solution for potionui

Tps dropping to 0.1 is a very rare cases so we can just add it to LagCompensator and ez fix

**Comment by dominikaaaa** [comment]
No, the crash is caused by a dividing by 0 error, because the tps is literally 0. It should return 20 if the tps is 0, because it takes a full second to calibrate the tps when you join a world

**Comment by Xiaro** [comment]
> No, the crash is caused by a dividing by 0 error, because the tps is literally 0. It should return 20 if the tps is 0, because it takes a full second to calibrate the tps when you join a world

Then `if (tps == 0.0f) return 20.0f?`

**Comment by dominikaaaa** [comment]
yes 

except the ? at the end, it's not null lmfao

**Comment by Xiaro** [comment]
Wait why don't we just fill the Array with "20"s instead of "0"s at the beginning lol
https://github.com/kami-blue/client/blob/73361bdd68dc2fc874c6338aceb1af372f95da6a/src/main/java/me/zeroeightsix/kami/util/LagCompensator.kt#L39-L43

**Comment by dominikaaaa** [comment]
That won't reset when changing servers?

**Comment by Xiaro** [comment]
> That won't reset when changing servers?

It doesn't really matter much because it would be calibrate eventually

**Comment by dominikaaaa** [comment]
I was thinking more along the lines of, won't it get reset to 0?

If not, I guess that solution is okay? I'd prefer the return one because it's more clear what it's doing
