### ISSUE TITLE
Unify config system 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1281]
I'm extremely happy with how I made the config system in kami-blue/bot-kt, and it's extremely modular and easy to use. 

I'd like to port it to KAMI Blue, as we're constantly adding new config types, I feel it would simplify things and fix the existing code which has several issues, such as #1001

Required for #310. I'll do this when I get back from vacation, shouldn't take too long

**Comment by Xiaro** [comment]
What is the point of this when we have #1283 and #1512

**Comment by l1ving** [comment]
true
