### ISSUE TITLE
Fastfall bugs 

### ISSUE THREAD

**Issue by ThugPenguin1** [kami-blue/client#1282]
**Describe the bug**
 fastfall hole only works only on nonhole, chats number go brrr

**To Reproduce**

1. Go to 'fastfall'
2. Click on 'holeonly
3. Try and run around
4. See error, rubber band too(look at chat too) 

**Expected behavior**
 gravity pull on hole only

**Screenshots**
 not on my PC rn

**Additional context**
 rubber bands tend to happen a lot,

**Comment by dominikaaaa** [comment]
That's not rubberbanding, that just means holeonly is inverted.

**Comment by ThugPenguin1** [comment]
I tried running with fast fall open at all times it didn't put me in a hole it put me somewhere in mid levels from top and bottom of bedrock like most exposed places

**Comment by dominikaaaa** [comment]
See my previous comment
