### ISSUE TITLE
Baritone doesn't save settings properly in specific situations 

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1284]
**Describe the bug**
The AutoWalk module on BARITONE mode ignores any modified settings under Client > Baritone after a restart and just uses the defaults. I don't think this is intended.

**To Reproduce**
1. Enable AutoWalk on BARITONE mode;
2. Change some settings under Client > Baritone that will have an obvious effect, like AllowBreak or FreeLook;
3. AutoWalk respects the changes - expected;
4. Close the client and restart it;
5. The modified settings under Client > Baritone will still be the same way you left it - expected;
6. Enable AutoWalk;
7. AutoWalk just ignores the settings and act like it's on the default settings.

**Expected behavior**
It should respect the changed Baritone settings.

**Screenshots**
Probably not needed.

**Additional context**
Version: Literally the latest possible, just downloaded the source and build minutes ago.
Modules enabled: Just the AutoWalk.
Didn't test on other Baritone related things.

**Comment by dominikaaaa** [comment]
> The AutoWalk module on BARITONE mode ignores any modified settings under Client > Baritone after a restart and just uses the defaults. I don't think this is intended.

That sounds like your Baritone settings didn't get properly set or reset. If you can *consistently* reproduce this with a clean .minecraft please reopen.

**Comment by omninope** [comment]
I don't think that matters because I always run every mod or combination of mods in their own folder but I did it anyway. Removed everyting from .minecraft, removed minecraft, reinstalled minecraft, reinstalled forge, reinstalled KAMI Blue (the same one i used earlier), left everyting at default and retested following the procedure described when i opened the issue and ... it still happens ... every time.
About reopening this issue, is this even someting that I can do?

**Comment by dominikaaaa** [comment]
Juat toggle the options, it means they weren't saved properly. I'll reopen this but it feels like a baritone bug

**Comment by dominikaaaa** [comment]
Oh yea I just realized why this happens. I'll fix it today

**Comment by omninope** [comment]
Reopen this. The exact same problem is happening again on a clean install.
Build on commit 98048da293e163559393ec43f9fb1120805f2121.

**Comment by l1ving** [comment]
Can you describe how you currently reproduced this?

**Comment by omninope** [comment]
The same way as before, using AutoWalk on baritone mode, following the steps:

1. Enable AutoWalk on BARITONE mode;
2. Change some settings under Client > Baritone that will have an obvious effect, like AllowBreak or FreeLook;
3. AutoWalk respects the changes - expected;
4. Close the client and restart it;
5. The modified settings under Client > Baritone will still be the same way you left it - expected;
6. Enable AutoWalk;
7. AutoWalk just ignores the settings and act like it's on the default settings.

**Comment by l1ving** [comment]
How did you restart it?

**Comment by omninope** [comment]
Set the Baritone options in the ClickGUI, press Esc to exit, then Esc > Save and Quit to Title > Quit Game, and to restart I just click the huge green button in the vanilla launcher.

**Comment by l1ving** [comment]
That sounds like a Baritone bug then, because all the Baritone module does is tell Baritone to change the setting
