### ISSUE TITLE
AutoTool doesn't recognize 'monster_egg' AKA Silverfish Stone

### ISSUE THREAD

**Issue by jumboman32** [kami-blue/client#1288]
**Describe the bug**
AutoTool does not switch to a pickaxe to mine silverfish stone.

**To Reproduce**
1. Toggle AutoTool (with a pickaxe in your inventory)
2. Attempt to mine silverfish stone.

**Expected behavior**
AutoTool will switch to your pickaxe and mine it.

**Comment by jumboman32** [comment]
this is pretty low priority but trying to clear out an area in a mountain biome is painful

**Comment by dominikaaaa** [comment]
Autotool uses whatever Minecraft says is the best tool, this probably means monster eggs don't mine faster with pics

**Comment by jumboman32** [comment]
It does mine faster, but I guess it's a Minecraft issue. Thanks for a quick response.

**Comment by dominikaaaa** [comment]
That's weird, sorry about that.
