### ISSUE TITLE
Enhancement for AutoObsidian

### ISSUE THREAD

**Issue by sirOzon** [kami-blue/client#1289]
When ;b schematica runs out of materials one has to manually come and refill their inventory for it to keep working. This can be frustrating.
A solution i have thought of is to use the module AutoObsidian but allow to change the "item refill" to a custom item, making it auto refill to an item of your choosing when set item runs out in your inventory.

Hopefully Im explaining myself well enough.

**Comment by dominikaaaa** [comment]
AutoObsidian is only for mining ender chests. InventoryManager already has an autorefill option

**Comment by sirOzon** [comment]
I didnt explain correctly then.

AutoObsidian when the obsidian is missing it will automatically open a shulker and retrieve the items from it.
Thats the feature im looking for. Inventory manager doesnt have that, it only refills from the inventory.

**Comment by dominikaaaa** [comment]
Then that would be a suggestion for InventoryManager, or probably another module since it's so specific

**Comment by dominikaaaa** [comment]
#1290

**Comment by sirOzon** [comment]
Epic, thanks.
