### ISSUE TITLE
BaritoneRemote -> RemoteEcho

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1291]
Expand the functionality to just work with all KAMI Blue commands / regular messages

**Comment by l1ving** [comment]
Moving, will complete after #1621

**Comment by iBuyMountainDew** [comment]
Should we just remove support for direct Baritone commands entirely and just have people use the `;baritone` command?

**Comment by l1ving** [comment]
Yes, though the entire module deserves a rewrite

**Comment by iBuyMountainDew** [comment]
:pensive:

**Comment by l1ving** [comment]
I had this issue self assigned, not sure what you expected 

Grab some of the million other issues which aren't assigned to anybody

**Comment by iBuyMountainDew** [comment]
Bruv they might as well all be assigned to you two; f*ck tons of them require delving into or fanagling around the non-extensible bullsh*t to understand reinvent-the-wheel systems you two have made.

**Comment by l1ving** [comment]
Then ask for clarification?

**Comment by iBuyMountainDew** [comment]
Would be crazy cool if I don't end up looking like a dumbass every time, get flamed and have the task taken over.

**Comment by l1ving** [comment]
That's a you problem, it's all in your head

**Comment by iBuyMountainDew** [comment]
No no no; this is a you and Xiaro circlejerk problem. Noone but you two are thinking what you're saying.

**Comment by l1ving** [comment]
No, that's a genuinely *pull your head out of your ass and learn to start asking questions instead of choosing to stay in the dark* moment

**Comment by iBuyMountainDew** [comment]
As if you're one to talk. Noone wants to look like a fucking idiot, and deciphering the bullshit systems you two have is so pain inducing. I'm in no mood for this since I feel like an absolute dipshit for the commit I made earlier.

**Comment by l1ving** [comment]
I'm trying to help, I even assigned two issues to you that you'd understand without needing clarification. You need to learn to just ask for fucking clarification if you're unsure of something. Going around in circles like "but X will happen" when you never even bother trying is entirely useless and unproductive. I don't see how you can be fit for this project if you don't even want to make an effort at amending the bullshit you have going on with xiaro and actually trying to ask questions.
