### ISSUE TITLE
Offhand thing

### ISSUE THREAD

**Issue by ThugPenguin1** [kami-blue/client#1292]
**Is your feature request related to a problem? Please describe.**
 auto totem is automatic. Ex. The health below 5 Is change to offhand, but, there are chances when a crystal can just kill you over 5. So not able to use totems properly. But if I set it higher I can't chug gaps cuz it will change and have to change hotbar

**Describe the solution you'd like**

Mouse forward and backward button, I think they are called mouse4 or 5 or 6. So, you can pick the order like gaps totem crystal and obsidian, and then you  start with totem if I press forward it will have gapples but if backwards crystal, just something like that.
**Describe alternatives you've considered**
 start from 0 press forward button for 1 press back to 0, press forward 2 times and it will go 0 then 1 then 2. Press back 2 times and it will go to 1 then 0 

**Additional context**

Put in low priority cux living is in a vacation

**Comment by dominikaaaa** [comment]
This isn't possible due to lwjgl limitations.
