### ISSUE TITLE
AutoEat option to eat bad food 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1293]
Such as rotten flesh

**Comment by exape** [comment]
At the moment, the player cannot autoeat :
- Rotten flesh
- Spider eye
- Poisonous potato
- Pufferfish & clown fish
- Chorus fruit

But, should the option really allow the player to eat chorus fruit ?

**Comment by l1ving** [comment]
Maybe just the former options, ignore chorus fruit anyways

**Comment by Xiaro** [comment]
Already closed by #1543
