### ISSUE TITLE
Combining Existing Modules

### ISSUE THREAD

**Issue by jumboman32** [kami-blue/client#1296]
ExtraTab and Tab Friends
Tab Friends should be an option with ExtraTab.

AntiFog and AntiOverlay
AntiFog should be combined with AntiOverlay or NoRender.

AntiChainPop And Surround.
Make it an option under Surround.

FastBreak and FastUse >> FastInteract

Logout Logger and Waypoints

NoHurtCam and NoRender

AutoNameTag and AutoSpawner

Timer and TPS Sync

**Comment by dominikaaaa** [comment]
> AntiChainPop And Surround.
> Make it an option under Surround.

No, they're completely different modules.

> AntiFog should be combined with AntiOverlay or NoRender

AntiFog should be rewritten*

> Logout Logger and Waypoints

What????

> Timer and TPS Sync

Absolutely not, that's counter intuitive.

> AutoNameTag and AutoSpawner

No, people want to nametag existing withers sometimes, or rename them. 

> FastBreak and FastUse >> FastInteract

FastUse already has a blocks option, it would be confusing

> Tab Friends should be an option with ExtraTab.

This just makes the client less customizable
