### ISSUE TITLE
Aura shouldn't do anything with autotool disabled and not holding a weapon 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1297]

**Comment by eliasfakhiri** [comment]
make this a toggleable thing also make it a thing for c aura

**Comment by dominikaaaa** [comment]
did you try reading the issue title?

**Comment by Xiaro** [comment]
I don't think this is necessary and sometimes you need to fist someone

**Comment by dominikaaaa** [comment]
Specifically with autotool disabled. When autotool is enabled but you don't have a tool, the desired behavior is to keep attacking

**Comment by eliasfakhiri** [comment]
why am i getting emails for this bruh

**Comment by dominikaaaa** [comment]
because you subscribed to it

**Comment by eliasfakhiri** [comment]
i’m suing git hub
