### ISSUE TITLE
Able to hide certain modules in the GUI

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1302]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when KamiBlue has too many modules that I don't use which clogs up the GUI

**Describe the solution you'd like**

Shift ctrl whatever button you want + click a module to toggle hide it, with a button to show hidden modules.

**Describe alternatives you've considered**

Not do this lol

**Additional context**

Probably best for the GUI update

**Comment by dominikaaaa** [comment]
You can already do this

**Comment by GoodPro712** [comment]
Visibility as in from the GUI not the Active Modules list. I'll link this in the gui issue
