### ISSUE TITLE
Signs for NoRender

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1303]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I read signs from meanies :( 

**Describe the solution you'd like**

A sign option in NoRender that doesn't render text on signs

**Describe alternatives you've considered**

A new module

**Additional context**

This probably already exists lol

**Comment by l1ving** [comment]
SignText is now an option, for entirely not rendering signs see #1508
