### ISSUE TITLE
Map names shown for MapPreview

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1304]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I can't see the names of my maps when I use MapPreview

**Describe the solution you'd like**

Show map names

**Describe alternatives you've considered**

I haven't considered any

**Additional context**

Seems like a bug

**Comment by GoodPro712** [comment]
like, the actual name of the item

**Comment by dominikaaaa** [comment]
Duplicate of #957

**Comment by GoodPro712** [comment]
didnt see that, sorry
