### ISSUE TITLE
Font option for customchat

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1305]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when CustomChat speaks in an unreadable font
![image](https://user-images.githubusercontent.com/45357714/92324816-71948a00-f088-11ea-827b-541478e9e4c1.png)

**Describe the solution you'd like**

title.

**Describe alternatives you've considered**

reeeeeeeeeeeeeeeeeeeee

**Additional context**

I can't read it but that might be from my res (which isn't that small)

**Comment by dominikaaaa** [comment]
I can read it just fine on my computer. You can use a custom ending or install smoothfont or something

**Comment by GoodPro712** [comment]
it was my chat size
