### ISSUE TITLE
X-Ray Not Rendering Ores

### ISSUE THREAD

**Issue by jumboman32** [kami-blue/client#1306]
**Describe the bug**
When I try to toggle X-Ray it doesn't render ores.

**To Reproduce**
1. Toggle X-Ray with the "Invert" option selected.

**Expected behavior**
X-Ray should not render the stone and other blocks and only render ores.

**Screenshots**
https://www.youtube.com/watch?v=xRvpTMZX-VE&ab_channel=jumboman32

**Comment by dominikaaaa** [comment]
That depends on what blocks you have selected. The invert option inverts your block list

**Comment by dominikaaaa** [comment]
> X-Ray should not render the stone and other blocks and only render ores.

Sounds like you should disable the invert option
