### ISSUE TITLE
Friends Category too large

### ISSUE THREAD

**Issue by jumboman32** [kami-blue/client#1307]
**Is your feature request related to a problem? Please describe.**
Yes, when you have too many friends on Kami Blue, the friends tab is too large and covers different categories.

**Describe the solution you'd like**
A way to move category windows other than dragging from the top.

**Describe alternatives you've considered**
Resetting my config.

**Additional context**
https://gyazo.com/37e75ad0eb0508de571d3dd82a80bd5c

**Comment by dominikaaaa** [comment]
Well you can minimize it. Another way to move hud elements will only be possible in the gui rewrite. Use `;fixgui` for now.
