### ISSUE TITLE
Nofall bucket pickup doesn't calculate properly 

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1308]
**Describe the bug**

I'm frustrated wh- oh this is a different template
title.

**To Reproduce**

1. turn nofall bucket on
2. fall
3. possibly die

**Expected behavior**

1. turn nofall bucket on
2. fall
3. no chance to die

**Additional context**

**Comment by dominikaaaa** [comment]
Disable `pickup` lol

**Comment by GoodPro712** [comment]
cwinge
