### ISSUE TITLE
Let donators choose/upload custom capes

### ISSUE THREAD

**Issue by kars0nn** [kami-blue/client#1316]
Bascically when someone donates, they will have a default cape, but they can upload their own cape via bot or something easy so you don't have to manually do it. This would be beneficial to groups and people who want have hentai capes... and it would bring in more donations since a lot of people have kami blue.

**Comment by dominikaaaa** [comment]
![image](https://user-images.githubusercontent.com/17222512/92427751-45960900-f15b-11ea-80bd-d20908c4b330.png)

**Comment by kars0nn** [comment]
dam rip

**Comment by GoodPro712** [comment]
F

**Comment by dominikaaaa** [comment]
Contest winners get custom cape colors, and we're figuring out a custom star system for donations / boost / contributions

**Comment by dominikaaaa** [comment]
I'm not doing fully custom images because of the security risk.

**Comment by kars0nn** [comment]
i can understand that

**Comment by humboldt123** [comment]
We could make a cape editor on the site

**Comment by dominikaaaa** [comment]
See above

**Comment by humboldt123** [comment]
I didn't say fully custom. I mean like how optifine has it. You can choose a color, an icon, and maybe a border.

**Comment by dominikaaaa** [comment]
Isn't that what the already existing cape editor is for?
