### ISSUE TITLE
AutoGarden

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1317]
**What My Module Request Is**
A module that breaks all grass and or flowers around you, with a config for breaking grass, flowers or both

**Why You Should Add It**
You should add this module because it's useful if you want to clear the grass out of an area or if you want to quickly harvest flowers/seeds

**Extra Comments**
N/A

**Comment by FluorideHistorian** [comment]
literally just nuker

**Comment by GoodPro712** [comment]
duplicate
