### ISSUE TITLE
Custom Message for Visual Range

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1320]
**Is your feature request related to a problem? Please describe.**

I don't like the default message and want to change it

**Describe the solution you'd like**

A command with a custom option for the message sent in chat when a player appears in visual range

**Describe alternatives you've considered**

🤷‍♂️ 

**Additional context**

None

**Comment by l1ving** [comment]
#1510 / #790 makes string settings editible in the GUI
