### ISSUE TITLE
Step Buggy When the Block has a Layer of Snow

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1321]
**Describe the bug**

When using step, stepping up a block which has snow on it rubberbands you occasionally

**To Reproduce**

Enable Step
Go up blocks with snow layers on them

**Expected behavior**

To not rubberband and act normal

**Screenshots**

Things like this:
http://i.imgur.com/tda8FAT.png

**Additional context**

Don't know if this is the anticheat. Happened on oldfag.org

**Comment by dominikaaaa** [comment]
Change your height setting

**Comment by GoodPro712** [comment]
1.5 doesnt work on any blocks (its patched)
