### ISSUE TITLE
Wrong GUI Size on TotemPopCounter

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1322]
**Describe the bug**

The size is too short and text goes out of the box

**To Reproduce**

Right click on the TotemPopCOunter module

**Expected behavior**

To be the correct size

**Screenshots**

![image](https://user-images.githubusercontent.com/45357714/92459476-1ab6be00-f20a-11ea-85b1-49d4330ace22.png)

**Additional context**

None

**Comment by dominikaaaa** [comment]
#790
