### ISSUE TITLE
AutoSheer

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1323]
**Is your feature request related to a problem? Please describe.**

I'm a lazy ass who can't click a few buttons.. but that's what automation is for right?

**Describe the solution you'd like**

Automatically sheers sheep in range of the player. Option for automatically switching to sheers.

**Describe alternatives you've considered**

N/A

**Additional context**

Not the most useful thing that can be added

**Comment by dominikaaaa** [comment]
Duplicate
