### ISSUE TITLE
AutoTotem option to check for nearby crystals against health setting

### ISSUE THREAD

**Issue by Augustinger** [kami-blue/client#1329]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

PLZ add offhand crystal and Switch to totems when you take fatal damage, such as jumping out of hole, or when obsidian is dug out from under your feet.

**Describe alternatives you've considered**

**Additional context**

![SHANA offhand](https://user-images.githubusercontent.com/31059777/93009939-1cd99d80-f5b9-11ea-9d61-c2ed3d2f7716.gif)

**Comment by dominikaaaa** [comment]
AutoTotem already has a health option. It doesn't have a crystal damage calculation option.

**Comment by Xiaro** [comment]
Planned for feature/Combat
