### ISSUE TITLE
Strafe and sprint options to pause during Baritone 

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#1333]
Since baritone has its own sprint mechanism and calculations, it needs to stop sprinting sometimes. An option to pause strafe and sprint during baritone would be cool

**Comment by Xiaro** [comment]
Why optional tho, they aren't even working with baritone. So just make it always stop strafe and sprint whenever baritone is running. Same with step.

**Comment by dominikaaaa** [comment]
I'd rather it be optional or people will complain

**Comment by dominikaaaa** [comment]
Just like step and safewalk, just make a `BaritoneCompatibility` setting which is on by default

**Comment by Xiaro** [comment]
> I'd rather it be optional or people will complain

No they won't, instead they would complain about breaking with baritone if they have the option off

**Comment by dominikaaaa** [comment]
good point. just make both of them return if baritone is active I guess

**Comment by dominikaaaa** [comment]
See https://github.com/kami-blue/client/commit/1ef84ff5c32c79a2e172290ec179180eba568185
