### ISSUE TITLE
Blink reset option

### ISSUE THREAD

**Issue by Doogie13** [kami-blue/client#1336]
A way of intentionally cancelling blink so that you effectively never blinked at all (going back to where you were when you entered the blink state). 
This should be possible as the server has never received the movement packets so if they are never sent then you will just essentially rubber band back to where you started. 
Maybe a bind to cancel the blink packets from ever being sent?

**Comment by Xiaro** [comment]
Why not just use freecam?

**Comment by Doogie13** [comment]
You may start to use blink but end up wanting to go back. this is not for exploration etc but for if you blink wrongly

**Comment by dominikaaaa** [comment]
So, an option to not send the packets you collected while blinking?

**Comment by Doogie13** [comment]
Yes, that exactly
