### ISSUE TITLE
Remove unneeded deps

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1341]
Currently we import the ENTIRE Kotlin std libraries + coroutines for... some reason?

**Comment by Nathan-Webb** [comment]
maybe remove the `dummyThing` from the gradle as well?
https://github.com/kami-blue/client/blob/master/build.gradle#L150

**Comment by dominikaaaa** [comment]
> `// can someone explain why this is here`

**Comment by Nathan-Webb** [comment]
I think you were the one who added it lmao, unless I don't know how to use blame which might be the case.
https://github.com/kami-blue/client/blame/fce2bd3d902c56b54495b7d4ad65857763cf7475/build.gradle#L138
Was it copied over from the old kami repo?

**Comment by Nathan-Webb** [comment]
Searched around and it seems to be a common thing in some shadowjar gradle scripts, I'll check the documentation.

**Comment by dominikaaaa** [comment]
> Was it copied over from the old kami repo
<https://github.com/kami-blue/client/commit/2429a4dd1e868c3c7e05db0736cda09f8ecacf35#diff-c197962302397baf3a4cc36463dce5ea>

Yes.

**Comment by Nathan-Webb** [comment]
The only thing I can find from any source that I know has some form of competency is from SpongeCommons. It appears they use it alongside another exclusion for ForgeGradle stuff?

https://github.com/SpongePowered/SpongeCommon/blob/08c64489eef2acc59779aa535c9a2bb3f9b43052/gradle/implementation.gradle#L168

**Comment by dominikaaaa** [comment]
Idk lol. I was gonna rewrite the Gradle in Kotlin

**Comment by Nathan-Webb** [comment]
Fair! I might test out what actually changes if you keep the line vs remove it.
