### ISSUE TITLE
NoFall void only option 

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1345]
**Is your feature request related to a problem? Please describe.**
Yes, nobody likes accidentally falling into the void.

**Describe the solution you'd like**
A module that, when enabled, checks if the player is walking or jumping and the end position of that action is inside the void, if true the player movement is cancelled, effectively "teleporting" the player back. If the player is jumping over the void but the end position isn't the void don't cancel the movement.
Maybe this is better suited as an option under NoFall and not a new module like I suggested, since it's NoFall and the idea is to prevent you from falling into the void.
If this is ever going to be coded, remember elytras and remember that people will use them over the void, especially but not exclusively in the end, and they will leave this option/module enabled amidst hundreds of other modules, so make it compatible with ElytraFlight and elytras in general after takeoff.

As a side note, this seems like a better solution than #1344 but i think having both is a better idea, since the player can get confused if it lags back or rubberbands and there is no obvious visual feedback of why.

**Describe alternatives you've considered**
Well, there is SafeWalk, but it is annoying in general, except when needed, and if the player jumps, SafeWalk will not prevent falling in the void.

**Additional context**
As an reference of what I'm trying to describe see Inertia's AntiVoid module under Movement > Anti Void.

**Comment by dominikaaaa** [comment]
> A module that, when enabled, checks if the player is walking or jumping and the end position of that action is inside the void, if true the player movement is cancelled, effectively "teleporting" the player back. If the player is jumping over the void but the end position isn't the void don't cancel the movement.

Wouldn't nofall catch satisfy this?

**Comment by omninope** [comment]
I had to test it because I never use NoFall (it is just annoying 90% of the time), but the conclusion is this is basically what I was talking about, teleporting the player right back, at least that happened on Constantiam and over normal terrain, unfortunatelly I can't test over the void on Constantiam. I tested it in my random test server and it didn't work, neither in a vanilla server, but i think that's expected?
Now, if NoFall literally does the same thing described, I don't know if this suggestion is still valid. Maybe adding an option to NoFall to only work over the void?

**Comment by dominikaaaa** [comment]
NoFall in catch mode will teleport you back to where you were before you fell. If you drag the min fall height to like 500 or whatever it'll only work over void

**Comment by dominikaaaa** [comment]
feel free to reopen this if you feel it isn't adequate

**Comment by Xiaro** [comment]
Maybe add a void only option?

**Comment by dominikaaaa** [comment]
> If you drag the min fall height to like 500 or whatever it'll only work over void

**Comment by Xiaro** [comment]
> > If you drag the min fall height to like 500 or whatever it'll only work over void

Yes but `mc.player.fallDistance` is counting the fallen distance not the distance to the surface below. So you have to fall for 500 blocks to get it activated. And you are very likely gonna flags ncp like this.

**Comment by dominikaaaa** [comment]
OHHH I see
