### ISSUE TITLE
Config Presets

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1352]
**Is your feature request related to a problem? Please describe.**
It's annoying when I have to enable/disable 12 modules if I want to do something, then disable/reenable those to go back to what I was doing. ie. I would create a preset for basing and a preset for pvp so when I want to pvp I can choose the pvp preset, and when I want to do normal basing/stuffing around I would choose the basing preset and it would enable all the modules I have set for this preset.

**Describe the solution you'd like**
A UI or command that when you press a button or write something like `;preset save "Basing"` it would save a preset with all the currently enabled modules and their respective config, then when I would want to use that preset I would write something like `;preset load "Basing"`

**Describe alternatives you've considered**
The alternate of this, which already works in the current versions, is to swap around config files to do certain things, but the issue with this is that you would have to close Minecraft just to swap the config around, which can be frustrating when Minecraft takes a while to load. A preset system like this would be much easier to use as a KAMI Blue user.

**Additional context**
Presets can be for pvp, basing, base hunting, presets for multiple servers as anti cheats change, etc, etc. I would find a present system much more user friendly than what we currently have to do.

**Comment by dominikaaaa** [comment]
You can use config presets to do this
