### ISSUE TITLE
GUI editor suggestion 

### ISSUE THREAD

**Issue by ThugPenguin1** [kami-blue/client#1362]
**Is your feature request related to a problem? Please describe.**
 it's not a beginner friendly GUI , so I'm suggesting something 

**Describe the solution you'd like**

Making ur own gui by urself
**Describe alternatives you've considered**

making list like render or movement or whatever by people themselves and putting modules in it by themselves, button size color font 

**Additional context**
it's just a suggestion

**Comment by dominikaaaa** [comment]
#790
