### ISSUE TITLE
When using Freecam can't break or place crystal

### ISSUE THREAD

**Issue by Augustinger** [kami-blue/client#1363]
**Is your feature request related to a problem? Please describe.**

When using a freecam, excavating blocks is particularly slow and crystals cannot be placed and break. 

**Describe the solution you'd like**

Make it a freecam like Impact that doesn't interfere with other activities when you use it.

**Describe alternatives you've considered**

**Additional context**

**Comment by dominikaaaa** [comment]
#1174, #530
