### ISSUE TITLE
Option to disable AutoWalk on Disconnect

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1364]
**Is your feature request related to a problem? Please describe.**

It's annoying when im afk flying and get dced with autoreconnect and have to turn autowalk on every time i get dced

**Describe the solution you'd like**

read title.
currently you cant turn this "feature" off. i'm suggestion for the availability to do that

**Describe alternatives you've considered**

N/A

**Additional context**

packet fly sucks

**Comment by dominikaaaa** [comment]
Making it optional will leave you with a completely useless enabled autowalk. It intentionally turns off because baritone doesn't handle resuming the goal properly and the server doesn't always rotate you correctly right away. 

Use loginmsg if you want to start a goal on connect.
