### ISSUE TITLE
Read Macros from file

### ISSUE THREAD

**Issue by HoratioGamer** [kami-blue/client#1366]
**Is your feature request related to a problem? Please describe.**
I want to be able to create a text file of keyboard macros that I can share with other players

**Describe the solution you'd like**
By default read a fixed filename of keyboard macros when KAMI starts
On Command, read a different file of keyboard macros when the user asks for a file to be read.

**Describe alternatives you've considered**
Typing in keyboard macros is a pain.

**Additional context**
none

**Comment by l1ving** [comment]
I'm closing this as invalid, as I pinged you on Discord earlier. 

> By default read a fixed filename of keyboard macros when KAMI starts

I'm not sure how you thought we stored it, but they're stored in `KAMIBlueMacros.json`. 

>  On Command, read a different file of keyboard macros when the user asks for a file to be read.

If you want this to be added then let me know and I'll reopen this for a future milestone.
