### ISSUE TITLE
AutoObsidian's packet mining doesn't respect TpsSync

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1373]
Mines at a different speed and stops too early on low tps

**Comment by Xiaro** [comment]
Packet mining is faster than the vanilla mining. It is intentional
And It would still work properly on low tps. Tested on 2b2b.

**Comment by l1ving** [comment]
I've had multiple people report it causes a kick on 2b. Maybe make an option to make it respect tpssync?

**Comment by Xiaro** [comment]
> I've had multiple people report it causes a kick on 2b. Maybe make an option to make it respect tpssync?

It is probably other issues like Freecam or something. I never got kicked with it at all

**Comment by Xiaro** [comment]
And 2b has higher tps now. Also I think hause has a plugin that allows you mining block at the same speed in low tps

**Comment by Xiaro** [comment]
TpsSync is client side only while Packet Mining is server side. So this would be impossible.
