### ISSUE TITLE
Quality of life with freecam 

### ISSUE THREAD

**Issue by Doogie13** [kami-blue/client#1374]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by l1ving** [comment]
I assume you mean #530, but there's so little information I'm guessing

**Comment by Doogie13** [comment]
> I assume you mean #530, but there's so little information I'm guessing 

I have no experience with GitHub markup and I think the original post was formatted incorrectly. I've removed all the formatting so the content is actually visible.
Sorry I was in a rush.

**Comment by l1ving** [comment]
Well your edited version is a duplicate of #254 and #263 which is a won't fix

**Comment by Doogie13** [comment]
Example:  
![example_pip_freecam#](https://user-images.githubusercontent.com/62295632/94574129-b1572780-026a-11eb-8d8c-d8f3c89733ba.png)

**Comment by l1ving** [comment]
read my above comment

**Comment by Doogie13** [comment]
> read my above comment

sorry I uploaded the screenshot before I refreshed the page
