### ISSUE TITLE
Build and version system improvements

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1376]
This is just a summary of how an earlier discussion went. 

### Versioning

We're switching away from the `v1.MAJOR.MAJOR-COMMIT` system, in favor of `y.mm.dd-hash`. 

An example for a current release would be `1.09.29-abcdefg`, or `2.01.01` for a planned major release in January. 

### Build system

We would like to add the following things to make future version information more machine-parsable and for some things such as configs and update checkers. 

- Build number 
  - Incremented by 1 with each new release
  - Planned to be used for update checker as below, and for saving a `KAMIBlueConfig.json.old` backup with each new version (maybe with a different name to reduce user confusion as Windows hides file extensions)
- ~~Bugs fixed~~
  - ~~Incremented by bugs fixed~~
  - ~~Planned to be used for update checker in the format of "You are X updates out of date, missing Y bug fixes"~~

### Process

- [x] Generate release number based off of R.MM.DD-hash
- [x] Change version to release number in all instances with sed
- [x] Update jar build number
  - [x] This shouldn't need to commit anything, except to jekyll. Instead, take the latest build number from remote and add 1 
- [x] Build binary
- [x] Rename to remove `-release`
- [x] Collect a list of commits since this was last run
- [x] Pretty format the list of commit subjects
- [x] Upload binary and changelog to github
- [x] Update a jekyll config with the new latest release number
- [x] Update a jekyll config with latest build number
- [x] Send a pretty formatted discord message with 
  - [x] Commits diff
  - [x] Github release link
  - [x] Changelog

### Tested

- [x] `buildNamed.sh`
- [x] `bumpMajor.sh`
- [x] `bumpVersion.sh`
- [x] `bumpWebsite.sh`
- [x] `changelog.sh`
- [x] *`hook.sh`
- [x] *`preHook.sh`
- [x] *`releaseNightly.sh`
- [ ] `runAutomatedRelease.sh`
- [x] *`testing.sh`
- [x] `uploadRelease.sh`
- [x] `utils.sh`
- [x] `version.sh`

*to be removed

**Comment by natan515** [comment]
Last issue for 1.1.7 release gg
