### ISSUE TITLE
Aura should attack specific parts of the body and automatically select which part for optimal distance

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1377]
Two parts, an enhancement and a bug 

First, you should have an option to select a specific part of the body to target (feet, chest, head etc)

Second, Aura currently targets the feet by default afaik, it should attempt to face the optimal target by default.

For example, if you're 1 block higher then someone and 4.3 blocks away, it should attack their head as that's closer then the feet, and so on.

A bit of basic trig can calculate which part of the body is best to target

**Comment by Xiaro** [comment]
Already fixed in combat branch 🗿

**Comment by l1ving** [comment]
oh pog
