### ISSUE TITLE
Add crafting slots to InventoryViewer

### ISSUE THREAD

**Issue by Natan515** [kami-blue/client#1379]
hello, i would like you to upgrade the inventory viewer so 1: it wont show the kami pic behind cus its rly anoying and make it harder to see, and add an optional 4 slots of the crafting place, cus people keep there stuff, this is the only resone why i still use salhack with ur hack.

**Comment by GoodPro712** [comment]
theres an option to turn off the logo

**Comment by natan515** [comment]
ye i saw but i want to have that u can see in your crafting place, like in salhack.

**Comment by l1ving** [comment]
I don't see why you need to see what's in your crafting slots so badly honestly.

**Comment by Natan515** [comment]
Its not important

**Comment by l1ving** [comment]
That's why it's marked as low priority, yes. But it's not trivial to implement

**Comment by Natan515** [comment]
Can u please write it ur self at another place? I'm trying to quit mc and its really hard for me cus this is still open, so I close it and I ask u to not reopen it please.
