### ISSUE TITLE
AutoObsidian isn't compatible with the new Freecam 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1383]
Kick is at 16:42:07 [log](https://cdn.discordapp.com/attachments/757312457063530620/760860261543313428/latest-10.log)

video: https://cdn.discordapp.com/attachments/747706818314240120/760859118234894346/ice_video_20200930-164203.webm

**Comment by natan515** [comment]
Already fixed, i think...

**Comment by natan515** [comment]
Its fixed, when u use anti packet kick, and it will get a redo cus of the Highway Tools

**Comment by l1ving** [comment]
?? what
