### ISSUE TITLE
Need additional default fonts for Linux

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1388]
IPAPGothic isn't even in the AUR, I'm wondering how the hell I have it installed. 

`noto-sans-cjk` isn't installed by default on Arch either. 

Another solution is having a pop-up on startup like the updater, if fonts are missing. 

This possibly "solves" #1389

**Comment by Xiaro** [comment]
Linux 🐒

**Comment by l1ving** [comment]
The default font has been changed, resolving this issue on Arch Linux.
