### ISSUE TITLE
Font renderer uses the color black if a glyph is missing 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1389]
Example:

![](https://cdn.discordapp.com/attachments/634010851128639508/761049974439542804/unknown.png)

Tested on Arch Linux. Bug fixed after installing `noto-sans-cjk`

See #1388

**Comment by Xiaro** [comment]
It isn't missing. If would be boxes if there is no textures

**Comment by l1ving** [comment]
Apparently installing a font which supported these glyphs fixed the black text.  
![image](https://user-images.githubusercontent.com/17222512/94951946-287efc80-04b3-11eb-9b8f-ba5735d297f7.png)

**Comment by Xiaro** [comment]
This should be fixed already now. For missing font issue, go to #1388
