### ISSUE TITLE
the game cant start, baritone missing. 

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1390]
file:///C:/Users/speed/Desktop/ice_video_20201001-083551.webm

my mods are in the video too.

and that's my crash report. 
file:///C:/Users/speed/AppData/Roaming/.minecraft/crash-reports/crash-2020-10-01_08.33.51-client.txt

**Comment by GoodPro712** [comment]
LMFAO HOW IS THIS UNIRONIC

**Comment by l1ving** [comment]
Already fixed.
