### ISSUE TITLE
Changing CustomFont setting doesn't reload GUI, causing boxes to be sized incorrectly

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1398]

**Comment by Xiaro** [comment]
Old gui bug. It only updates width on loading. So just ignore it and wait for the new gui lol.

**Comment by l1ving** [comment]
It's like a 1 line fix, otherwise I wouldn't have opened lol

**Comment by l1ving** [comment]
Reopening because this affects you on every new session, not just after changing font.
