### ISSUE TITLE
Black line in chat with CustomFont disabled

### ISSUE THREAD

**Issue by NekoNoor** [kami-blue/client#1399]
**Describe the bug**
Last line of chat renders as black

**To Reproduce**
1. Join a minecraft server
2. Disable CustomFont in the clickgui
3. Look at chat

**Expected behavior**
The chat renders normally

**Screenshots**
![image](https://user-images.githubusercontent.com/14105847/94823726-77ba2400-0404-11eb-88da-8ea38570c0d3.png)

**Additional context**
This is using latest nightly

**Comment by l1ving** [comment]
What other mods are you using?

**Comment by NekoNoor** [comment]
Kami blue is the only loaded mod

**Comment by Xiaro** [comment]
GL blend shit fuk up again
