### ISSUE TITLE
baritone stack some times which make afk rly anoying.

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1401]
*Operating system: not sure what it is

*Java version: 8
*Minecraft version: 1.12.2
*Baritone version: the lastest 
*Forge mods (if used): normal forge...

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
*make so baritone wont stop lol, we cant afk like this.

the start of baritone file:///C:/Users/speed/Desktop/ice_video_20201002-141407.webm
the end of it, and how to start it back.
file:///C:/Users/speed/Desktop/ice_video_20201002-142717.webm
it stop for a sec for no resone... and it come back when i moving which make afk so anoying!!!!! i would like you to fix it have a good day.

**Comment by GoodPro712** [comment]
...

**Comment by l1ving** [comment]
This is either AntiAFK or LagNotifier working as intended
