### ISSUE TITLE
add to auto mine lapis. 

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1403]
very simple no?

**Comment by GoodPro712** [comment]
lapis is too specific, instead of adding lapis i suggest adding info telling the user how to autmine any block like ;b mine lapis_ore

**Comment by natan515** [comment]
i do know how lol, i just care about other people i rly think they need to remove this cus baritone is a thing.

**Comment by l1ving** [comment]
`;b mine lapis_ore`
