### ISSUE TITLE
Auto32k,  more good ca and auto crystal, autototem mod (crystal,  gap),  swordgap to autototem. 

### ISSUE THREAD

**Issue by xoffu** [kami-blue/client#1408]
Auto32k,  more good ca and auto crystal, autototem mod (crystal,  gap),  swordgap to autototem.

**Comment by l1ving** [comment]
> auto32k

#1025

> improve CA

use the rewrite? lol

> autototem option for crystal / gap

use autooffhand

> swordgap to autototem

no idea what this is

**Comment by Nathan-Webb** [comment]
> swordgap to autototem.

I believe this is referring to a way to switch from using a sword and gapple in your main/offhand to a sort of autototem switch. I guess if you're fighting varied enemies? Would you be able to elaborate xoffu? 🤔

**Comment by Nathan-Webb** [comment]
Also yea, leave a comment on #1335 if you want to suggest anything for xiaro to add.
