### ISSUE TITLE
Offhand ignores settings and prioritises Totems then gapples then crystals in offhand no matter what

### ISSUE THREAD

**Issue by ub3rshadow** [kami-blue/client#1417]
The autooffhand module prioritises moving totems into your offhand no matter what the settings. If you run out of totems, it will prioritise moving gapples into your offhand, and if you run out of them it'll finally put crystals into your offhand.

https://www.youtube.com/watch?v=S8aBeYDErU0 Link to demonstration

**Comment by Xiaro** [comment]
It does that already. It only moves totem into your hand if your offhand slot is empty or health is too low. If you want to overrides it manully. Use the swap hand key in Minecraft (Binded to F by default). Or replace a item with it inventory (move the item you want into the offhand slot not moving it out first)

**Comment by Xiaro** [comment]
Offhand gap only puts gapple in your offhand when you have aura or crystal aura enabled. Or you have a sword in your hand. (if you have those settings enabled)
Offhand crystal put crystal in your offhand when crystal aura is enabled.

**Comment by Xiaro** [comment]
Closed due to no further responses and this is an intentional design
