### ISSUE TITLE
bug with name tags

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1418]
when I'm at freecam and I look at myself I don't see the name tag and my armor(the thing that shows enc and durability, so u need to look up to see this even though I'm not there.
![2020-10-05_20 54 29](https://user-images.githubusercontent.com/66911017/95114901-51bab980-074d-11eb-9979-b87129da3551.png)
![2020-10-05_20 54 34](https://user-images.githubusercontent.com/66911017/95114908-52ebe680-074d-11eb-967d-cb09e3d135eb.png) 
![2020-10-05_20 54 36](https://user-images.githubusercontent.com/66911017/95114917-541d1380-074d-11eb-9d06-26debb538510.png) 
![Uploading 2020-10-05_20.54.38.png…](
ive send some of the screen shots

**Comment by l1ving** [comment]
> I don't see the name tag and my armor(the thing that shows enc and durability, so u need to look up to see this even though I'm not there.

Your screenshots show the opposite
