### ISSUE TITLE
Custom font breaks PotionUI

### ISSUE THREAD

**Issue by bensonious** [kami-blue/client#1419]
**Describe the bug**
Potion effects hud module do not show any text other than time remaining

**To Reproduce**
1. turn on potion effect hud
2. put potion effect on to self
3. See error

**Expected behavior**
to see what potion effect i am under 

**Screenshots**
![Screenshot (179)](https://user-images.githubusercontent.com/72408961/95116830-a3475200-0715-11eb-9dd4-3283a77e8206.png)

**Additional context**
none

**Comment by l1ving** [comment]
Does this work with custom font disabled?

**Comment by bensonious** [comment]
yes it does
