### ISSUE TITLE
Nametags self nametag is buggy sometimes

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1420]
now ik u removed my last thing about that but u don't get it a bug... when I'm looking at my player with freecam I see his name only not name tag the module, which is anoying. 
![2020-10-05_23 59 44](https://user-images.githubusercontent.com/66911017/95131686-2b097c80-0767-11eb-9e1d-c7fac9141625.png)
![2020-10-05_23 59 46](https://user-images.githubusercontent.com/66911017/95131687-2cd34000-0767-11eb-9f2d-e3b4e33c9b0c.png)
![2020-10-05_23 59 54](https://user-images.githubusercontent.com/66911017/95131692-2d6bd680-0767-11eb-8c98-59ca4337e66c.png)

**Comment by l1ving** [comment]
I closed your last issue because I still cannot understand what you're saying and I have no idea what the problem is here

**Comment by natan515** [comment]
Ok so i will try to explain yet again, when you have name tags on and freecam on, you look and your self and see your armor, ping, and health, just like you see any other player. this is what happens in a client like salhack, but in kami blue, you just see the name and you dont see all the normal name tags stuff like armor and health, and if you want to see them you need to look at the sky. so the problem is: the player and his name tag arent connected proparly in freecam. best explain i can...

**Comment by l1ving** [comment]
So you mean that Nametags don't display for your own player at certain angles?

**Comment by natan515** [comment]
yes, I think... hard to explain just go to a server and have armor and active name tags and freecam and ul see. have a great day.
