### ISSUE TITLE
add auto netherack, or just any block

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1422]
when ur building highways ur using auto obsidian but what if u could do it with more blocks like, that it would mine 8 stacks of netherack and keep building for highways and thous kind of stuff add more automation and make more ppl use kami blue. give option for more blocks like if u got a schamatic thta u need send for he will mind automaticly send or get it out from a shulker. could be super usfual I will be super happy if u would add it.

**Comment by GoodPro712** [comment]
low iq monkey

**Comment by natan515** [comment]
ha? ur just saying it with no explain...

**Comment by KMatias123** [comment]
tell me a block that drops 8 netherrack

**Comment by natan515** [comment]
NO, BUT it will mine it.

**Comment by GoodPro712** [comment]
please learn English before creating 20~ issues
