### ISSUE TITLE
AutoOffhand doesnt count absorption

### ISSUE THREAD

**Issue by KMatias123** [kami-blue/client#1423]
**Describe the bug**
AutoOffhand doesnt count absorption when switching back to crystal or any item

**To Reproduce**
1. turn the module on
2. take damage
3. eat a gapple
4. even tho you have more than the set amount of hearts in total it wont switch

**Expected behavior**
it should switch when you have enough absorption + normal hearts now it only switches when enough normal hearts

**Comment by l1ving** [comment]
5f769583dbd0ec9f65afdf348b3e01d06fef66ab
