### ISSUE TITLE
CrystalAura doesnt work while eating

### ISSUE THREAD

**Issue by KMatias123** [kami-blue/client#1424]
**Describe the bug**
CrystalAura doesnt place or break when the main hand is eating and the offhand has crystals

**To Reproduce**
1. turn the module on
2. put crystals in offhand and gapples in main hand
3. make sure you have an enemy in range
4. it should start attacking
5. eat, it should stop attacking

**Expected behavior**
placing and breaking should happen even if the main hand is eating

**Comment by GoodPro712** [comment]
should be a config option*

**Comment by Xiaro** [comment]
Go to Combat → Combat Setting → Page: IN_COMBAT → PauseForEatting
It is on by default because some server patches it as what @GoodPro712 mentioned.
