### ISSUE TITLE
New shader ESP is incompatible with other ESP's

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1427]
**Describe the bug**
Almost all other ESP type features stop rendering if the player enables the ESP module and select mode SHADER. Tested with StorageESP, HoleESP, SelectionHighlight and Search. For some reason CrystalESP works fine.

**To Reproduce**
1. Build KAMI Blue;
2. Enable ESP related stuff, like StorageESP and HoleESP;
3. Enable the ESP module, select mode SHADER;
4. Other ESP's stop rendering.

**Expected behavior**
Other ESP's should work fine.

**Screenshots**
No.

**Additional context**
KAMI Blue build on commit aebc76b5d27db273fe52a3b0140165e502088449.

**Comment by l1ving** [comment]
mfw people make bug reports for unreleased nightlies

**Comment by omninope** [comment]
I just build from master minutes ago. Is it incorrect do write bug reports for stuff in master?

**Comment by l1ving** [comment]
No, I was entirely joking. Thanks for the bug report, appreciate it. I'll make shader not default for now then

**Comment by omninope** [comment]
Oh, ok. I tought I did something stupid.

**Comment by l1ving** [comment]
Closed in 3e42b441c9599acd0ecd588a0c6c545b62dd0c9d
