### ISSUE TITLE
Future Dosent Like KAMI Blue

### ISSUE THREAD

**Issue by RealThisNoobCoder** [kami-blue/client#1428]
**What mod?**

Future Client (Hacks if you are stupid)
**Logs**

It closes with Error Code 0. No logs are made. I dont know why
**Additional context**

N/A

**Comment by l1ving** [comment]
You need to provide a log

**Comment by RealThisNoobCoder** [comment]
I once again say. No logs were created

**Comment by natan515** [comment]
you can find it in the .minecraft file.

**Comment by l1ving** [comment]
It's not possible for a log to not be created.

**Comment by l1ving** [comment]
Closed. Reopen with requested information.
