### ISSUE TITLE
Option to disable SelectionHighlight in Freecam

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1429]
very anoying when u go through blocks in freecam with selection highlights on, so it would be nice if there would be an option to disable.

**Comment by natan515** [comment]
Why did u close Xiaro? It hasn't been fixed.

**Comment by l1ving** [comment]
Yes it has

**Comment by natan515** [comment]
![2020-11-15_08 38 57](https://user-images.githubusercontent.com/66911017/99178653-146b2380-271e-11eb-8452-1a92a3daf96d.png)
![2020-11-15_08 38 54](https://user-images.githubusercontent.com/66911017/99178654-16cd7d80-271e-11eb-997f-ad502e2fac41.png)
Don't see any option for it.. idk

**Comment by l1ving** [comment]
Because it's in the code

**Comment by Xiaro** [comment]
No it doesn't disable it. It just have a proper check for not rendering inside of block. Disabling it is :monkey:
