### ISSUE TITLE
Portal esp

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1430]
I was really surprised to see portal esp ain't a thing and maybe just add it to esp no need to make a new module.

**Comment by l1ving** [comment]
Search module

**Comment by DisNin** [comment]
> I was really surprised to see portal esp ain't a thing and maybe just add it to esp no need to make a new module.

@natan515 just enable `search` in render category and do `;search +"name of block"` (`;search +portal`)

**Comment by natan515** [comment]
Ye ik but its still kinda anoying

**Comment by l1ving** [comment]
What??

**Comment by DisNin** [comment]
lmao, add portalesp now plsplsplsplsplsplsplsplsplsplspls

**Comment by supakeks** [comment]
literally just add it in "search", thats exactly what it does... You can have an ESP for any block of your liking with the "search" module...

;search +portal

**Comment by GoodPro712** [comment]
portal is even there by default
