### ISSUE TITLE
ESP Shader mode is incompatible with Optifine's Fast Render 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1431]
Causes a black screen

**Comment by Xiaro** [comment]
🗿 
![image](https://user-images.githubusercontent.com/62033805/95362803-9dc84400-089c-11eb-9205-7ab37ea339b9.png)

**Comment by l1ving** [comment]
Okay this is why I ask people to make bug reports themselves. User error

**Comment by Xiaro** [comment]
nvm it was a impact moment 
![image](https://user-images.githubusercontent.com/62033805/95364667-1c25e580-089f-11eb-94b3-d51e09efa116.png)

**Comment by l1ving** [comment]
Wait impact fixes it? lmfao
