### ISSUE TITLE
Rename MPS to BPS in InfoOverlay for the Speed Unit

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1442]
Self explanitory

**Comment by FluorideHistorian** [comment]
already an option

**Comment by GoodPro712** [comment]
oops, i got confused with the M, i was thinking miles lol

**Comment by l1ving** [comment]
I don't see why. It's m/s in the gui, while it's km/h for the other option. If it was miles it would be m/h

**Comment by GoodPro712** [comment]
either way, 90% of people refer to them as blocks not meters

**Comment by l1ving** [comment]
#790 would setting descriptions
