### ISSUE TITLE
Custom type of font for CustomFont

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1443]
Basically an option to make the font look like
![image](https://user-images.githubusercontent.com/45357714/95425543-2bd12700-0990-11eb-826d-eb4c403b3f6c.png)
instead of
![image](https://user-images.githubusercontent.com/45357714/95425621-473c3200-0990-11eb-94cc-2cb78e0e15fb.png)

**Comment by l1ving** [comment]
I'd rather you just be able to choose the font.
