### ISSUE TITLE
ChatFilter support boss bars 

### ISSUE THREAD

**Issue by Natan515** [kami-blue/client#1445]
people on 2b2t and other anarchy servers like to name withers and sometimes it can be extremly anoying or just rly toxic, so it would be cool to have an option to see as the name of the wither olways just wither or have something that the player can add what he call "bad words" and if the wither has it it will convert to wither or just nothing. can be usfual for youtubers when in spawn or just nice for less toxic or less text on screen.

**Comment by Xiaro** [comment]
BossStack has an option of hiding them
![image](https://user-images.githubusercontent.com/62033805/95471319-cd845400-094f-11eb-9cfe-422745986e0f.png)

**Comment by l1ving** [comment]
Just change the BossStack scale to 0?

**Comment by l1ving** [comment]
xiaro commented while I was typing :>(

**Comment by natan515** [comment]
no, but i mean like that i will see that there are withers just not there names

**Comment by natan515** [comment]
it can be useful.

**Comment by natan515** [comment]
I don't want to remove the wither just not to see the name tags, i do want to see dragons and other normal withers and name tags withers too just not there names..

**Comment by l1ving** [comment]
You mean, you want an option for the ChatFilter module to apply to boss names?

**Comment by natan515** [comment]
YES and to have an option to just olways make it normal wither

**Comment by l1ving** [comment]
Closed in 2b9fac04
