### ISSUE TITLE
the bug with baritone is yours!

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1448]
this time I got evidence! ur lagnotifiar is the one making the problems, it doesn't matter his settings or if he is on or off.

but the thing is the file is 7mb... and I can send only 10 here so pls living look at discord for the evediance.

**Comment by l1ving** [comment]
I have literally no idea what this is supposed to mean.

**Comment by natan515** [comment]
nooo, server need to be lvl 3 i don't know where i can send it to u.

**Comment by Xiaro** [comment]
Post the link here 🗿

**Comment by natan515** [comment]
i cant...
its more than 10mb

**Comment by l1ving** [comment]
Use an unlisted youtube link then

**Comment by natan515** [comment]
https://youtu.be/qb5HMNiL7Zk it will take 1 min

**Comment by natan515** [comment]
my voice there sound so weird lol.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Copy and paste the appropriate one and fill out the requested information
- [Example bug template](https://gist.githubusercontent.com/l1ving/a0e174c4338cfb043fd674ff27a0a6aa/raw/de031898596cc7e4eb82ab0cc4f3719243f4075b/bug.md)
- [Example suggestion template](https://gist.githubusercontent.com/l1ving/c19a9bf70e7faf4829b0dc0fc2e5f268/raw/7dacde4466dc9c92e5253bdab57f4aec8ff91450/suggestion.md)
- [Example question template](https://gist.githubusercontent.com/l1ving/7f383161eb4fcab96e6c1f439c26d220/raw/f59af220a8ba88fe3535e33316a8b28669d868d4/question.md)

**Comment by natan515** [comment]
done.
