### ISSUE TITLE
problem with lagnotifiar with baritone schamatic.

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1449]
a video show this, https://www.youtube.com/watch?v=qb5HMNiL7Zk&feature=youtu.be
so the thing is that when u use baritone of schmatic and it doesn't matter the lagnotifer settings doesn't matter, the baritone just decides to randomly stop doesn't matter if the lagnotifer is on or off, and if u want it to be back you need to double click, the way i live with this is an auto clicker on the lagnotifer of 1sec so i wont get stuck. very anoying problem please don't tell me its not a kami blue problem cus it is and only happens with your mod. the other way to make it work is by walking away from there a bit. pls fix and have a great day.

**Comment by l1ving** [comment]
This isn't a KAMI Blue issue. You're mistaking the fact that LagNotifier runs unpause when disabled as a "bug".

**Comment by natan515** [comment]
what? so cant u fix it??? its extremely anoying and ur the only mod that has it.

**Comment by l1ving** [comment]
No, this is a Baritone bug.

**Comment by natan515** [comment]
so how does it work when i click on it twice? and why doesn't it happen at impact?

**Comment by l1ving** [comment]
> so how does it work when i click on it twice? 

**You're mistaking the fact that LagNotifier runs unpause when disabled as a "bug".**

**Comment by natan515** [comment]
im sorry, so why when ive added this bug report to baritone u sayed it aint a bug... and again the only mod that it happens too ive did it with impact and it went great.

**Comment by l1ving** [comment]
> did it with impact and it went great.

You're doing something differently then.

**Comment by l1ving** [comment]
Make a bug report with the **template filled out**.

**Comment by natan515** [comment]
no, nothing 100 percent the same and the bug started when i started to use kami blue.
