### ISSUE TITLE
Create required (blank) files when modules are enabled

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1453]
Pretty simple to understand, create blank files for chatfilter, spammer etc for the people who don't know what type of file to create and who don't know how to create a file (lol)

**Comment by Xiaro** [comment]
Bruh that is like the basic skills of using computer

**Comment by GoodPro712** [comment]
do I need to link you to the conversations in the help channel?

**Comment by l1ving** [comment]
This should be done
