### ISSUE TITLE
InventoryPreview Border/Outline option

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1454]
self explanitory

**Comment by l1ving** [comment]
Eh I don't know how I feel about this. Take a look at the one in the new GUI and let me know if it's still worth implementing

**Comment by l1ving** [comment]
I think the one in the new GUI is quite sufficient. If you feel this should be still implemented then ask me to reopen it.

**Comment by Xiaro** [comment]
I mean it is just one line of code

**Comment by l1ving** [comment]
me underestimating how complete the new gui is be like

**Comment by Xiaro** [comment]
RenderUtils2D exists way before it
