### ISSUE TITLE
NoSlow doesn't work with AutoWalk Foward

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1455]
At it again with another kami blue bug report :)

**Comment by l1ving** [comment]
All AutoWalk forward mode does is set your motion to positive 1, so I don't know why it wouldn't work

**Comment by GoodPro712** [comment]
lmao

**Comment by Xiaro** [comment]
> All AutoWalk forward mode does is set your motion to positive 1, so I don't know why it wouldn't work

No it isn't, It just set the movenment input to 1, like baritone

**Comment by l1ving** [comment]
That's what I meant

**Comment by Xiaro** [comment]
> That's what I meant

Motion != movement input

**Comment by l1ving** [comment]
# _🗿_
