### ISSUE TITLE
AntiSpam removes me saying "nice"

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1456]
32 issues in 1 month... never done before

AntiSpam removes me saying "nice"
I can still see other people say "nice"
wtf is this bug??
config:
![image](https://user-images.githubusercontent.com/45357714/95590015-43dc9f80-0a91-11eb-9814-ea43e1aec99e.png)
![image](https://user-images.githubusercontent.com/45357714/95590048-4ccd7100-0a91-11eb-95df-d60d01f0d5f4.png)

**Comment by l1ving** [comment]
Please provide your log, it says which regex was triggered

**Comment by GoodPro712** [comment]
```[00:34:42] [Client thread/INFO] [KAMI Blue]: [AntiSpam] Duplicate: <GoodPro712> nice```
even so, shouldnt it matter because filter self is set to false?

**Comment by l1ving** [comment]
Send your entire config file I guess

**Comment by GoodPro712** [comment]
[KAMIBlueConfig.zip](https://github.com/kami-blue/client/files/5359220/KAMIBlueConfig.zip)

**Comment by l1ving** [comment]
Should be fixed.
