### ISSUE TITLE
AutoOffhand option to switch to totem when falling 

### ISSUE THREAD

**Issue by halo7761** [kami-blue/client#1458]
AutoOffhand on KamiBlue is pretty nice however i would like a few changes including changing to totems while falling >4 blocks and the ability to bind offhand gapple and offhand crystal
+ it would be helpful for offhand crystal to be activated when crystal aura is toggled

and also it would be helpful to have custom module message whenever a module is toggled on or off

if any of these have been asked of before or are already in but i missed it, very sorry for wasting ur time

**Comment by l1ving** [comment]
> ability to bind offhand gapple and offhand crystal

can already do that

**Comment by Xiaro** [comment]
> > ability to bind offhand gapple and offhand crystal
> 
> can already do that 

No

**Comment by l1ving** [comment]
Macros allow you to bind that??

**Comment by l1ving** [comment]
> have custom module message whenever a module is toggled on or off

this is also already an option in CommandConfig

**Comment by Xiaro** [comment]
> Macros allow you to bind that??

No, the option is only for allowing it to switch offhand item when player is holding weapon, or aura/ca is active

**Comment by Xiaro** [comment]
> > have custom module message whenever a module is toggled on or off
> 
> this is also already an option in CommandConfig

They meant sending a message when switching offhand item I think

**Comment by l1ving** [comment]
they said module though
