### ISSUE TITLE
ESP Rendering Bug

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1460]
![image](https://user-images.githubusercontent.com/45357714/95654325-0e948800-0b4b-11eb-9b7e-289b4319bbf9.png)
Weird ass bug with ESP. I know its ESP because it stops when I disable it. This happens seemingly randomly.

It's turning water and selection highlight rendering into this. Probably more things it glitches but that's all in the screenshot

spooky

**Comment by l1ving** [comment]
Provide the output of ;tsc please

**Comment by GoodPro712** [comment]
![image](https://user-images.githubusercontent.com/45357714/95654411-84005880-0b4b-11eb-84da-229bd0f5922b.png)
this is what it is currently. this screenshot was from 4~ hours ago though

**Comment by l1ving** [comment]
Does the issue still happen with your current setup?

**Comment by GoodPro712** [comment]
no, as ESP is off

**Comment by l1ving** [comment]
Actually you're using a version that's 2 versions outdated. This should already have been fixed, please reopen if it happens in latest (with your tsc).

**Comment by GoodPro712** [comment]
shader esp, btw
![image](https://user-images.githubusercontent.com/45357714/95654453-c6c23080-0b4b-11eb-8c45-7de76f5fc17e.png)

**Comment by GoodPro712** [comment]
alright
