### ISSUE TITLE
InventoryUtils don't count offhand

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1461]
I have a totem in my offhand
I have autolog on with totem set to 1
Randomly I get logged because I "have below 1 totem"
When I log back in there is still a totem in my offhand

**Comment by Xiaro** [comment]
https://github.com/kami-blue/client/blob/00d3e32aca3f514c36c67bab409679691492cd17/src/main/java/me/zeroeightsix/kami/util/InventoryUtils.kt#L126-L129
It does it already :thonkkill:

**Comment by Xiaro** [comment]
https://cdn.discordapp.com/attachments/634010567107149824/764516691131760660/2020-10-10_11-54-39.mp4
