### ISSUE TITLE
Crash on initialization

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1468]
**Describe the bug**
Consistent crash while loading KAMI Blue build on commit 6b88b3012de28522ae759b723b2aac6487bf33ad (latest at the time of writing) on a clean install.
Crash report: [https://pastebin.com/KuUeZmYD](https://pastebin.com/KuUeZmYD)

**To Reproduce**
1. Build KAMI Blue on commit 6b88b3012de28522ae759b723b2aac6487bf33ad;
2. Start the game;
3. Crash.

**Expected behavior**
It should not crash.

**Screenshots**
Not applicable.

**Additional context**
No.

**Comment by Tigermouthbear** [comment]
this is because CombatManager.kt is inutialized before ModuleManager::load() is called. therefore Combat manager.kt references a non-initalized field.

**Comment by Xiaro** [comment]
Already fixed in 137763e 😩

**Comment by Xiaro** [comment]
> this is because CombatManager.kt is initialized before ModuleManager::load() is called. therefore Combat manager.kt references a non-initalized field.

No, the sorted module list is init in another thread, and `getModules()` gets called by `CombatManager` before the thread is done.
