### ISSUE TITLE
Baritone that can dodge enemies, because knock back doesn't register in low tick speeds 

### ISSUE THREAD

**Issue by slickasfrick** [kami-blue/client#1470]
**Is your feature request related to a problem? Please describe.**
Yes, I was playing on constantiam and using auto mine. But my problem is that I have to keep track of  the bot because once it gets in contact with a hostile mob, it just takes the hits. I have died twice because of this problem. Both times is because the bot would just stand right next to a creeper and not even try to get away.

**Describe the solution you'd like**
I barely know any thing about coding and stuff, and not sure if this is too advanced or doesn't work. But maybe some thing to avoid hostile mobs, or players. Like backing up every time something gets closer. 

**Describe alternatives you've considered**
I have tried using killaura while using baritone, but it just messes up the baritone. And like I said in the title, knock back doesn't register in low tps I'm pretty sure and once the mobs get close enough to hit you, your just done for.

**Additional context**

**Comment by l1ving** [comment]
> but it just messes up the baritone.

Aura intentionally pauses Baritone, it's optional. 

1. This is the KAMI Blue repo, not the [Baritone](https://github.com/cabaletta/baritone) repo
2. Baritone has an [avoidance](https://baritone.leijurv.com/baritone/api/Settings.html#avoidance) setting and a [mobAvoidanceCoefficient](https://baritone.leijurv.com/baritone/api/Settings.html#mobAvoidanceCoefficient) setting
