### ISSUE TITLE
MC Crash

### ISSUE THREAD

**Issue by zihasz** [kami-blue/client#1471]
**Describe the bug**

When I launch Minecraft with only KAMI Blue in my mods folder it crashes.

**To Reproduce**

1. Put KAMI Blue in the mods folder
2. Delete configs and latest config
3. Start Minecraft
4. Crash

**Expected behaviour**

Minecraft launches fine

**Screenshots**

N/A

**Additional context**

Logs:
https://pastebin.com/kQ3FuGCT

**Comment by l1ving** [comment]
You're using v1.1.6, which is nearly 350 updates old and unsupported.

**Comment by zihasz** [comment]
> 
> 
> You're using v1.1.6, which is nearly 350 updates old and unsupported.

same with 1.1.7 latest

**Comment by l1ving** [comment]
I need your new log then.
