### ISSUE TITLE
Commit 3e42b44 breaks fullscreen on specific Windows systems 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1474]
Diff: https://github.com/kami-blue/client/commit/3e42b44

Reproduce: open Minecraft, try fullscreening. Game hangs 

Tested on:

Windows 10, Integrated Intel Graphics, no other mods, latest forge.

This is pretty system specific, only one person has reported it. I can't reproduce this myself, they can consistently reproduce it on d22c947 and above.

**Comment by slashsynapse** [comment]
this problem is simmilar to mine

**Comment by slashsynapse** [comment]
o wait it is mine
