### ISSUE TITLE
disable firework rendering

### ISSUE THREAD

**Issue by bensonious** [kami-blue/client#1480]
**What mod?**
the mod is called "disablefireworkrendering-1.0-full.jar, it makes it so fireworks don't get rendered since on 9b9t you can crash people with fireworks, this mod prevents this

**Logs**
[latest.log](https://github.com/kami-blue/client/files/5401871/latest.log)

**Additional context**
not really, but something else that might solve this is adding a firework option within norender, using gentity works but it makes everything else not render so if an option for just fireworks was to be added will also solve this problem

**Comment by humboldt123** [comment]
Sure. I'll get started on this.

**Comment by l1ving** [comment]
Why was this labelled "incompatible"?

**Comment by bensonious** [comment]
because the disablefirworkrendering mod doesnt work with kami blue, the part about norender is just a sugguestion

**Comment by l1ving** [comment]
Whatever. Already added.
