### ISSUE TITLE
Extreme lag when close to a ender dragon if CombatSetting is targeting hostile mobs

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1485]
**Describe the bug**
If the CombatSetting module is targeting hostile mobs and the player approaches an ender dragon the CPU usage goes to 100% on all the cores on my PC and the FPS drops to 0.
Tested with some other mobs and only the ender dragon caused this problem.
Tested only in Singleplayer and a local server, no "proper" servers.

**To Reproduce**
1. Build KAMI Blue on commit b445c96746369d07e1f950234bcc54e43de54e1e;
2. Go to the end or summon a dragon with `/summon minecraft:ender_dragon ~ ~ ~ {NoAI:1b}` (easier). Make sure the dragon is close to the ground it doesn't seem to work reliably while in the air;
3. Under CombatSetting enable HostileMobs as a target;
4. FPS goes straight to 0.

**Expected behavior**
A little lag is expected because of the hardware I use, but not that much.

**Screenshots**
No.

**Additional context**
No.

**Comment by l1ving** [comment]
I never expected anybody to fight an Ender Dragon with KAMI Blue...

**Comment by omninope** [comment]
You never killed an ender dragon on an anarchy server? This is not uncommon.
Also I don't think people will be disabling CombatSettings options just to fight a dragon while they can literally use CrystalAura on the dragon to kill super quickly.

**Comment by l1ving** [comment]
Oops. This should be fixed, testing

**Comment by l1ving** [comment]
![image](https://user-images.githubusercontent.com/17222512/96532941-e7c90680-125a-11eb-9754-8c89d792cd2f.png)

**Comment by l1ving** [comment]
Thanks Mojang

**Comment by l1ving** [comment]
![image](https://user-images.githubusercontent.com/17222512/96533371-d2081100-125b-11eb-97a3-60db13dd0526.png)
I don't even wanna know how tf this happens

**Comment by slashsynapse** [comment]
lmao we hav to expecc the un expecc
