### ISSUE TITLE
Strange Chams ThroughWall behavior

### ISSUE THREAD

**Issue by Nathan-Webb** [kami-blue/client#1489]
**Describe the bug**
The `ThroughWall` setting in chams makes the hand models splay down and to the left. No clue why. This happens even when no chams settings are enabled.

**To Reproduce**

1. Enable Chams
2. Toggle between ThroughWall enabled and disabled.
3. See behavior

**Expected behavior**
The hand models should not change position or size

**Screenshots**
Video https://imgur.com/a/Uq6UvwT

**Additional context**
Might be impact messing things up again 🐒

**Comment by l1ving** [comment]
> This happens even when no chams settings are enabled.
![image](https://user-images.githubusercontent.com/17222512/96626375-6cf4ff80-12dd-11eb-9027-dbe000266612.png)
