### ISSUE TITLE
norender selection

### ISSUE THREAD

**Issue by bensonious** [kami-blue/client#1492]
**Is your feature request related to a problem? Please describe.**
not really a problem, just I feel like norender could be more customizable

**Describe the solution you'd like**
I think a decent enhancement to the norender would be being able to choose what is rendered or not using for example the command ";norender +entity", so basically make it like the reverse of search, where instead of highlighting blocks, its does norenderon certain entities
**Describe alternatives you've considered**
not really, no clients that I know of have a feature like this in this version of Minecraft

**Additional context**
nope nothing else

**Comment by l1ving** [comment]
Won't fix. Feel free to reopen when #1283 is added.
