### ISSUE TITLE
Non-CustomFont text is "blurry" in certain situations

### ISSUE THREAD

**Issue by bensonious** [kami-blue/client#1493]
**Describe the bug**
everything that uses vanilla font is really blurry, when using a resource pack with different font it is not blurry 

**To Reproduce**

1. no steps just that chat, gui, etc text is blurry

**Expected behavior**
text to be normal vanilla
**Screenshots**
![Screenshot (236)](https://user-images.githubusercontent.com/72408961/96740711-15af6780-138f-11eb-957e-99f0b7278617.png)
everything that has custom font is not affected, seems like only vanilla text is affected

**Additional context**
nope

**Comment by l1ving** [comment]
I need the exact version number you're using and a screenshot of the issue

**Comment by bensonious** [comment]
v1.1.7-af060a56 and screenshot is posted in post i think

**Comment by l1ving** [comment]
my internet didn't load the ss earlier. thanks.

**Comment by Xiaro** [comment]
Might be fixed in 453b97b, need some testing

**Comment by l1ving** [comment]
Tested, appears fixed by 453b97b5a4503fadcd4a96faf724b0ad7d5e2ba7.
