### ISSUE TITLE
Optifine = Opengl error 1281 with tracers

### ISSUE THREAD

**Issue by bensonious** [kami-blue/client#1494]
**Describe the bug**
I get a opengl error "opengl error: 1281 (invalid value)"

**To Reproduce**
1. turn/have on tracers
2. See error

**Expected behavior**
having tracers without errors every few seconds

**Screenshots**
![Screenshot (240)](https://user-images.githubusercontent.com/72408961/96801524-c9d3e100-13d5-11eb-99df-ff4701986b03.png)

**Additional context**
nope

**Comment by Xiaro** [comment]
Did you set your line thickness to 0?

**Comment by bensonious** [comment]
yep

**Comment by l1ving** [comment]
Why tho

**Comment by bensonious** [comment]
wym why?

**Comment by l1ving** [comment]
Why would you want a 0 wide tracer?

**Comment by bensonious** [comment]
well its the thinest and i prefere thinner tracers

**Comment by l1ving** [comment]
I'm pretty sure it's 0 as in 0 pixels but idk man

**Comment by l1ving** [comment]
Use 0.5

**Comment by bensonious** [comment]
aight, when it is at zero i see tracers so idk, will set to 0.5

**Comment by bensonious** [comment]
wouldnt it be better to not make zero a option then?

**Comment by l1ving** [comment]
Yes.

**Comment by bensonious** [comment]
I guess the way to fix this "bug" would be just to remove the option to go down to zero since i don't get the error when I bump up the thickness from zero, i guess make the lowest 0.25 since thats the lowest from 0

**Comment by Xiaro** [comment]
Old setting system moment 🗿
