### ISSUE TITLE
Option to disable and enable armor of ur self and other in freecam.

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1495]
**Describe the solution you'd like**
it can be nice to have 2 options: 1 to have that you won't see your own armor in freecam and 2 to not see the armor of other people on freecam, and maybe one for mobs armor.
it is useful for seeing ur self in a better way but still want to know how good of armor you got or your friends have. if it would add I will use it. have a great day.

**Comment by l1ving** [comment]
I wonder what the ArmorHide module does

**Comment by natan515** [comment]
I know this, this is why I asked spasificly for freecam and I explain why it's different in freecam."t is useful for seeing urself in a better way but still want to know how good of armor you got or your friends have. "

**Comment by l1ving** [comment]
So enable the self option?

**Comment by natan515** [comment]
No, I mean that you would be able to see yourself in freecam with no armor but if ur at f5 or something like that u would see it. and if u look at ur friends u see their armor but with freecam, u don't.

**Comment by l1ving** [comment]
I don't understand why this would be useful as opposed to the self option.

**Comment by natan515** [comment]
if you want to see a big group of people maybe even film it but you still want to see people armor on pvp, it can be nice not to disable and unable all time.

**Comment by l1ving** [comment]
You're still enabling / disabling something though...

**Comment by natan515** [comment]
but u don't need to change it, it's easier to use.

**Comment by l1ving** [comment]
It would actually be harder to use because instead of toggling an option you're toggling an unrelated module

**Comment by natan515** [comment]
I actually think it would be easier but I do get that it's not very important. have a good day and sorry for wasting your time.
