### ISSUE TITLE
myn and other people carectors don't show up or buggy at freecam and normal.

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1503]
**Describe the bug**
when I go on freecam with tracer opens and some more modules I see my player realy like some time and most of the time I see just the trace and not the player and the same with other players, and sometimes even when I'm not at freecam.

**Expected behavior**
when i got on freecam and normal i will see people normaly.. like vanila or other clients.

**Screenshots**

![2020-10-23_22 09 43](https://user-images.githubusercontent.com/66911017/97045291-2d990e00-157e-11eb-9177-225463c21235.png)

**Additional context**
it wasent like that before i first saw it a few weeks ago. 
have a great day! (;

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by natan515** [comment]
I actually did but I didn't found, I'm sorry.

**Comment by l1ving** [comment]
#1434
