### ISSUE TITLE
add to extra chat history an option of infinit like in badlion(not the hack)

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1504]
**Is your feature request related to a problem? Please describe.**
nop

**Describe the solution you'd like**
adding infinite chat so you can see all the chat you had since you logged in to minecraft.

**Describe alternatives you've considered**
add infinit chat that will show all chat since u join this paticaly server or singlayer player world.

**Additional context**
have a good day, rly hope not duplicate cus ive cheeked.

**Comment by l1ving** [comment]
This is already added.

**Comment by natan515** [comment]
![2020-10-23_22 27 00](https://user-images.githubusercontent.com/66911017/97045979-5b328700-157f-11eb-9b7e-133a2ba65386.png)

**Comment by natan515** [comment]
where?

**Comment by l1ving** [comment]
There's a max of 5000 for a reason. Any more will eat up your RAM.
