### ISSUE TITLE
New features for NoRender 

### ISSUE THREAD

**Issue by FriedrichM** [kami-blue/client#1508]
I am making this issue to collect suggestions for new NoRender options
If you think something has the potential to lag your client leave a comment and maybe we can add it to the list 

- [x] Mobs
- [x] GEntity (better name needed) now Lightning
- [x] Object (better name needed) now Projectiles etc
- [x] Items
- [x] XP
- [x] Paintings
- [x] Fire
- [x] Explosions
- [x] BeaconBeams
- [x] SkyLightUpdates
- [x] Particles
- [x] EnchantingTableBooks
- [x] EnchantingTables as Snowlayers (needs improvements)
- [x] SignText
- [x] Signs  
- [x] Banners
- [x] Endportal/gatewaye
- [x] Heads
- [x] Falling Blocks
- [x] ArmorStand
- [x] ItemFrames
- [x] Players 
- [x] Maps

**Comment by Nathan-Webb** [comment]
heads big yes

**Comment by FriedrichM** [comment]
There are basically 3 ways to handle entities :
1. canceling all packets that spawn them 
- this way has the advantage that the client does nothing with the entity it is as if it was not there
- entities whose spawn packets have been ignored will not reappear if you turn norender back off until you walk away and back to reload the chunk properly
- entities that are already loaded wont disappear

2. Blocking all render calls for them
- this way has the Advantage that the entities disappear and reappear when the option is toggled without the need of reloading a chunk 
- entities are still maintained by the game this uses some computational power 

3. a combination of 1 and 2
 
i would like to give the player  option 2 and 3.
If a player walks into an area that lags his game they want to "remove" the lagsource without having to reload the chunks.
My idea is to have an option that lets you decide if only the packets should be ignored or if only the rendering should be canceled or both.

Is my idea ok or do you want to change something ?

**Comment by l1ving** [comment]
An option to decide between something such as "Cancel" or "Hide" would be nice

**Comment by FriedrichM** [comment]
sounds fine now i need to see what packets create what entity the documentation is very vague about that

**Comment by l1ving** [comment]
... documentation? :p

**Comment by FriedrichM** [comment]
im matching up these https://wiki.vg/Protocol#Spawn_Entity and the few below against the forge packets

**Comment by spide-r** [comment]
Maybe have an entity setting that will trip the NoRender module? Maybe have a hard cap of 1000/configurable amt of entities, anything more than that and the module activates for the rest of the entities that still need to be loaded in.

**Comment by bensonious** [comment]
fireworks as an entity, I opened an issue with this #1480 and, after going back to spawn on 9b, it fixed a different problem, i found out it was fireworks as an entity that caused lag/crash, so consider adding this
![Screenshot (66)](https://user-images.githubusercontent.com/72408961/98378697-5efce980-2014-11eb-98ec-fe62d459f111.png)

**Comment by FriedrichM** [comment]
The ProjectilesEtc option in PR #1531 already cancles all rocketspawning packets. if there is a need for an only fireworks option let me know.

**Comment by bensonious** [comment]
what do the projectiles include, I'm guessing arrows, pearls, etc can you give me a list of whats included in that list?

**Comment by FriedrichM** [comment]
- FishHook
- TippedArrow
- SpectralArrow
- Snowball
- EnderPearl
- EnderEye
- FireworkRocket
- LargeFireball
- DragonFireball
- SmallFireball
- WitherSkull
- ShulkerBullet
- Egg
- EvokerFangs
- Potion
- ExpBottle
- TNTPrimed
- AreaEffectCloud
- LeashKnot
- Boat
- Minecart

Boats Minecarts also fall under the new ProjectilesEtc option i think we could make a separate option for those if needed (let me know) also if you want any of the above to be toggleable separately let me know too

**Comment by bensonious** [comment]
I think personally, that the ones that can be spammeed with fastplace/fastuse (eggs, fireworks, snowballs, etc) should be a separate option

**Comment by l1ving** [comment]
When proper List settings are implemented I'll make modules with lots of options such as this just be a List

**Comment by bensonious** [comment]
Aight
