### ISSUE TITLE
New Messaging system prevents impact from viewing and/or cancelling message.

### ISSUE THREAD

**Issue by Nathan-Webb** [kami-blue/client#1511]
**Describe the bug**
Whenever I use any `.command` with impact, the result is sent to the chat instead of blocked and read by impact
**To Reproduce**
1. Install impact and kami in the latest version
2. Go into a world and type `.help`
3. See that the message has been sent into the chat instead of being blocked by impact.

**Expected behavior**
The message should not be sent to the chat when using another client prefix.

**Screenshots**
![qXKTLlu5ok](https://user-images.githubusercontent.com/29214314/97115432-b1f5a900-16c4-11eb-8d14-b6e40707661a.gif)

**Additional context**
I leaked some shit in another server because of this and im angy. 😡

**Comment by l1ving** [comment]
You have your KAMI prefix set to `.`???

**Comment by Nathan-Webb** [comment]
no, my kami prefix is ;
my impact prefix is .

**Comment by l1ving** [comment]
wtf

**Comment by l1ving** [comment]
Oh someone probably changed the prefix window check to use all possible prefixes instead of active one

**Comment by Nathan-Webb** [comment]
tfw

**Comment by Xiaro** [comment]
Need to lower the priority of it I guess
