### ISSUE TITLE
DiscordNotifs Doesn't work due to removed library

### ISSUE THREAD

**Issue by Nathan-Webb** [kami-blue/client#1516]
**Describe the bug**
Error when setting up discordnotifs - NoClassDefFound

**To Reproduce**
1. Set Discordnotifs Webhook
2. Enable module
3. see errors in log

**Expected behavior**
The module should send the chat to the webhook.

**Screenshots**
![image](https://user-images.githubusercontent.com/29214314/97220413-6f51d080-1799-11eb-8bc0-0b7ebfb0bd93.png)

**Additional context**
mfw someone was too eager in slimming down the jar

**Comment by l1ving** [comment]
https://github.com/kami-blue/client/commit/59381df7e90b61a55da952ca7d0421838fc1997d
