### ISSUE TITLE
Chams module causes white screen when enabled

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1517]
**Describe the bug**
Similar in behavior to the issue that happens with ESP on SHADER mode, (and will be fixed by #1499) the Chams module causes a completly white screen when enabled on a non-resized screen. Possibly hardware an OS dependant but I did not test that.

**To Reproduce**
1. Build KAMI Blue on commit 3f1216d669940be78dfc8aa33c53b1eb3617dde3;
2. Load the game but don't resize the screen after it finishes loading;
3. Enable Chams;
4. Screen turns white;
5. Resize screen in any way;
6. Everyting works perfectly again for that session.

**Expected behavior**
Chams should work and not break all rendering.

**Screenshots**
I don't think it is necessary to screenshot a completly white screen.

**Additional context**
In case it is hardware an OS dependant:
- Graphics card: Nvidia GTX1050
- Operating System: Debian

**Comment by l1ving** [comment]
Resizing creates framebuffers. I think all Chams has to do to fix this is create framebuffers
