### ISSUE TITLE
Strange movement behavior when NoFall is enabled

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1519]
**Describe the bug**
When enabled, the module NoFall causes some weird behavior to the player movement:
- Jumping becomes extremely strange, feels like a fast fall is enabled;
- Going down a block or more fells like using DownStep on PACKET mode.

**To Reproduce**
1. Build KAMI Blue on commit 3f1216d669940be78dfc8aa33c53b1eb3617dde3;
2. In game enable NoFall;
3. Try to jump and see the first problem described above;
4. Try to go down a block and see the second problem described above.

**Expected behavior**
It just prevents fall damage.

**Screenshots**
Not applicable.

**Additional context**
Tested on single and multiplayer, KAMI Blue was the only mod active and NoFall the only module active.

**Comment by l1ving** [comment]
Send a screenshot of your NoFall settings, also do you have AntiHunger enabled?

**Comment by omninope** [comment]
> Send a screenshot of your NoFall settings

They are default.
![2020-10-26_22 50 52](https://user-images.githubusercontent.com/69328977/97247141-f5e8cb00-17f6-11eb-8cde-faaf0230cf3a.png)

> do you have AntiHunger enabled?

No. As I said in the original issue NoFall is the only module active.

**Comment by l1ving** [comment]
That's motion. What server? Try TP

**Comment by omninope** [comment]
Tested on singleplayer and the servers 9b9t.com and Oldfag.org.
The TP mode prevents fall damage on singleplayer and does nothing on the servers described, but I don't know what it's supposed to do in the first place.

**Comment by l1ving** [comment]
Well what it's  supposed to do is trip a fly check to get you teleported back to where you were before you fell. I don't understand why motion does that on that server, motion basically tells the game you're going at mach 10 upwards

**Comment by Ihackedsctrach** [comment]
9b no fall doesn’t work from what I’ve played

**Comment by l1ving** [comment]
That depends on the mode. I tested both motion and tp on 9b when I wrote it.

**Comment by Ihackedsctrach** [comment]
ah then try packet or something since sometimes or usually its just settings

**Comment by l1ving** [comment]
Packet will not cause this issue, but I don't think it will work on 9b either.
