### ISSUE TITLE
Make the AutoTrap selftrap mode a different module called SelfTrap

### ISSUE THREAD

**Issue by KMatias123** [kami-blue/client#1528]
**Is your feature request related to a problem? Please describe.**
i dont want to press 3 buttons every time i want to place a block on my head

**Describe the solution you'd like**
make the modules separate like in salhack

**Comment by l1ving** [comment]
I don't understand why this would be useful

**Comment by KMatias123** [comment]
instead of 3 button presses its 1?
also i know when its on

**Comment by l1ving** [comment]
it's already 1?

**Comment by KMatias123** [comment]
no? if you want to use both autotrap and selftrap

**Comment by l1ving** [comment]
There's a bind for selftrap in the module

**Comment by KMatias123** [comment]
it doesnt selftrap just by pressing the bind in the module, you need to have the module on

**Comment by l1ving** [comment]
Okay but you can change that...
