### ISSUE TITLE
GUI for certain modules

### ISSUE THREAD

**Issue by Doogie13** [kami-blue/client#1538]
**Is your feature request related to a problem? Please describe.**

It's annoying having to type out commands for search and a way to set up macros easier would be nice. 

**Describe the solution you'd like**

In the pause menu a "kami-blue" option (like impacts) that would bring up menus to add/remove blocks to x-ray and make chains of commands for macros easier to write.

**Describe alternatives you've considered**

impact client search, xray, macro systems

**Additional context**

idk if this is part of #1510

**Comment by l1ving** [comment]
#790
