### ISSUE TITLE
add message when module is toggled over a keybind

### ISSUE THREAD

**Issue by recursivetree** [kami-blue/client#1541]
I never know if a module controlled over a keybind is now toggled on or off. I wish there would be a message with the new state when you toggle a keybind.

**Comment by recursivetree** [comment]
I could code it myself and write a pull request

**Comment by recursivetree** [comment]
Sorry, didn't find the option in the commandConfig module, it's well hidden

**Comment by l1ving** [comment]
It'll be a proper gui setting in the future
