### ISSUE TITLE
Massive Thread overload which hangs the client.

### ISSUE THREAD

**Issue by spide-r** [kami-blue/client#1555]
**Describe the bug**
Every so often, semi-regularly, my game hangs and crashes. Sometimes it just hangs for a little while before resuming, but it's not always predictable.

**To Reproduce**
I honestly have no idea how this would be reproduced.  I'm usually using stashfinder, elytrafly control mode, search, and storageESP when this happens.

**Expected behavior**
No thread hanging.

**Screenshots**
![image](https://user-images.githubusercontent.com/29214314/98267592-2d6f1a00-1f51-11eb-9d79-bb0225e1a10e.png)

**Additional context**
 I can't really do ;tsc in the moment as my game hangs. Is there a way to profile my game to see where the threads are coming from?

**Comment by spide-r** [comment]
One thing that might be affecting it would be this line? When the thread is removed from the list, does it get garbage collected once it finishes running or does it just wait idly? 
https://github.com/kami-blue/client/blob/c5d44ecb32570622c8e4b52e66bb457355ccc293/src/main/java/me/zeroeightsix/kami/module/modules/render/Search.kt#L151

**Comment by spide-r** [comment]
![image](https://user-images.githubusercontent.com/29214314/98268989-cbafaf80-1f52-11eb-8542-6be5906b0fc6.png)
here is ;tsc before any of the stuff happens

**Comment by Xiaro** [comment]
That's is what `CachedThreadPool` does. It holds the finished Threads so they can be rerun quickly. They will get terminated after 60 seconds if not being used anymore

**Comment by Xiaro** [comment]
And I need the specific exception that threw instead of just a screenshot of bunch of threads to know where it went wrong

**Comment by spide-r** [comment]
The thing is, that is the only error message that pops up, everything else is just normal debug stuff like baritone saving and such.

**Comment by spide-r** [comment]
Similar hanging, this time with a log.
https://hastebin.com/zasifuqavo.md

**Comment by spide-r** [comment]
I understand that journeymap is erroring above. however, I am not entirely sure if its my configuration, an issue with journeymap, an issue with the two mods interacting, or a kami-specific issue. If you aren't able to help with this because you know its a journeymap issue, would you at least be able to point me in the proper direction to figure out where exactly these threads are coming from?

**Comment by spide-r** [comment]
More errors, this time with search being the culprit. https://hastebin.com/siyowegicu.sql

**Comment by l1ving** [comment]
I haven't had anybody else reproduce this at all, not even myself. Can you reproduce this with no mods?

**Comment by spide-r** [comment]
I'll try and reproduce this with no mods soon
