### ISSUE TITLE
AutoReply spams responses

### ISSUE THREAD

**Issue by spide-r** [kami-blue/client#1560]
**Describe the bug**
When a private message is received, the response is spammed back.

**To Reproduce**
1. Turn on autoreply.
2. Have someone send a message.
3. See that the messages start spamming back.

**Expected behavior**
No Spam

**Screenshots**
![image](https://user-images.githubusercontent.com/29214314/98332784-f2a6c980-1fc4-11eb-9cfe-2b208d216fec.png)

**Comment by l1ving** [comment]
lol my bad

**Comment by l1ving** [comment]
easy fix

**Comment by Xiaro** [comment]
2 day later 🗿

**Comment by notperry1** [comment]
> 2 day later 🗿

6 day later

**Comment by l1ving** [comment]
okay watch I'll fix this right now it'll literally take 2 minutes + the time to open intellij

**Comment by notperry1** [comment]
> okay watch I'll fix this right now it'll literally take 2 minutes + the time to open intellij

lmao

**Comment by notperry1** [comment]
> okay watch I'll fix this right now it'll literally take 2 minutes + the time to open intellij

v1.1.7 milestone close ngl only 5 issues open
