### ISSUE TITLE
Essential Combat Module Indicator

### ISSUE THREAD

**Issue by Bluestacker** [kami-blue/client#1562]
Is your feature request related to a problem?
Yes
<!-- A clear and concise description of what the problem is. 
its so frustrating when i cant see if my essential modules are ON or not, also i dont even notice if i toggle one by accident, and yes, i have module list on.

i may be blind, but im pretty sure im not the only one who has this issue.

**Describe the solution you'd like**
Add essentials module Indicator/List, how it would work?
CA: ON (CristalAura)
A: OFF (Aura)
S: ON (Surround)
The ON and OFF should be included
Or better make it customizable so we can put any module we think its essential for combat/pvp

**Describe alternatives you've considered**
0

**Additional context**
Yes i know one or some mods have this same feature, but i think its so useful, and kami blue could do it unique by making it customizable or something.

**Comment by l1ving** [comment]
Fill out the issue template properly.
