### ISSUE TITLE
ActiveModules -> ModuleList and indicators option 

### ISSUE THREAD

**Issue by Bluestacker** [kami-blue/client#1563]
**Is your feature request related to a problem? Please describe.**
yes

**Describe the solution you'd like**
The new feature would look like this:

This is an example, its like a module list but this indicates if its ON or not, is very useful for pvp, sometimes i dont even notice because of the large normal module list

**Additional context**
I know this feature is not original, but this is so useful, also it could be customizable so we put the modules we want but thats optional!

**Comment by l1ving** [comment]
> also it could be customizable so we put the modules we want but thats optional!

Closing this as invalid, you can already do this.

**Comment by l1ving** [comment]
Edited.

**Comment by l1ving** [comment]
There is a visibility setting in the new gui
