### ISSUE TITLE
CrystalAura scuffed on high ping

### ISSUE THREAD

**Issue by Bluestacker** [kami-blue/client#1567]
**Describe the bug**
When you have like 190-200-210 ping the CrystalAura still works, the problem comes when it tries to explode, you can hear the hand punching the crystals but nothing

**To Reproduce**
1. Use offhand crystal
2. Have like 190 - 200 ping
3. Use default ca settings

**Expected behavior**
The crystals should explode

**Screenshots**
-

**Additional context**
They do explode if i just hit them manually even if my ca is on, it takes me 1 click

**Comment by l1ving** [comment]
I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.

**Comment by Bluestacker** [comment]
well im using the latest nightly release 1.1.7, i tested others clients ca and they do the same thing but they "resolve" it faster and they explode like 300 ms after i place the crystals, while kami blue is stuck spamming, also i think it has something to do with ticks (not sure). hope this helps, sorry for not adding more info

**Comment by l1ving** [comment]
Send a video I guess

**Comment by Xiaro** [comment]
https://cdn.discordapp.com/attachments/634010567107149824/775440901203951616/2020-11-09_14-24-18.mp4

**Comment by l1ving** [comment]
> @living yo i use a laptop rn and my minecraft goes like 5 fps if i use obs cant even pvp so you can close the issue if you want, sorry

Can't reproduce this issue either.
