### ISSUE TITLE
Autowalk resume after disconnect 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1570]
Created by: Goodpro712 `(550907912281915412)`

The ability to keep autowalk (note: i will not be referring to the baritone autowalk here) enabled even after disconnect, as someone may want to afk and they could get disconnected, but with autoreconnect and this module still on it can be full afk.

**Comment by l1ving** [comment]
Note: I already tried to do this in the past and Baritone doesn't like it. There's already a queueing system planned (#792) with should have resume functionality as well. See this issue in Baritone for the suggestion there: https://github.com/cabaletta/baritone/issues/1007

**Comment by Xiaro** [comment]
Bruh just don't disable it and set the goal if not pathing

**Comment by natan515** [comment]
It would still disable at a disconnect, its a problem with schematic too.

**Comment by l1ving** [comment]
Baritone doesn't cancel the goal properly when you disconnect, it sets it to null and running resume threw an NPE when I tested

**Comment by Xiaro** [comment]
Just set a new goal and path bruh

**Comment by l1ving** [comment]
the point is for afk

**Comment by Xiaro** [comment]
> the point is for afk

SafeTickEvent
