### ISSUE TITLE
Color change range for Tracers module

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1578]
**Is your feature request related to a problem? Please describe.**
Not a problem, this is a suggestion.

**Describe the solution you'd like**
An option to customize the range color change in the Tracers module separated from the actual render range of the tracers, so the user can still see tracers for far away players and only when said players enter a specific range, set by the user, the tracer color starts to change, indicating they are close.

**Describe alternatives you've considered**
There is none.

**Additional context**
No.

**Comment by l1ving** [comment]
This is blocked by #790

**Comment by Xiaro** [comment]
No, just need an extra option

**Comment by l1ving** [comment]
Two different colors in the current GUI will be a mess, I'd rather wait

**Comment by omninope** [comment]
The 2 colors for far and close already exist, I'm just talking about the range option.

**Comment by Xiaro** [comment]
The color setting already exist, they only want options to change when the color start changing

**Comment by l1ving** [comment]
Oh
