### ISSUE TITLE
Autodupe feature

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1581]
Created by: Knifeduck `(538572059630895105)`

How it works, Two people who have Kami blue get near each other, then you port sync the two clients together I.e something like ;connect 1337. But anyways you have to set up a lot of rails and minecarts, it is a working donkey dupe essentially,now the steps that I have seen from youtube.
1. one of the players pushes the donkeys to the direction of the track
2. the player who logs goes to the end of the track
3. the player who logs enables packet canceller and freecam and starts going thru the track thru minecarts, then mounts the  donkey without chest once is back
4. second player pushes the button that pushes donkeys back and goes to the end of the track
5.  second player reloads chunks at the end of the track and waits 10 seconds, then comes back
6. once hes back only one donkey (the one with chest) should be in the boat, first player gone too
7. when the second player is back, first player logs and once he logs the second player kills the donkey
8. then first player reconnects
9. profit
The rails have to be spaced 4 apart, so you can go six chunks away in a fraction of a second by clicking them.
https://www.youtube.com/watch?v=yi8SWMzk-og This video was extremely beneficial in explaining how it works in full detail, I think it could help you out if you ever attempt to make this. If you added this to Kami Blue you would definitely be ahead of the game. It will definetly better the client, and bring more users to use Kami blue, as it will become The best client (IMO). It would be a shame not to see this magnificent piece of enginerical coding in this client.

**Comment by l1ving** [comment]
Won't fix, patched now

**Comment by natan515** [comment]
It works on servers that aren't 2b2t people still need it, I think it is better to put it on low priority.
