### ISSUE TITLE
Baritone fast goto module

### ISSUE THREAD

**Issue by Doogie13** [kami-blue/client#1586]
**Is your feature request related to a problem? Please describe.**

No, just lazy
**Describe the solution you'd like**

A version of freecam that when you click, it ;goto your freecam location.
**Describe alternatives you've considered**

Freecamming and ;goto what the coords I freecam to are
**Additional context**

For moving around to somewhere in render distance quickly.

**Comment by l1ving** [comment]
`;b come`?

**Comment by Xiaro** [comment]
#come,  #click
Clicking in Freecam already used for interacting with blocks and entity

**Comment by Doogie13** [comment]
> `;b come`?

Is that where you click on a block and it goes to it? If that works in freecam close this.

**Comment by l1ving** [comment]
That will go to where your freecam player is. 

Also specifically clicking to go somewhere is already suggested in ImpactDevelopment/ImpactIssues#912 and #1160.

**Comment by Xiaro** [comment]
> That will go to where your freecam player is. 
> 
> Also specifically clicking to go somewhere is already suggested in ImpactDevelopment/ImpactIssues#912 and #1160. 

Isn't that just #click?

**Comment by l1ving** [comment]
Yea, #click should be able to do that actually. #1160 is multiple suggestions though, so don't close it
