### ISSUE TITLE
AutoArmor works weirdly

### ISSUE THREAD

**Issue by KMatias123** [kami-blue/client#1588]
**Describe the bug**
When im on a server and turn it on it makes the items disappear and when i toggle it off and click the inv slots they come back, I think its ncp trying to make me not use utility mods

**To Reproduce**

1. log on 2b2tpvp
2. use a kit
3. throw armor away and then turn autoarmor on
4. items glitch

**Expected behavior**
they go to the armor slots

**Comment by l1ving** [comment]
Do you have XCarry enabled?

**Comment by KMatias123** [comment]
i have future xcarry enabled

**Comment by KMatias123** [comment]
happens without it enabled too

**Comment by l1ving** [comment]
restart your game without it enabled and see what happens

**Comment by l1ving** [comment]
make sure it's not enabled in either mod

**Comment by KMatias123** [comment]
it still doesnt work with xcarries disabled and game restarted

**Comment by l1ving** [comment]
I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.
