### ISSUE TITLE
Strange Chams rendering

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1591]
**Describe the bug**

This is better demonstrated as an image. From left to right:
1. The mushrooms on top of a mooshroom render as solid white squares disrespecting the normal rendering size of said structures and in disregard of the different custom color and transparency, the same thing happens when no custom color is selected;
2. The hopper on a hopper minecart render as a solid white color despite the different custom color and transparency;
3. ~~Items render as a solid white squares disrespecting the normal rendering size of said items and in disregard of the different custom color and transparency, the same thing happens when no custom color is selected.~~

![2020-11-14_20 25 22](https://user-images.githubusercontent.com/69328977/99158260-ddb6ee00-26c8-11eb-8fc9-45d961714c45.png)

**To Reproduce**
1. Build KAMI Blue on commit 599a9dcdc3da29270ee9f94409f15fe0c3941c7c;
2. Ingame enable Chams;
3. See the weird rendering.

**Expected behavior**
1. The rendering respects the color and transparency selected;
2. ~~The rendering respects the actual real size of the entity being rendered, in other words, not render huge white squares.~~

**Screenshots**
Placed it on "Describe the bug" so I could explain better.

**Additional context**
None.

**Comment by omninope** [comment]
Just realized there are a lot more weird rendering of entities in the Chams module.

A correction for what I said on the original issue about items: block like items render with the correct dimensions but solid white while non block items render as big 2D solid white squares.

First, item frames. From left to right:

1. Exp orbs render as 2D squares;
2. Item frames render solid white. The first one contains a shulker box, which renders fine but not the item frame, the second one contains an non-block item which renders as a solid white 2D square and the last one is just the item frame. Block like items in a item frame render as a solid white cube with the correct dimensions.

![2020-11-15_03 10 49](https://user-images.githubusercontent.com/69328977/99171446-0b1f8e00-2701-11eb-84fe-133f5e3d4c6f.png)

Now for the armor stands. From left to right: Enchanted diamond, unenchanted diamond, enchanted iron, unenchanted iron, enchanted gold, unenchanted gold, enchanted chain, unenchanted chain, enchanted leather and unenchanted leather.

1. Enchanted diamond armor only has the chams effect applied to the chestplate and renders the arms of the chestplate model longer than normal, which is supposed to stop at the shoulder, some times the rendering of the arms go back to normal depending on the view angle;
2. Unenchanted diamond armor only has the chams effect applied to the chestplate;
3. Enchanted and unenchanted iron, gold and chain armor only has the chams effect applied to the chestplate;
4. Enchanted and unenchanted leather armor doesn't get the chams effect applied in any way. Some times, depending on the view angle, the chestplate renders as completly white with the longer arms described for the enchanted diamond armor, but I couldn't take a screenshot of that (well, I can but I'm lazy).

![2020-11-15_03 20 00](https://user-images.githubusercontent.com/69328977/99173597-38b90700-2702-11eb-8188-ae9833e45222.png)

The bow on skeletons renders with a white square, some times, depending on the view angle, same thing applies to the swords of zombie pigman and wither skeletons. Endermen are brighter than other mobs.

![2020-11-15_03 39 45](https://user-images.githubusercontent.com/69328977/99177890-ab77b180-2705-11eb-89ff-753453d34926.png)

The healing beam of end crystals render as a solid white color that fades to black.

![2020-11-15_03 33 37](https://user-images.githubusercontent.com/69328977/99177920-06110d80-2706-11eb-986b-35df89d8027f.png)

The chams effect on armor described for armor in armor stands doesn't apply to mobs using it.

![2020-11-15_04 04 19](https://user-images.githubusercontent.com/69328977/99178219-c13aa600-2708-11eb-8499-9400099c2b7b.png)

If you do damage to mobs they flash the original texture some times, depending on the view angle.

Thats it, I hope.

**Comment by Xiaro** [comment]
Square thing: That is just how minecraft renders it without texture. Turn on the texture or uncheck type for them

**Comment by omninope** [comment]
When I thought all problems where reported, here is another one:

When enabled, Chams breaks a lot of the rendering stuff if there is an entity close to the player, tested with ESP, Tracers, VoidESP, HoleESP, Search, CrystalESP, StorageESP, BreakingESP and SelectionHighlight.

What happens: At some angles everyting works just fine, at other angles the modules described above completly stop rendering and somewhere in between everyting renders very weirdly, like the example in the image below.

Build on commit c302b921449bbded5a5478b10599a59bea5ecfc6 and tested both in singleplayer and multiplayer, but I don't think that's relevant.
Can this be hardware and operating system specific? Someone else should test on their hardware.

![2020-11-16_20 02 39](https://user-images.githubusercontent.com/69328977/99318870-7469e300-2860-11eb-9745-aabca7705729.png)
