### ISSUE TITLE
YawLock / PitchLock combine into one, with options for sensitivity and unlock 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1592]
Created by: Charlie918 `(409173912832835614)`

Be able to turn from cardinal direction to cardinal direction and have a slider that increases or decreases sensitivity. Also an option for a mode where it disables when you move your mouse manually like Pyro

**Comment by FriedrichM** [comment]
I'll do this one. I could make it so it snaps to the next direction after you move your mouse a certain amount in some direction over a given time period.
This could be used both for the "hard locked" mode and the one where it only sets your rotationvalues every tick.
Im not sure if thats better than the slider one you suggested.

**Comment by l1ving** [comment]
That sounds good, yea
