### ISSUE TITLE
Null Crash in PacketLogger

### ISSUE THREAD

**Issue by spide-r** [kami-blue/client#1601]
**Describe the bug**
When the `readToList` function encounters a null line, a fatal error occurs
**To Reproduce**
I'm not entirely sure how this happens or how the line is null in the first place.

**Expected behavior**
The error would handle quietly and not crash my game.

**Additional context**
Crash Report:
https://hastebin.com/azulogogec

**Comment by l1ving** [comment]
![image](https://user-images.githubusercontent.com/17222512/99430671-a8ccb600-28d7-11eb-90f8-ddbc0d26c1c1.png)
Lol what
