### ISSUE TITLE
PortalChat is active even if the module is disabled

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1607]
**Describe the bug**
Even with PortalChat disabled the player can access their inventory and chat while in a portal.
Clean install, all default, nothing else enabled.

**To Reproduce**
1. Build KAMI Blue on commit a03084bc5cdf3b123023c8a6d01faff767322292;
2. Enter a singleplayer or multiplayer world;
3. Find a nether portal and enter it;
4. Try opening the inventory or typing in chat.

**Expected behavior**
Opening inventory and chat should only be possible when PortalChat is enabled. While not an real "issue" (it doesn't cause any real problems) this is not expected from the point of view of a casual user.

**Screenshots**
Not needed.

**Additional context**
No.

**Comment by l1ving** [comment]
https://github.com/kami-blue/client/blob/49c45780a7558c4f33d09eebf183b19028f00829/src/main/java/me/zeroeightsix/kami/mixin/client/player/MixinEntityPlayerSP.java#L60

I mean the code says otherwise lol
