### ISSUE TITLE
Freecam lack of head movement.

### ISSUE THREAD

**Issue by spide-r** [kami-blue/client#1608]
**Describe the bug**
When you enable freecam, you can't move your head around at all. Not sure if this is a mixin conflict with impact or not. 
**To Reproduce**
1. Use impact and kami latest
2. use freecam
3. try and move head

**Expected behavior**
Head should have moved

**Screenshots**
https://i.imgur.com/ZWGzEn2.mp4

**Additional context**
impact moment

**Comment by natan515** [comment]
There is no reason for u to use impact with kami blue, kami blue got all impact features and betters.

**Comment by l1ving** [comment]
What do you have enabled in Impact?

**Comment by spide-r** [comment]
nevermind I'm 🐒 impact esp is broken, kblue works fine

**Comment by l1ving** [comment]
what does this have to do with freecam then

**Comment by spide-r** [comment]
I was using impact freecam by mistake because I bound it a while back to test something. also smhhhhhh setting this as 1.1.7 just to add another number to "resolved bugs"
