### ISSUE TITLE
When used once, Flight on vanilla mode allows the player to fly even when the module is disabled

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1609]
**Describe the bug**
If the module Flight is enabled once, on vanilla mode, the player keeps the ability to fly, even if the module is disabled shortly after. To lose this ability the player must logout from the multiplayer server or close the singleplayer world, but no need to restart.

**To Reproduce**
1. Build KAMI Blue on commit 98048da293e163559393ec43f9fb1120805f2121;
2. Go to singleplayer or multiplayer and make sure you are in survival mode and don't have OP, if it's a server;
3. Enable Flight on Vanilla mode;
4. Try to fly, it works if it's singleplayer and you most likely get rubberbanded a lot in multiplayer;
5. Disable Flight;
6. Double jump;
7. Player starts to fly like creative (or gets rubberbanded like crazy), despite the module being disabled.

**Expected behavior**
The player shouldn't fly without the module enabled.

**Screenshots**
Not applicable.

**Additional context**
At first it appears to not be a big problem, since vanilla flight doesn't work on the vast majority of servers, but if the player misclicks and enable this for a second by accident, if they ever double jump after that, they will start flying and most likely rubberband and get kicked. Even worse if it's 2b2t.

**Comment by l1ving** [comment]
Will probably fix #1606

**Comment by spide-r** [comment]
can confirm this is a thing
