### ISSUE TITLE
Add spasific player to auto log

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1614]
**Is your feature request related to a problem? Please describe.**
Yes, rn I can't write a name that if he will join me(be near enough for my client to see) I will automatically disconnect.

**Describe the solution you'd like**
I would like so u would add a feature of or a name or UUID or a player so u will disconnect if he will get close to the player(In his range)

**Describe alternatives you've considered**
Just did...

**Additional context**
Nothing

**Comment by l1ving** [comment]
This is too specific to be useful. Autolog already has an option to ignore friends.

**Comment by natan515** [comment]
Yes, but we have names of griefers on the highway and it can be very nice to not let them a chance to crystal us and disconnect after more than 1 totem, and a need to have totems on u which make so u would have less place in ur inventoryt for highways. So if the player name "gjfkgdf" joined i will automaticly leave. more usfual that it sound.
