### ISSUE TITLE
Fake player is invis after my death

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1615]
**Describe the bug**
After i died with fake player on my fake player is invis..

**To Reproduce**

**Expected behavior**
Not be invis

**Screenshots**
![2020-11-22_10 49 35](https://user-images.githubusercontent.com/66911017/99899273-a213b980-2cb0-11eb-9a48-efbc1e4d3ce7.png)

**Additional context**
Pretty annoying bug

**Comment by Xiaro** [comment]
Oh so that happens after you died, I got someone else reporting it but had no idea what causes it

**Comment by natan515** [comment]
You want my log?

**Comment by l1ving** [comment]
https://github.com/kami-blue/client/commit/c98437924e17a9dd2be72f9cc39fd171ffd8e3d6
