### ISSUE TITLE
Kami blue ca isn't smart enough

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1616]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Wasn't sure if it was for a feature req or bug report.

I would like Kami blue ca to be smarter, have the crystals farther than me and closer to my enemies.
**Describe alternatives you've considered**
Make it smarter

And I got a video!
https://www.youtube.com/watch?v=hdYTELXc2R4&feature=youtu.be

**Comment by l1ving** [comment]
Change the targeting options to your preferences

**Comment by natan515** [comment]
What? No, it's just a bad placement I have no way to fix it, it has nothing to do with settings. Its an issue with kami blue ca

**Comment by natan515** [comment]
It's just a better place to put it... No settings here

**Comment by Xiaro** [comment]
It just calculate the placing position based on the damage :moyai:

**Comment by natan515** [comment]
No, the damage is 0, I'm creative and even with the damage, it's stupid! It's in a place that makes me more damage and less to him.....

**Comment by Xiaro** [comment]
You were on creativr so it does 0 damage to you. Basically just ignoring self damage

**Comment by natan515** [comment]
There is 0 resone to put there a crystal. No, I went after this to survival too and it did the same, and it does more to him still.

**Comment by l1ving** [comment]
It does not.
