### ISSUE TITLE
coords log crashes me in singlayer player when i /kill

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1617]
[debug.log](https://github.com/kami-blue/client/files/5579854/debug.log)
[latest.log](https://github.com/kami-blue/client/files/5579855/latest.log)
[crash-2020-11-22_18.53.32-client.txt](https://github.com/kami-blue/client/files/5579857/crash-2020-11-22_18.53.32-client.txt)

**Comment by l1ving** [comment]
Invalid, not running latest commit. Reopen if this happens in the upcoming release today, or if you build latest commit yourself.

**Comment by Xiaro** [comment]
They are running cracked Pyro so it probably fucks up the access transformer
