### ISSUE TITLE
Option to keep fake player after I die

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1618]
Option to disable and enable fake player after death

**Comment by Xiaro** [comment]
You are gonna be respawned back to spawn point so no point of adding this

**Comment by natan515** [comment]
Ye, but then I need to start fake player all the times, can be funny for bed trap

**Comment by l1ving** [comment]
Won't fix, this causes the bug described in #1615

**Comment by Xiaro** [comment]
I don't see how is this useful

**Comment by l1ving** [comment]
It'll restart where you spawned, making it useless anyways
