### ISSUE TITLE
Logout Logger + Fakeplayer spams the chat

### ISSUE THREAD

**Issue by spide-r** [kami-blue/client#1627]
**Describe the bug**
LogoutLogger spams the chat when it detects a fake player.

**To Reproduce**
1. Enable LogoutLogger
2. Enable FakePlayer

**Expected behavior**
No spam

**Screenshots**
![image](https://user-images.githubusercontent.com/29214314/100042874-f8c4e480-2dd1-11eb-87d0-26ccce51698d.png)

**Comment by l1ving** [comment]
send a screenshot of ;tsc when this happens

**Comment by spide-r** [comment]
🗿 will do soon
