### ISSUE TITLE
TotemPopCounter Not Working Bug

### ISSUE THREAD

**Issue by FerrumTheElement** [kami-blue/client#1631]
TotemPopCounter Not Working Bug.

When i turned on TotemPopCounter  on kamiblue and i popped someone's totem it doesn't show that i popped someone
[https://www.youtube.com/watch?v=eYk2kjQokAY&feature=youtu.be](https://www.youtube.com/watch?v=eYk2kjQokAY&feature=youtu.be)

I am on the latest version.

**Comment by l1ving** [comment]
That is *not* the latest version. Please provide a video of this issue on the latest version

**Comment by l1ving** [comment]
Closed as invalid, reopen with requested information.
