### ISSUE TITLE
Freecam is having some problems loading chunks

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1633]
**Describe the bug**
When u go on freecam chunks just become laggy, hard to explain, watch my vid for a straight explaining.

**To Reproduce**

1. Go to 'freecam on kamiblue'
2. Click on 'activate it.'
3. look at ur player as he moves
4. See how chunks don't load compare to other utility mods freecam

**Expected behavior**
It should just load everything in 5 chunks from the player, like every other freecam.

**Screenshots**
https://www.youtube.com/watch?v=BkJTD-YUfR0&feature=youtu.be

**Additional context**
Pretty annoying normally, the only reason I use pyro freecam.

**Comment by l1ving** [comment]
culling issue

**Comment by Xiaro** [comment]
No, just force it reload chunk on enable should fix it

**Comment by zeroeightysix** [comment]
> No, just force it reload chunk on enable should fix it

No - this really is culling. Minecraft omits parts of chunks, e.g. caves underground when it knows it's impossible for the player to see them (as a performance optimisation). However, it disables this behaviour when the player is in spectator mode AND in an opaque block. In 1.16.4 I know there's a field in `Minecraft` that also allows you to disable chunk culling, but I don't know if that exists in 1.12.2.

**Comment by l1ving** [comment]
The old freecam disabled culling in freecam with a Mixin, wouldn't be too trivial to find it

**Comment by Xiaro** [comment]
> The old freecam disabled culling in freecam with a Mixin, wouldn't be too trivial to find it

It already does it

**Comment by l1ving** [comment]
# :moyai:

**Comment by natan515** [comment]
Thank you! (;
