### ISSUE TITLE
3D freecam

### ISSUE THREAD

**Issue by Doogie13** [kami-blue/client#1642]
**Is your feature request related to a problem? Please describe.**
some people may prefer it idk

**Describe the solution you'd like**
Similar to noclip in source games and 3d flight mode in impact client a mode that moves freecam in the direction your looking including y axis (so if your looking up and press w your camera would go up rather than forwards

**Describe alternatives you've considered**
seppuku

**Additional context**

Would work like elytra boost except you press w to boost if that makes it any clearer

**Comment by natan515** [comment]
Can explain it better, please?  I have no idea what u mean.

**Comment by Doogie13** [comment]
If I look at a 30° angle from forward and press 'w', I will just go forward. In 3D mode  my camera would move up at a 30° angle. This gives more precision. If you've ever played Garry's mod you can press v and do something similar.

**Comment by Xiaro** [comment]
Flight in beta version of Minecraft
(The controllability is terrible tbh)

**Comment by l1ving** [comment]
Some people like the controlability I guess lol. I forgot which game was it but I've seen a few games with this, I believe Portal 2's freecam works this way

**Comment by FriedrichM** [comment]
i can make an option for this
