### ISSUE TITLE
Fake player just doesn't leave

### ISSUE THREAD

**Issue by natan515** [kami-blue/client#1649]
I asked him nicely to leave while disabling him and he just kept being there... Very rude.

**Comment by natan515** [comment]
![2020-11-29_23 08 47](https://user-images.githubusercontent.com/66911017/100553689-ddf1e480-3297-11eb-952a-208439d082df.png)

**Comment by natan515** [comment]
This photo is after disabling, worth saying I use optifine.

**Comment by l1ving** [comment]
Pyro bug

**Comment by natan515** [comment]
Why is entity still there?

**Comment by l1ving** [comment]
user error
