### ISSUE TITLE
freecam rendering

### ISSUE THREAD

**Issue by bensonious** [kami-blue/client#1655]
**Describe the bug**
when in freecam, with other mods that have render modification (other clients hole render, schematicas render, the render modifications follow your character in freecam state

**To Reproduce**
1. have a different modification with render changes
2. freecam
3. move arund 

**Expected behavior**
render modifications should stay in their original place
 
**Screenshots**
inertias freecam, render mods stay in place
![Screenshot (226)](https://user-images.githubusercontent.com/72408961/100757087-f22f0200-33bb-11eb-986c-105b1f69580e.png)
kami blue freecam, render mods come with your character
![Screenshot (227)](https://user-images.githubusercontent.com/72408961/100757161-070b9580-33bc-11eb-8594-6115ab110b39.png)

**Additional context**

**Comment by l1ving** [comment]
Won't fix, use KAMI Blue's equivalent render modules. 

KAMI Blue's freecam uses a different render entity, if other mods don't use the current render entity that's not our problem

**Comment by bensonious** [comment]
well im pretty sure kami doesnt have schematica

**Comment by bensonious** [comment]
hmm ok

**Comment by l1ving** [comment]
That's already reported in #1506

**Comment by bensonious** [comment]
ah mkay
