### ISSUE TITLE
Non-ASCII characters incompatible with Custom Chat

### ISSUE THREAD

**Issue by Supercolbat** [kami-blue/client#1657]
**Describe the bug**
Non-ASCII characters don't display properly in chat when relaunching Minecraft. They are instead replaced with question marks. All other characters display properly.

**To Reproduce**
1. Set your custom chat ending to anything that includes non-ASCII characters (`;chat "ᴀʙᴄ"` ).
2. Close Minecraft and relaunch it.
3. Type anything in chat or alternatively check `KAMIBlueConfig.json`.
![image](https://user-images.githubusercontent.com/24477470/100935050-37832a80-34b5-11eb-9751-ffa9f12756a9.png)

**Expected behavior**
The chat ending should be what you originally put in.

**Additional context**
This can be solved by Unicode escaping the characters first before storing them. I tried this out by modifying the config file and it worked. For example, `ᴀʙᴄ` would translate to `\u1d00\u0299\u1d04`.

**Comment by l1ving** [comment]
This is due to how the config is loaded and saved, please reopen the bug report if it happens in the rewrite
