### ISSUE TITLE
Use durability instead of percentage in ElytraReplace

### ISSUE THREAD

**Issue by bensonious** [kami-blue/client#1659]
**Is your feature request related to a problem? Please describe.**
when afk flying, i use elytrareplace so I don't fall out of the sky while flying, I set the broken% to the lowest (1%) but in a test world I notice I can still fly for a few hundred blocks at 1 percent and still has 4 durabilities on the elytra and I think it would be better to have elytra replace at 2 dura for a few extra hundred blocks of travel

**Describe the solution you'd like**
have an option for % or raw durability, so users can have an option for less precise or more precise option 

**Describe alternatives you've considered**
other clients that have it arent as good

**Additional context**
nope

**Comment by l1ving** [comment]
I didn't think an imprecision of 2 dura would make that much of a difference, but I guess it could easily be done. Code-wise it would be clearer, just less intuitive on the user side. 

> Describe alternatives you've considered
> other clients that have it arent as good

rofl

**Comment by bensonious** [comment]
I'm not sure but from my experience 2 dura can get me abt 500 or so blocks depending on the speed of elyfly, idk for sure tho, a bit extra use is always useful
