### ISSUE TITLE
Add an option to the Strafe module to cancel player inertia

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1660]
**Is your feature request related to a problem? Please describe.**
No, it's an improvement to Strafe.

**Describe the solution you'd like**
When the player stops all movement input, normally they will continue to move for some time, making the player not land where they wanted or fall off a block they landed. Of course this can be overcome with skill, but who needs skill when we have mods?
My suggestion is: Add an option to the Strafe module to completly cancel player inertia, so they just stop on a dime when they stop movement input. And yes, this works on servers.
I'm suggesting this as an option because some people may not want it, so they can just disable the option.

**Describe alternatives you've considered**
No comment.

**Additional context**
As an example, Wurst+2 Strafe module does that. You can try it for yourself to "feel" what I'm trying to describe. Also Meteor Speed module does that somehow, but it's Fabric 1.16.4.

**Comment by l1ving** [comment]
Would you have any idea where this is calculated?

**Comment by omninope** [comment]
No actually. Some weeks ago I looked at the source of mods that do what I described but due to my lack of knowledge I couldn't figure out what was happening. I also tried to implement it by myself but gave up, so this is why I oppened an issue instead of a pull request :)

**Comment by l1ving** [comment]
Most likely some random Mixin somewhere

**Comment by Xiaro** [comment]
This have nothing to do with mixin 🗿
