### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#173]
I've decided to reopen this for several reasons

- We're reaching 160 modules. I think I'm going to reject additional modules and leave them in branches for now, for several reasons.
  - GUI is way too fucking cluttered. GUI rewrite is in progress, #790
  - Some modules most people won't need. It would be nice to remove those and have them readded as plugins
  - Due to how poorly the GUI is designed, more modules exponentially decreases the performance.
- We're currently rewriting this in Kotlin (just hit 50% Kotlin at the time of writing), so Javascript plugins are WAYYYY easier.
- Having a plugin repo with signed plugins is a must, and show a "verified" badge in some plugin menu 
- Even after the recent module manager optimizations and part rewrite, having hundreds of modules isn't amazing for loading times and again, most people don't need some modules.

**Comment by cookiedragon234** [comment]
A lot of problems arise with this. Firstly mappings, the plugin will either need to be mapped to mcp at compilation or runtime.

Secondly the security issue brought up in the original issue, a user might assume that plugins are sandboxed and therefore safer than full clients, however this is not possible.

**Comment by S-B99** [comment]
Yea, there would be a security issue. For that, I'd only be including plugins I've checked under a plugin repo, and warn people about downloading whatever.

I mean, in the end it's like downloading some kami skid. You're responsible for however dangerous it may be, since I don't endorse those

**Comment by cookiedragon234** [comment]
In my opinion, the best plugin system is one written in javascript. This way you *can* properly sandbox the plugin enviroment, it is also *much* easier for people to learn how to write the plugins, and also to hot reload them at runtime creating faster development. Obviously experienced developers would prefer Java, but if they're at that experience level they should be making their own client.

**Comment by S-B99** [comment]
I doubt people will write plugins for it, though it would be nice.
The main reason I want a plugin system is to break down the main client  into easily usable parts, because as you can see there are 75ish opened issues and the menu already has so many modules, most of which I know people don't use.

Also I would have no idea where to start with porting it all to JavaScript, let along execute Java code in Javascript, if that's even possible??

**Comment by S-B99** [comment]
Also a sandbox system would only be for stopping complete idiots from downloading whatever and putting it in the plugin folder

**Comment by cookiedragon234** [comment]
> Also I would have no idea where to start with porting it all to JavaScript, let along execute Java code in Javascript, if that's even possible??

https://github.com/cookiedragon234/Backdoored-1.5-leak/blob/master/src/com/backdoored/hacks/chatbot/Announcer.java

and

https://github.com/cookiedragon234/Backdoored-1.5-leak/blob/master/src/com/backdoored/hacks/chatbot/AnnouncerScriptHandler.java

Not to flex or anything, but we were the first client to have completely scriptable announcer and chatbot

**Comment by S-B99** [comment]
Only doing this for 1.14, which this repo is not

**Comment by l1ving** [comment]
One thing which is nice to have would be a way to dictate which modules / plugins a plugin is incompatible with, and be able to show a warning in the plugin gui / disallow enabling both at once. 

This could be accomplished with an annotation that contains a list of strings, and after all modules and plugins are loaded you can set a lazy value to the classes of incompatibles, and check when enabled / in gui

**Comment by x4e** [comment]
😬

**Comment by l1ving** [comment]
cooker moment
