### ISSUE TITLE
Dupe that might work idk

### ISSUE THREAD

**Issue by Doogie13** [kami-blue/client#1757]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I saw this cyri video on a 1.16 dupe and wondered if it would work on 1.12.2. there is a fabric mod in the description of the video that could be reverse engineered for 1.12.2. idk if it would work tho.

**Describe alternatives you've considered**
Mod + viafabric

**Additional context**
Video by cyri https://youtu.be/M_Y-IyG5rk4

**Comment by l1ving** [comment]
It's 1.16 specific

**Comment by Doogie13** [comment]
K
