### ISSUE TITLE
Antidisconnect screen misaligned

### ISSUE THREAD

**Issue by sedfg** [kami-blue/client#1765]
<img width="1440" alt="Screen Shot 2020-12-26 at 11 06 38 am" src="https://user-images.githubusercontent.com/38718075/103143464-9e20fe80-476a-11eb-99a6-f6bf2230f55a.png">
I have no idea what caused it but one day I logged in and every time after that it looks like this.

 I imagine that I should be able to provide files which can explain how/why.

**Comment by l1ving** [comment]
wtf

**Comment by l1ving** [comment]
send a screenshot of f3

**Comment by Xiaro** [comment]
Well yes this happens after you resize the game in the gui

**Comment by sedfg** [comment]
![2020-12-26_13 16 26](https://user-images.githubusercontent.com/38718075/103144382-9c603680-477c-11eb-9b00-82eb8cf96fcb.png)
My f3 screen has been like this for a while, might be caused by another mod..
