### ISSUE TITLE
Custom Held Item view (please rename if you know a proper name for it)

### ISSUE THREAD

**Issue by zisis912** [kami-blue/client#1769]
many clients ive seen have an option to change how the items that the player is holding look on his hand. I will show some screenshots. 
![image](https://user-images.githubusercontent.com/65046191/103173122-6d6fc080-4861-11eb-86a9-6a782014d195.png)
![image](https://user-images.githubusercontent.com/65046191/103173137-84161780-4861-11eb-9163-2a224a096635.png)
![image](https://user-images.githubusercontent.com/65046191/103173240-48c81880-4862-11eb-9ab3-b84283414983.png)

**Comment by l1ving** [comment]
#1089
