### ISSUE TITLE
Autoexec

### ISSUE THREAD

**Issue by Doogie13** [kami-blue/client#1771]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An autoexec file that is read as soon as you join a server and any commands etc typed into chat. This should be server specific as well as a generic one executed as soon as you join any server **before** the server-specific one.

Example: olgfag.orgautoexec.txt would be generated as soon as you join oldfag.org for the first time. This txt file could be filled with any commands you wanted to be executed. This would effectively type the text into chat so if you used other clients you could add commands for those as well. This could try to catch any text packets sent to the server so you don't type stuff in chat automatically but should not prevent other clients from accessing the commands. 

**Describe alternatives you've considered**
Not being lazy.

**Additional context**
Any source game will have this (autoexec.cfg).

**Comment by l1ving** [comment]
LoginMessage does this. Open a new issue for the multi line support, to make it easier to keep track of. The server specific configs is already planned as a whole.

**Comment by l1ving** [comment]
LoginMessage does this. Open a new issue for the multi line support, to make it easier to keep track of. The server specific configs is already planned as a whole.
