### ISSUE TITLE
Multiline support for LoginMessage

### ISSUE THREAD

**Issue by Doogie13** [kami-blue/client#1772]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Login message designed to run commands. Should have multiple lines. Probably would be easier to edit from a file. Maybe add a text editor to the new GUI to edit the config file?

**Describe alternatives you've considered**
Typing out each individual command/message.

**Additional context**
WaSd

**Comment by l1ving** [comment]
> Maybe add a text editor to the new GUI to edit the config file?

That's already planned 

> Login message designed to run commands

It already can

**Comment by iBuyMountainDew** [comment]
Sorry about earlier.

**Comment by l1ving** [comment]
For future reference, if you put "Closes #X" it'll link and close the issue. 

```
[enhancement] LoginMessage multiline support

Closes #1772
```

Just letting you know in case you want to do that, I find it easier than opening a browser again and closing it manually.

And that's fine. Everybody makes git mistakes, I went and made a bad commit immediately after you did.
