### ISSUE TITLE
TargetStacks in AutoObsidian is not accurate 

### ISSUE THREAD

**Issue by test1230-lab** [kami-blue/client#1780]
When using the TargetStacks feature of AutoObsidian, the fortune level of the pickaxe isn't taken into account. For a Fortune III pickaxe, 8 obsidian is dropped when mining an enderchest. I suggest there is an option to change the amount expected to drop in the clickgui.

**Comment by Xiaro** [comment]
Fortune pickaxe doesn't make it drop more obby and it is multiplied by 8 already

**Comment by theredstoner** [comment]
Target stacks is not accurate, but not because of this. I am rewriting AutoObsidian in Avanatiker/client and I will open a PR when it is fully done.

**Comment by test1230-lab** [comment]
Really sorry for the misinformation, I was sure that this was a mechanic. Good to hear that it is being fixed nonetheless.

**Comment by Xiaro** [comment]
> Target stacks is not accurate, but not because of this. I am rewriting AutoObsidian in Avanatiker/client and I will open a PR when it is fully done.

It was rewritten already and counting both the obby in inventory and dropped ones. You were probably talking about the one in HighwayTool. It wasn't merged properly so it doesn't have the fixed version.

**Comment by test1230-lab** [comment]
[](https://streamable.com/o7aayp) it seems to overshoot the target.

**Comment by l1ving** [comment]
We need a screenshot of ;tsc to help you.

Just like the correct bug template asks

**Comment by test1230-lab** [comment]
https://i.imgur.com/oIylrHF.png

**Comment by l1ving** [comment]
You're not using the latest version, which has the fix for AutoObsidian

**Comment by test1230-lab** [comment]
https://github.com/kami-blue/nightly-releases/releases/download/1.12.30-0d247244/kamiblue-1.12.30-0d247244.jar is this the latest?

**Comment by l1ving** [comment]
Yes, it's latest. At least, for the next few hours, but it does have the fix.

**Comment by huddy987** [comment]
@Xiaro I have this issue fixed in highwaytools repo. It was merged properly.

**Comment by l1ving** [comment]
No... it was not https://www.diffchecker.com/mBkL1TPh

**Comment by huddy987** [comment]
It might not be merged yet but regardless its fixed in the highwaytools repo

**Comment by test1230-lab** [comment]
It sometimes  seems to get stuck in a state where is cant place anything unless there is player intervention like manually moving. This is latest built, 
https://user-images.githubusercontent.com/64430532/103443423-2b61c880-4c2d-11eb-9a94-5ff49daa97d5.mp4

**Comment by huddy987** [comment]
Seems I missed this https://github.com/Avanatiker/client/pull/29

My bad.

**Comment by test1230-lab** [comment]
I should probably open a new issue for my above comment, this has been resolved. the target stacks is working as expected.

**Comment by l1ving** [comment]
> It might not be merged yet but regardless its fixed in the highwaytools repo

It's also fixed in our repo.

> where is cant place anything unless there is player intervention like manually moving

That is a Baritone issue.
