### ISSUE TITLE
option for notebot to not tune whenever a song is loaded

### ISSUE THREAD

**Issue by feliscatusmeows** [kami-blue/client#1785]
**Is your feature request related to a problem? Please describe.**

It seems a bit unnecessary to have to tune noteblocks again when changing songs. 
**Describe the solution you'd like**

Add an option that disables tuning per song, or seperate notebot from notebot tuner. 
**Describe alternatives you've considered**

String all songs into one long notebot song. Obviously isn't great because it means no more choice. 
**Additional context**

![image](https://user-images.githubusercontent.com/29553771/103485170-5113dc80-4da9-11eb-9fcf-d39907eea324.png)
I was told to suggest this so i did.

**Comment by Xiaro** [comment]
There is no tuning, it is just scanning the note blocks's sound and pitch. And it is a required for note bot to work. And yon't need toggle the module to load new song. There is a reload song button in the setting page.
