### ISSUE TITLE
Make notebot auto-set channels

### ISSUE THREAD

**Issue by feliscatusmeows** [kami-blue/client#1786]
**Is your feature request related to a problem? Please describe.**

It's painful to listen to a song that should have 5 instruments crammed into 1 piano instrument. 
**Describe the solution you'd like**

Make the notebot detect what instruments are in which channels and set the instruments accordingly. 
**Describe alternatives you've considered**

Manually setting it could be possible, but it involves too much trial and error. 
**Additional context**

**Comment by Xiaro** [comment]
Already closed in #1906
