### ISSUE TITLE
Notebot support `.nbs` format

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1787]
Inertia and possibly others support this format, and it makes it easy to make noteblock songs

Code for loading: https://github.com/HielkeMinecraft/OpenNoteBlockStudio/blob/862ee521f239c600c53f21ef8f9714cdb08f3940/scripts/load_song/load_song.gml#L31

Spec: https://opennbs.org/nbs

**Comment by feliscatusmeows** [comment]
I will warn you that both opennbs and the older nbs use .nbs file extension, but I am not sure of the differences. The spec for the old noteblock studio should be at https://www.stuffbydavid.com/mcnbs/format.
