### ISSUE TITLE
While searching for a module, pressing your GUI bind will close the GUI

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1793]
The "best" solution for this might be ignoring gui bind to close the gui when it's a letter.

If we ignore the bind while typing, it will still close if the module name starts with that bind.

**Comment by Doogie13** [comment]
would be cool if the search bar was a seperate catagory with a search bar instead of a title which filtered as you type (somewhat similar to meteor) as having modules disapear on the main client is annoying sometimes
