### ISSUE TITLE
The client cannot build.

### ISSUE THREAD

**Issue by zisis912** [kami-blue/client#1807]
when I run `gradle build` on client-master, it says build failed. 
![image](https://user-images.githubusercontent.com/65046191/103746347-a4846580-5009-11eb-88ae-3869a9e793b8.png)
If you need more information, I can try building with --scan

**Comment by iBuyMountainDew** [comment]
Please properly follow the contribution instructions.

**Comment by zisis912** [comment]
I checked the contributing page and tried again. I forked the repo, cloned it, run the setupworkspace.sh, but when I tried to do `./gradlew build`, this happened
![image](https://user-images.githubusercontent.com/65046191/103749338-11016380-500e-11eb-89ea-b561f4f47f5a.png)

**Comment by iBuyMountainDew** [comment]
You'll have to import into IntelliJ before building. All other IDEs and development environments are unsupported.

**Comment by zisis912** [comment]
so I open the client folder in intellij, and then compile it using the intellij gradle intergration?

**Comment by iBuyMountainDew** [comment]
Don't download the zip by the way; always use the actual `git clone`. 
Anyway, open the `build.gradle` file in the folder as a project and it'll automatically import.

**Comment by zisis912** [comment]
i cloned it, don't worry

**Comment by Xiaro** [comment]
> You'll have to import into IntelliJ before building. All other IDEs and development environments are unsupported.

no, they are just not running the setup script properly

**Comment by iBuyMountainDew** [comment]
How can you mess up running a *script*??

**Comment by l1ving** [comment]
No actually, we figured out with someone that some magical stuff doesn't download when running the setup script on entirely new machines.

**Comment by zisis912** [comment]
I needed to do it in intellij.
