### ISSUE TITLE
CA bug

### ISSUE THREAD

**Issue by Doogie13** [kami-blue/client#1810]
**Describe the bug**
CA doesnt do the C

**To Reproduce**

Use the CA
[https://youtu.be/ZHW-WH50hbA](https://youtu.be/ZHW-WH50hbA)

**Expected behavior**
It will kill the enemy with crystals placed and broken rapidly

**Debug info**
![image](https://user-images.githubusercontent.com/62295632/103799571-2d6bc300-5043-11eb-81c2-52bcfa725c8a.png)

**Additional context / media**
I have got it working ages ago before IDK how

**Comment by Xiaro** [comment]
Already fixed in #1809
