### ISSUE TITLE
Re-add spaces to setting names

### ISSUE THREAD

**Issue by Xiaro** [kami-blue/client#1813]
#972 Since we have greedy string already. What is the point of having weird user unfriendly name with no spaces.

:wonk:

**Comment by l1ving** [comment]
What about commands...?

**Comment by Xiaro** [comment]
> What about commands...?

Since most of them have single word name so doesn't matter.
I mean you can still do it with 2 literals arguments at the beginning but commands don't really matter that much.

**Comment by l1ving** [comment]
Most modules are more than one word, the toggle command would become incredibly annoying with a space

**Comment by l1ving** [comment]
I'm fine with refactoring settings to have spaces in their names, just not module names.

**Comment by Xiaro** [comment]
> Most modules are more than one word, the toggle command would become incredibly annoying with a space

Just make it also accept names without space

**Comment by l1ving** [comment]
The preview would be ugly, and it's 2x slower to store 2 lists of module names :wonk:

**Comment by Xiaro** [comment]
> The preview would be ugly, and it's 2x slower to store 2 lists of module names :wonk:

It never stores it. And the preview are done in another thread so :wonk:
