### ISSUE TITLE
Discord Notifs Regex

### ISSUE THREAD

**Issue by 18gatenmaker** [kami-blue/client#1814]
**Describe the bug**
The regex in [DiscordNotifsCommand.kt](https://github.com/kami-blue/client/blob/b4467fa0e160053a5249c41db106c874392e778d/src/main/java/me/zeroeightsix/kami/command/commands/DiscordNotifsCommand.kt#L13) never matches. (line 13)

**To Reproduce**

1. Make a Discord Webhook and copy the url
2. Paste it into the `;discordnotifs` command
3. Regex doesn't match due to non-escaped forward slash and a 2 at the end

**Expected behavior**

The regex should match and the url should have been set.

**Debug info**

I dont think that you need a screenshot, but here goes: [Imgur link](https://imgur.com/a/I9a6mvy)

**Additional context / media**

I am not sure, but i tested the regex and i think it should be:
`^https:\/\/.*discord.com\/api\/webhooks\/([0-9])+\/.{68}$`

**Comment by l1ving** [comment]
It works on older urls. I think discord changed the length
