### ISSUE TITLE
Get ArmourHUD to show stacked armour properly

### ISSUE THREAD

**Issue by muppetcode** [kami-blue/client#1821]
**When wearing stacked armour, ArmourHUD currently just displays it as normal armour without the stack value.**

![kamihud](https://user-images.githubusercontent.com/69520038/104001853-2a361b80-5198-11eb-81a0-ccf6318977e9.PNG)
This is how stacked armour is shown

![w+2hud](https://user-images.githubusercontent.com/69520038/104001931-48038080-5198-11eb-90ad-041842514066.PNG)
This is how I would like it to be shown (Ignore the durability percentage)

I just thought this would be useful as quite a few popular servers have stacked items and this is on almost every other client I have used.

**Comment by l1ving** [comment]
... did you disable the stack setting by any chance?

**Comment by muppetcode** [comment]
> ... did you disable the stack setting by any chance?

No setting shows up

**Comment by l1ving** [comment]
the setting is called ArmorCount

**Comment by Xiaro** [comment]
![image](https://user-images.githubusercontent.com/62033805/104025695-01f7ee00-5193-11eb-87ce-76861c89d58c.png)
🤔

**Comment by l1ving** [comment]
Closing as invalid
