### ISSUE TITLE
SVG rendering for KamiMoji

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1825]
Currently the quality of shrunken png emojis looks quite poor compared to the new fontrenderer and all of that. It would be nice to support drawing svgs and glScaling them smaller to prevent such a huge loss of quality, and it will save download space instead of downloading pngs.

**Comment by Xiaro** [comment]
No, all the emojis were in png format https://github.com/2b2t-Utilities/emojis

**Comment by l1ving** [comment]
The emojis themselves in that repo are just converted from existing svgs. I don't mind adding an svg branch and readding the svgs to that repo, I have push access.

**Comment by iBuyMountainDew** [comment]
🙄

**Comment by Xiaro** [comment]
No, all you need is just mipmapping not svg

**Comment by Xiaro** [comment]
> The emojis themselves in that repo are just converted from existing svgs. I don't mind adding an svg branch and readding the svgs to that repo, I have push access.

And no, some of the custom ones were not svg

**Comment by l1ving** [comment]
That's fine, most of them were. We can just support both.
