### ISSUE TITLE
Parkour hack

### ISSUE THREAD

**Issue by sedfg** [kami-blue/client#1829]
Jumps whenever you reach the edge of a block, has an option to jump in a range slightly earlier to fake authenticity.

**Comment by sedfg** [comment]
the jump slightly before the edge of the block is espeially important is 2b will lag you back if you jump at the very edge like you do with impact's version of the utility

**Comment by l1ving** [comment]
I already closed this as a duplicate

**Comment by sedfg** [comment]
oh sorry
