### ISSUE TITLE
BooleanButton clicking is insensitive / sometimes missed 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1842]
Occasionally BooleanButton clicks won't register, which I assume is due to it waiting for a drag event. My proposed solution is to toggle the button on drag, which makes more sense intuitively with the animation.

**Comment by Xiaro** [comment]
Intentional design to avoid misclick. You can move away the mouse to cancel the click.(which is what 99.9% of the ui buttons does)

**Comment by l1ving** [comment]
Well it makes it feel like the gui is missing clocks, and I've definitely noticed it myself

**Comment by Xiaro** [comment]
Probably because minecraft only update mouse input on tick :moyai:
