### ISSUE TITLE
ClickGUI will resize while dragging scale slider, instead of waiting for the slider to be released 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1843]

**Comment by Xiaro** [comment]
Intentional design to avoid dragging bug or misclick.

**Comment by l1ving** [comment]
Well it's user unfriendly. I'd rather toggle a slider if someone drags it

**Comment by Xiaro** [comment]
> Well it's user unfriendly. I'd rather toggle a slider if someone drags it

It isn't. If you resize on drag right away it will cancel the drge because of the position change

**Comment by l1ving** [comment]
Oh I replied to the wrong issue. What I meant to say was, I'd rather it wait to release the slider before resizing, instead of resizing while dragging

**Comment by Xiaro** [comment]
> Oh I replied to the wrong issue. What I meant to say was, I'd rather it wait to release the slider before resizing, instead of resizing while dragging 

It already wait for 1 second on value change. And gui and module is separated you can change the button's behavior on module side
