### ISSUE TITLE
Out of Fov Arrows

### ISSUE THREAD

**Issue by Bluestacker** [kami-blue/client#1845]
**Is your feature request related to a problem? Please describe.**
not a problem, just a new feature.

**Describe the solution you'd like**
This new module it's called OOF Arrows or " Out of Fov Arrows" basically this thing works like tracers but instead of ugly lines using all the screen its cool arrows, how does this work? when you have an enemy behind you a arrow will appear facing down indicating you have a player behind you, just like tracers but nicer, this could even be an option in tracers.

Example:

1 enemy on the right
![R](https://user-images.githubusercontent.com/19354317/104473940-4670f880-559c-11eb-94d1-20a812832fb5.jpg)

3 enemies on the left
![L](https://user-images.githubusercontent.com/19354317/104474014-5688d800-559c-11eb-94b7-b1fc3e737ded.jpg)

**Describe alternatives you've considered**
-

**Additional context**
This is actually a unique feature in minecraft utility mods

**Comment by l1ving** [comment]
#1347
