### ISSUE TITLE
Loqout spot

### ISSUE THREAD

**Issue by sedfg** [kami-blue/client#1847]
It puts an outline around where someone in my render distance logged out, shows the playername and options for showing the gear they had on like nametags does.

**Comment by l1ving** [comment]
what do you think waypointrender is for

**Comment by sedfg** [comment]
> what do you think waypointrender is for

what do you mean. Way point render doesnt have an option to show logout spots - at least I cant see it.

**Comment by Xiaro** [comment]
> > what do you think waypointrender is for
> 
> what do you mean. Way point render doesnt have an option to show logout spots - at least I cant see it.

It just got mixed up with other waypoints like coords log, stash logger
