### ISSUE TITLE
Ghost containers - storage ESP

### ISSUE THREAD

**Issue by sedfg** [kami-blue/client#1848]
**Describe the bug**
oooo spppooooky (see image). Turning off and on doesnt fix it 

**To Reproduce**
Im not 100% but I believe this is how:
1) Get shulker
2)open shulker
3) Break it before either it starts closing or is fully closed
4) Spooky

**Comment by sedfg** [comment]
![Uploading 2021-01-14_22.14.40.png…]()

**Comment by sedfg** [comment]
![2021-01-14_09 10 16](https://user-images.githubusercontent.com/38718075/104586490-a4dfc900-56b9-11eb-9305-707b795aa66d.png)

**Comment by sedfg** [comment]
I have a replay mod recording if you need to see exactly how it happened

**Comment by l1ving** [comment]
fill out the **entire** issue template properly, we can't accept this as a valid bug report without all the info
