### ISSUE TITLE
Centered Setting Panes 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1861]
Created by: Voxel (<@245404909229441024>)

 when right clicking a module to adjust it's settings, I'd like the option for the settings pane to spawn where my mouse is halfway across the top row or centered over the module list as opposed to the top right of my mouse position, where it currently does. perhaps this request could be expanded to add a custom x/y offset when opening a pane.

**Comment by Xiaro** [comment]
Centered pop up panel is actually a bad idea and you can misclick things when you spam click.
Better solution at #1862
