### ISSUE TITLE
Settings panes go offscreen 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1862]
Created by: Voxel (<@245404909229441024>)

 If you've expanded a module category so that a modules are visible close to the bottom of your screen, when you right click on one to open its settings the pane will spawn offscreen. if you attempt to move the pane it will immediately jump back into view.

**Comment by Xiaro** [comment]
Solution: 
X axis:
![image](https://user-images.githubusercontent.com/62033805/105189089-9999fc80-5b02-11eb-8642-dab5928fdf8c.png)
![image](https://user-images.githubusercontent.com/62033805/105189116-a0c10a80-5b02-11eb-8bd1-90cbbc61eec0.png)
Pops up window on the right side of the mouse. If there isn't enough space on the right side, pops up on the left.

Y axis:
![image](https://user-images.githubusercontent.com/62033805/105189274-cd752200-5b02-11eb-8b06-8be89a3faab0.png)
![image](https://user-images.githubusercontent.com/62033805/105189589-20e77000-5b03-11eb-9069-7403f600f031.png)
![image](https://user-images.githubusercontent.com/62033805/105189303-d49c3000-5b02-11eb-980d-32f09892a280.png)
Pops up on below the cursor. And limit it in the view area
