### ISSUE TITLE
Add thousands separators option for the HUD

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1863]
There should be a universal European setting (maybe tied to language when #797 is implemented) that turns `1,234.55` to `1.234,56`

**Comment by scorbett123** [comment]
How does that commit close this, this is talking about language when doing this, not just putting them in, unless I am missing something in your commit this doesn't fix this issue.

**Comment by l1ving** [comment]
Apparently Xiaro localized it somehow.

**Comment by Xiaro** [comment]
String format will format numbers with your JVM default locale (Which is based on your os setting)

**Comment by scorbett123** [comment]
Ok, sorry I have completely mis-understood this, I thought that it just put what you put in, not that the "," just means to put a thousands separator in.
