### ISSUE TITLE
Packetfly enhancement

### ISSUE THREAD

**Issue by sedfg** [kami-blue/client#1864]
**Is your feature request related to a problem? Please describe.**
Some other clients have a version of packet fly that enable you to escape the elytra freeze thing, kami does not. A version of packet fly that allows for this would be greatly appreciated.

**Comment by l1ving** [comment]
I'm not sure what this means, but it sounds useless with the Elytraflight module

**Comment by l1ving** [comment]
Reopen this if you can explain why it would be useful and how it works
