### ISSUE TITLE
Disable allowBreak when AntiAfk is enabled 

### ISSUE THREAD

**Issue by sedfg** [kami-blue/client#1865]
**Is your feature request related to a problem? Please describe.**
If you die and respawn it is possible for anti afk to break your bed. Eg you die and Anti-death-glitch-screen is active 

**Describe the solution you'd like**
While the movement part of anti afk is active there should be an option for a special clause making it impossible to break a bed.

 I know that #allowbreak exists but having something that automatically does it would make everything a lot less stressful.

**Describe alternatives you've considered**

**Additional context**
Personal experience

**Comment by l1ving** [comment]
This isn't something we can do without you disabling allowBreak

**Comment by sedfg** [comment]
I was thinking of an option where while it is active it disables allow break and then reanables it when it is turned off (assuming it was allowed in the first place of course). 

This should be doable right?
