### ISSUE TITLE
Remove AntiChainPop

### ISSUE THREAD

**Issue by Xiaro** [kami-blue/client#1869]
It is pretty useless against anyone with a fast ca. You can't surround your feet with obsidian because of the hitbox of crystal. It can even trigger the server anti cheat and get you rubber band then die.

**Comment by l1ving** [comment]
Once plugins are implemented

**Comment by Xiaro** [comment]
No I mean removing it entirely. Not moving it to plugin.

**Comment by l1ving** [comment]
okay lol
