### ISSUE TITLE
Improve Strafe to work on servers such as cpvp

### ISSUE THREAD

**Issue by Doogie13** [kami-blue/client#1872]
**Describe the bug**
When using timerspeed and airspeed you rubberband on cpvp.cc

**To Reproduce**

1. Go to cpvp.cc
2. enable strafe with auto jump, airspeed and usetimer
3. hop around the floating island
4. Rubberband after a few seconds

**Expected behavior**
You can hop around at around 30km/h

**Debug info**
![image](https://user-images.githubusercontent.com/62295632/105365640-5f118c00-5bf6-11eb-8728-9f1c293ce0ef.png)

**Additional context / media**
clients often get 30km/h without timer (maybe an option to adjust airspeed speed would help?)

**Comment by l1ving** [comment]
Not a bug

**Comment by Xiaro** [comment]
Turn off AirSpeedBoost it should work just fine.

**Comment by Doogie13** [comment]
> Turn off AirSpeedBoost it should work just fine.

I was mostly opening this to get airspeed to better bypass as other clients have done thins sucessfully.

**Comment by l1ving** [comment]
#1922
