### ISSUE TITLE
[feature] 2b2t QueuePeek

### ISSUE THREAD

**Issue by Xiaro** [kami-blue/client#1876]
Magical stuff to check who else is in queue and also detecting people leaving/joining queue with SPacketTeams from hause

**Comment by l1ving** [comment]
Maybe this could be implemented as part of #1101

**Comment by ElectroYModz** [comment]
no please it would get hause to patch it instantly

**Comment by Doogie13** [comment]
> no please it would get hause to patch it instantly

i mean 2b2t elytrafly lasted a while after it was discovered on kami blue

**Comment by ElectroYModz** [comment]
> > no please it would get hause to patch it instantly
> 
> i mean 2b2t elytrafly lasted a while after it was discovered on kami blue

he already is trying to patch it
it'll just help him

**Comment by ElectroYModz** [comment]
so it would be the worst fucking idea
