### ISSUE TITLE
Strafe option to start at max speed 

### ISSUE THREAD

**Issue by KMatias123** [kami-blue/client#1877]
**Is your feature request related to a problem? Please describe.**
you speed up slowly and need to sprint when using kami blue strafe

**Describe the solution you'd like**
there should be an option for the player to not need to hold sprint and to instantly be at max movement speed like in future

**Comment by l1ving** [comment]
#1922

**Comment by Xiaro** [comment]
> #1922

It is linked already

**Comment by l1ving** [comment]
mobile user moment
