### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by SKITLSE** [kami-blue/client#1893]
Could not resolve org.spongepowered:mixingradle:0.7-SNAPSHOT.
         > Unable to load Maven meta-data from http://repo.spongepowered.org/service/rest/repository/browse/maven-public/org/spongepowered/mixingradle/0.7-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'http://repo.spongepowered.org/service/rest/repository/browse/maven-public/org/spongepowered/mixingradle/0.7-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'http://repo.spongepowered.org/service/rest/repository/browse/maven-public/org/spongepowered/mixingradle/0.7-SNAPSHOT/maven-metadata.xml'. Received status code 520 from server: Origin Error
 Help i can't build mod kami blue

**Comment by l1ving** [comment]
Known. This isn't a KAMI Blue issue, use Gradle offline if you have it cached.
