### ISSUE TITLE
Fireworks should have a seprate option in NoRender

### ISSUE THREAD

**Issue by KMatias123** [kami-blue/client#1907]
**Is your feature request related to a problem? Please describe.**
when i have the projectiles option enabled in norender the module will cancel the firework spawn packet but also some other misc spawn packets that i would not want canceled like boats and minecarts

**Describe the solution you'd like**
an option for each entity (idk if this would be smart but i guess its the solution)

**Describe alternatives you've considered**
idk

**Additional context**
nothing

**Comment by Doogie13** [comment]
this might work better with commands considering the amount of options needed?
