### ISSUE TITLE
logout logger esp

### ISSUE THREAD

**Issue by bensonious** [kami-blue/client#1914]
**Is your feature request related to a problem? Please describe.**
it's annoying when someone logs out and it only appears in chat, and then u have to manually find the spot

**Describe the solution you'd like**
some sort of esp box where the player has logged out, makes it easier to trap logout, and other reasons you may want someone's logout spot, with coords/distance away from you

**Describe alternatives you've considered**
future, inertia

**Additional context**
the esp clears in different conditions(a button in module settings to clear, or delete the box when the player logs back in
![eqwumwg7yc731](https://user-images.githubusercontent.com/72408961/107125433-0853b580-6878-11eb-8d7e-08dd22db7cfa.jpg)
something similar to this
random image I found on the internet to show what I mean by esp box

**Comment by l1ving** [comment]
`;t waypointrender`
