### ISSUE TITLE
Xray is missing in version 2.02

### ISSUE THREAD

**Issue by m00nyONE** [kami-blue/client#1916]
**Describe the bug**
XRay is nowhere to be found in version 2.02
its not even in the configs anymore

**To Reproduce**
open up minecraft, get in the clickgui and see yourself

**Expected behavior**
Xray should be there

**Additional context / media**
i searched the changelogs but i found nothing

**Comment by l1ving** [comment]
This isn't a bug, it was removed temporarily. See #289

**Comment by scorbett123** [comment]
No it shouldn't, it has been "temporarily" removed, just use esp.
