### ISSUE TITLE
Crashing a ton

### ISSUE THREAD

**Issue by tlamorod** [kami-blue/client#1918]
**Describe the bug**

my game is crashing a lot.

**To Reproduce**

idk, just crashing

**Expected behavior**

not crashing every time I load up the game
**Debug info**

**Additional context / media**

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/kami-blue/client/issues/new?labels=bug%2C+-module&template=bug-report.md)
- [**Suggestion for a new feature**](https://github.com/kami-blue/client/issues/new?labels=enhancement%2C+-module&template=enhancement.md)
- [**Suggestion for an existing feature**](https://github.com/kami-blue/client/issues/new?labels=new%2C+-module&template=featurereq.md)
- [**Incompatiblity**](https://github.com/kami-blue/client/issues/new?labels=-incompatible&template=incompatiblity-report.md)
