### ISSUE TITLE
BlockHighlight

### ISSUE THREAD

**Issue by DontEatOreo** [kami-blue/client#195]
**Is your feature request related to a problem? Please describe.**
It draws an overlay around a block similar to pvp client badlion. 

It could be hole block overlay or the edge of the block overlay. Modes could be Rainbow, Chroma, solid color or breathing between 2-4 colors.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DontEatOreo** [comment]
Example: https://i.imgur.com/CJrd8N2.jpg

**Comment by S-B99** [comment]
Elementars was kind enough to give me this a while ago [KamiTesselator.java](https://cdn.discordapp.com/attachments/637846173025173514/655144236248989735/KamiTessellator.java) [(pastebin)](https://pastebin.com/raw/sLechgqj) if anyone would like to use part of it for this module

**Comment by dominikaaaa** [comment]
Closed by #1115
