### ISSUE TITLE
Offhandgapple like the old one

### ISSUE THREAD

**Issue by ZoomGC** [kami-blue/client#2085]
I find it to be frustrating when my totem and gapple automatically swap, so I was wondering if there's a way to keep a new version of Kami Blue while keeping something similar to the old offhandgapple where you would hold the right mouse button (usually with a weapon equipped) and it'd replace your totem with a gapple so you can eat, then upon letting go of the right mouse button it would switch back to the totem, placing the gapple back where it was originally

I have also considered moving to an older version but the changes made to the newer versions are ones i would desire to keep, so if there is a solution through configuring "Autoffhand" then that'd be great

Thank you so much for reading and thank you in advance for any solutions
-ZoomGC

**Comment by l1ving** [comment]
#1748 :neutral_face:

**Comment by Xiaro** [comment]
That one was a no already so what ever
