### ISSUE TITLE
[feature] Re-add Potion HUD

### ISSUE THREAD

**Issue by Xiaro** [kami-blue/client#2099]
With remaining time calculated based on tps, effect name, effect level.
And maybe icon?
![image](https://user-images.githubusercontent.com/62033805/109750224-0ac0db00-7baa-11eb-9f97-254f82124b7e.png)

Been realizing this for long time but always forgot the make an issue.

**Comment by l1ving** [comment]
It was mentioned in #1648 :moyai:
