### ISSUE TITLE
cant open options in clickgui unless you have scrolled

### ISSUE THREAD

**Issue by Doogie13** [kami-blue/client#2101]
**Describe the bug**
if you 

**To Reproduce**

1. Go to click gui'
2. right click on any module
3. Scroll in a pane
4. right click on any module

**Expected behavior**
Opens both times rather than only the second time

**Debug info**
nothing is missed off except the red message
![image](https://user-images.githubusercontent.com/62295632/109828460-8cf5e180-7c34-11eb-9b5b-c59039864f4a.png)

**Additional context / media**
clicc

**Comment by Xiaro** [comment]
#1855
