### ISSUE TITLE
Baritone does not work when running with multiple clients [Ares  2.7.4 + Kami Blue 1.12.05]

### ISSUE THREAD

**Issue by anonfoxer** [kami-blue/client#2116]
Whenever running Ares 2.7.4 and Kami-Blue 1.12.05 together (this is my first time actually running two util clients at once), Baritone refuses to work outright.

Both clients offer the same options for methods of controlling baritone, and I think this might be part of the problem. It could also just be because both clients have Baritone integrated. 
Regardless, all handlers for enabling baritone (;b, #, -b) do not work when running these clients together, regardless if any modules from either client are enabled or not.

**Comment by iBuyMountainDew** [comment]
We don't support old versions.
