### ISSUE TITLE
`;nbt copy` subcommand to copy to clipboard, instead of to value

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#2119]
Currently users assume that `;nbt copy` will copy to clipboard. Have the existing `;nbt copy` renamed to `;nbt copydata`, and add descriptions for the subcommands, so it is more intuitive.

**Comment by UltimateBoi** [comment]
Ok

**Comment by Xiaro** [comment]
Why not just make it only copy to clipboard and paste from clipboard

**Comment by l1ving** [comment]
4372fdc319d8e3d1494db5e8e47e0cb9d85005e0 added `;nbt`, I'm not quite sure when it was changed to not copy to clipboard but it was originally clipboard lol. So yea, making it copy and paste from clipboard sounds fun, just maybe add a validation string at the beginning of the copy like `NBT DATA` to make sure the user can't paste invalid data
