### ISSUE TITLE
Error whilst installing

### ISSUE THREAD

**Issue by virronn** [kami-blue/client#2128]
so I have installed kami. And when I load it up it says Baritoe is only supported on 1.13 would this be because I have inertia installed? 
![kami](https://user-images.githubusercontent.com/80702756/111179805-5315cb00-85a4-11eb-8996-a1b50f4b8375.PNG)

**Comment by l1ving** [comment]
Most likely, yes. This is not what the issue tracker is for, ask for help on the discord.
