### ISSUE TITLE
AutoLog doesn't work with Autoreconnect

### ISSUE THREAD

**Issue by Potterfanz** [kami-blue/client#2130]
![2021-03-16_04 55 21](https://user-images.githubusercontent.com/34488308/111290777-decb3e00-861c-11eb-97d2-3c72a3f2a012.png)
![2021-03-16_04 56 10](https://user-images.githubusercontent.com/34488308/111290778-df63d480-861c-11eb-90b5-d777570b2df4.png)

**Comment by Potterfanz** [comment]
this was with disable mode set to Not Player. disable mode on never doesn't change that.

**Comment by scorbett123** [comment]
What do you want it to do, if auto disconnect happens it won't auto reconnect?
