### ISSUE TITLE
Please remove all references to the popular indie game known as "Among Us!"

### ISSUE THREAD

**Issue by kars0nn** [kami-blue/client#2137]
this is making the mod un-playable. i need this fixed immediately
![Screenshot 2021-03-19 164046](https://user-images.githubusercontent.com/64934094/111839998-16aedb80-88d2-11eb-8d67-597e3d412bf6.png)
![Screenshot 2021-03-19 164033](https://user-images.githubusercontent.com/64934094/111840012-1ca4bc80-88d2-11eb-8342-930f055ad1fc.png)

**Comment by l1ving** [comment]
le funny

**Comment by d1snin** [comment]
sus
