### ISSUE TITLE
kami-blue tag

### ISSUE THREAD

**Issue by d1snin** [kami-blue/client#2142]
can you add `kami-blue` to tags just because
![2021-03-20_23-59_1](https://user-images.githubusercontent.com/68169685/111885371-65469d80-89d8-11eb-9aed-40f128f32014.png)
![2021-03-20_23-59](https://user-images.githubusercontent.com/68169685/111885373-6677ca80-89d8-11eb-94ff-47c4b20881ed.png)

**Comment by l1ving** [comment]
Thanks
