### ISSUE TITLE
enh: Option to sync baritone waypoints with KAMI blue waypoints.

### ISSUE THREAD

**Issue by scorbett123** [kami-blue/client#2148]
idk why not.

**Comment by l1ving** [comment]
does the baritone API even expose access to them?

**Comment by l1ving** [comment]
Also, how would this work? It'd need to be optional somewhere otherwise the user would be annoyed by the waypoints that baritone makes automatically

**Comment by scorbett123** [comment]
Maybe just a button in the waypoints module like the default button, just to sync them all. Will check whether you can access them now.

**Comment by scorbett123** [comment]
Yes baritone api does expose them,
```
BaritoneAPI.getBaritoneProvider().getPrimaryBaritone().getWorldProvider().getCurrentWorld().getAllWaypoints().getAllWaypoints()
```

returns a set of the waypoints

**Comment by scorbett123** [comment]
Wait, is there not a waypoint module? can you just manage them through commands?

**Comment by l1ving** [comment]
It's only via commands
