### ISSUE TITLE
Custom AutoReply message for AntiAFK

### ISSUE THREAD

**Issue by Doogie13** [kami-blue/client#2166]
**Is your feature request related to a problem? Please describe.**
The current message is non customisable

**Describe the solution you'd like**
Make AntiAFK AutoReply have a customizable message 

**Describe alternatives you've considered**
using my keyboard and mouse to type "/r [message]" whilst afk somehow idk

**Additional context**
i might try to add this myself at some point idk

**Comment by scorbett123** [comment]
Closed by #2168
