### ISSUE TITLE
Inability to scroll before interacting with window after interacting with another window

### ISSUE THREAD

**Issue by scorbett123** [kami-blue/client#2183]
**Describe the bug**
You can't scroll just after opening a window after you have just interacted with another window.

**To Reproduce**

1. Open ClickGUI - you can scroll like usual.
2. Open the HudEditor - you can scroll like usual.
3. Reopen the ClickGui, DON'T click on the screen. - you can't scroll.

**Expected behavior**
That you can scroll after opening a window when the focus has previously been pulled off of it.

**Comment by l1ving** [comment]
It used to be the other way around, you couldn't click until you had scrolled :pensive:
