### ISSUE TITLE
Setting up the workspace gives a very long and strange error

### ISSUE THREAD

**Issue by LucaForever** [kami-blue/client#2199]
**Describe the bug**
When I am trying to download the source code and "./scripts/setupWorkspace.sh", it gives me this strange error.
https://pastebin.com/1PvKQWmY               (posted on pastebin because its too long)

**To Reproduce**
I followed the steps on the website (https://kamiblue.org/contributing) and when I used the setupWorkspace.sh, it gives me that error.

**Additional context / media**
https://pastebin.com/1PvKQWmY

**Comment by l1ving** [comment]
> java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7

That really doesn't look right lol.

Send the output of `java -version`

**Comment by LucaForever** [comment]
> java -version

![image](https://user-images.githubusercontent.com/58527636/114926908-9086a600-9e39-11eb-9b2a-16ff7e7080c3.png)

**Comment by l1ving** [comment]
You have to use JDK 8 as per the contributing instructions, just set the JAVA_HOME variable to your JDK 8 path and clear your Gradle caches as per the instructions

**Comment by LucaForever** [comment]
> 
> 
> You have to use JDK 8 as per the contributing instructions, just set the JAVA_HOME variable to your JDK 8 path and clear your Gradle caches as per the instructions

ok thanks, ill close this issue when i see it works

**Comment by LucaForever** [comment]
is this normal?
`[0;1m-------------> 0% EXECUTING [1m 31s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 32s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 33s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 34s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 35s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 36s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 37s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 38s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 39s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 40s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 41s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 42s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 43s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 44s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 45s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 46s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 47s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 48s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 49s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 50s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 51s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 52s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 53s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 54s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 55s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 56s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 57s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 58s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [1m 59s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 0s]←[m←[0K←[36D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 1s]←[m←[36D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 2s]←[m←[36D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 3s]←[m←[36D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 4s]←[m←[36D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 5s]←[m←[36D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 6s]←[m←[36D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 7s]←[m←[36D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 8s]←[m←[36D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 9s]←[m←[36D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 10s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 11s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 12s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 13s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING [2m 14s]←[m←[37D←[5B←[5A←[1m<←[0;1m-------------> 0% EXECUTING`

**Comment by l1ving** [comment]
It could take a while after clearing the caches

**Comment by l1ving** [comment]
Though I'd recommend not pasting straight terminal output as it looks like cygwin messes with the ANSI escape characters and displays garbage when copying it

**Comment by LucaForever** [comment]
> 
> 
> Though I'd recommend not pasting straight terminal output as it looks like cygwin messes with the ANSI escape characters and displays garbage when copying it

well it shows like that in the terminal too, it just looks nicer here because its spaced and with linebreaks

**Comment by LucaForever** [comment]
and it worked. thanks! fast help btw
