### ISSUE TITLE
AutoMend

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#242]

**Comment by Vonr** [comment]
done in https://github.com/S-B99/KAMI/commits/feature/autoexp-improvements a long time ago

**Comment by pol-y-mer** [comment]
I'd love to enhance/implement this if it's not done already :)

**Comment by Vonr** [comment]
its broken or something so go test for bella and report to her in discord thanksss

**Comment by S-B99** [comment]
this is aaaa supposed to be done

**Comment by S-B99** [comment]
all you need to do is checkout the branch and test

**Comment by S-B99** [comment]
@Vonr it works, but if you lose a piece of armour it breaks, says it crashes at the divide, because there is no stack.getitemdamage, because there is no item. It ignores the itemstack empty check, meaning the method that runs it needs to check if it's not empty
