### ISSUE TITLE
Fix bug with tooltips

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#243]
Currently isHovered is active outside of the visible window

Expand GUI boxes to be tall and scroll the entire screen instead, like future does it

Line 77 in KamiGUI, but you need a scroll impl

**Comment by S-B99** [comment]
Implemented fixgui

**Comment by dominikaaaa** [comment]
Reopening this as a way to fix a dumb bug caused by #78

**Comment by dominikaaaa** [comment]
Closing this as won't fix as I found a workaround.
