### ISSUE TITLE
Jar installer

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#271]
Because people don't read the readme for some reason

**Comment by zeroeightysix** [comment]
Why not have an actual installer instead of install instructions?

**Comment by S-B99** [comment]
That's a better idea honestly.

**Comment by d1gress** [comment]
the only way i can think of doing this is using git to download the source, build it with jdk, then send the last modified file in /libs/builds with "release" in its name to the mods folder but im stupid so i probably overcomplicated about 193 things

**Comment by S-B99** [comment]
No, it can literally copy forges updater.

I added it in release v1.1.1 but making a separate program to automatically get the url and download it is what the issue is for

**Comment by S-B99** [comment]
Currently there's an installer branch which demonstrates how to keep it a forge mod but also have the jar do something when opened. I doubt I'll ever get around to it, so I'm probably going to close this as won't fix. I'll comment the important code here before I delete the branch.

**Comment by S-B99** [comment]
Alright, so it all goes in `build.gradle`.

Move your buildscript to the top, as this requires it. 

After build: dependson(shadowjar) add this

```java
void application() {
    mainClassName = 'wtf.bella.installer.Main'
} 
```

And you can make that class do something

```java
package wtf.bella.installer;

public class Main {
    public static void main(String[] args) {
        System.out.println("ran installer!!!");
    }
}
```

**Comment by cookiedragon234** [comment]
😯

**Comment by humboldt123** [comment]
now this is podracing

**Comment by humboldt123** [comment]
Alrighty. I'm *thinking* of doing this in Python.

**Comment by dominikaaaa** [comment]
why the fuck.

**Comment by dominikaaaa** [comment]
![image](https://user-images.githubusercontent.com/17222512/87557069-77bc4a80-c685-11ea-9599-bbf702a55b65.png)
Kinda pog

Automatically deletes older versions of KAMI and KAMI Blue on confirmation and warns if you don't have Forge installed
