### ISSUE TITLE
Xray

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#289]
Reopening, Xray got removed in #1510

Maybe with an opacity option as well, suggested in #964

**Comment by S-B99** [comment]
// TODO: 
- [ ] fix resources references
- [ ] change to proper warnings
- [ ] fix help menu

**Comment by S-B99** [comment]
Only pending testing now.

**Comment by S-B99** [comment]
... and I need to change my folder name. Oof.

**Comment by l1ving** [comment]
Reopening, Xray got removed in #1510
