### ISSUE TITLE
Change RPC lib

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#307]
Missing library, idk where to get it

Screm someone help

**Comment by EmotionalLove** [comment]
I'll get to this (someday)

**Comment by cdantetho** [comment]
I believe you need the /darwin/ folder in this repo to fix this issue: https://github.com/MinnDevelopment/discord-rpc-release/tree/master/src/main/resources.

When I launched on OSX, minecraft console threw errors complaining about a lack of `libdiscord-rpc.dylib` in `/darwin/`. Hopefully this discord-rpc resource will help!

**Comment by S-B99** [comment]
it fix but sasha wanted to switch the rpc system i think
if not she can close

**Comment by S-B99** [comment]
Suggesting https://github.com/jagrosh/DiscordIPC

**Comment by S-B99** [comment]
Seeing as this project isn't planned to be very active anymore I'm going to close this as won't fix, unless Sasha wants to self assign this later.

**Comment by dominikaaaa** [comment]
Actually, Nuker found a decent library which looks way cleaner and more performance efficient, I'm switching to that. [Vatuu/discord-rpc](https://github.com/Vatuu/discord-rpc)

**Comment by iBuyMountainDew** [comment]
To quote the developers of this proposed library:

"Currently supported OSs include Windows x86, Windows x64 and Unix x64. OSX and macOS support is currently broken, although we're working hard on getting it to work again."

I don't think we should be switching until OSX support for this library is fixed.

**Comment by dominikaaaa** [comment]
Oh that's true. I'll close this as won't fix for the time being then.
