### ISSUE TITLE
Move configuration files to their own `kamiblue` folder

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#310]
In case there will be more configuration in the future and for cleanliness

**Comment by dominikaaaa** [comment]
> In case there will be more configuration in the future and for cleanliness

Now there are a lot of configuration files, eg KAMIBlueMacros and KAMIBlueWaypoints, + spammer and all of those module ones. With #1227 implementing autosaving this should be kept in mind.

**Comment by Xiaro** [comment]
What about backward compatibility? Do we just remove the old configs and move them to KamiBlue folder?

**Comment by dominikaaaa** [comment]
Yes, the same way Waypoints do it. Currently they'll try to look for `KAMIBlueMacros.json` and if it exists, read that file and delete that file, and it'll only ever save inside `KAMIBlueWaypoints.json`

**Comment by Xiaro** [comment]
closed in #1512

**Comment by l1ving** [comment]
Macros, waypoints and friends are not moved. I would like to reopen this and add backwards compat to move the files when updating
