### ISSUE TITLE
Custom GUI colors

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#32]
title

**Comment by S-B99** [comment]
Also have options for custom colors or rgb

**Comment by S-B99** [comment]
This needs so much more work then I thought, gonna take a bit

**Comment by S-B99** [comment]
For reference
https://github.com/S-B99/KAMI/pull/37#discussion_r352232176

**Comment by S-B99** [comment]
Waiting for #392 and and #36

**Comment by S-B99** [comment]
https://github.com/S-B99/kamiblue/blob/feature/master/src/main/java/me/zeroeightsix/kami/gui/kami/RenderHelper.java#L57

**Comment by dominikaaaa** [comment]
See #790.
