### ISSUE TITLE
Elytra Replace 

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#355]
- [x] Replace elytra when it breaks 
- [x] automatically switch elytra based on if elytraflight is enabled and `mc.player.onGround`

~~Right click to replace it~~ < dumb idea, although possible

**Comment by d1gress** [comment]
how the hell do you plan on hooking into right click?

**Comment by d1gress** [comment]
actually you could probably mixins into whatever lets you equip it in the first place then do whatever you need

**Comment by S-B99** [comment]
Use item on block?

**Comment by d1gress** [comment]
probably not but if you see something related to armor it might be

**Comment by S-B99** [comment]
No there's a function use item on block

**Comment by iBuyMountainDew** [comment]
done, albeit not very elegantly.
