### ISSUE TITLE
Custom ChatFilter

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#387]

**Comment by Vonr** [comment]
mixin into chat gui or something then remove ir replace any words that are swear words. make new command to customize list.

**Comment by S-B99** [comment]
I haven't been able to figure out customizing and storing something since #11 and this https://github.com/zeroeightysix/KAMI/pull/161. But otherwise the rest I can do

**Comment by S-B99** [comment]
// TODO: make antispam into a method i can reuse
