### ISSUE TITLE
Move GUI category to proper settings

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#392]
For anyone who's interested in what this entails: there is an example settings board in KamiGUI called Info2

I'd like to move stuff in the Client Module category to there 

Adjusting things such as tab height would be nice as well

TextRadar max players (eg only show 2)

**Comment by S-B99** [comment]
Also make ArmourHUD a draggable module

**Comment by dominikaaaa** [comment]
See #790.
