### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by Vonr** [kami-blue/client#421]
**Is your feature request related to a problem? Please describe.**
I need to learn kotlin

**Describe the solution you'd like**
rebase old stuff to /source/main/java/me/zeroeightsix/kami/java
new kotlin folder in /source/main/java/me/zeroeightsix/kami/kotlin
add dependencies to build.gradle

**Describe alternatives you've considered**
death

**Additional context**
kotlin is apparently cool now
- [x] chat
- [x] client
- [x] combat
- [x] misc
- [x] movement 
- [x] player
- [x] render

**Comment by S-B99** [comment]
> rebase old stuff to /source/main/java/me/zeroeightsix/kami/java
> new kotlin folder in /source/main/java/me/zeroeightsix/kami/kotlin

shouldn't this be
```diff
= /source/main/java/me/zeroeightsix/kami/
+ /source/main/kotlin/me/zeroeightsix/kami/
```

**Comment by S-B99** [comment]
Blocked bc I need to learn kotlin. Also this is probably only happening for 1.14 unless someone else wants to do it

**Comment by Vonr** [comment]
firstly yes secondly yeah 1.14 is fine

**Comment by S-B99** [comment]
Then closing until I make 1.12 inactive (when 2b updates).

**Comment by dominikaaaa** [comment]
Reopening as this is now in progress.

**Comment by Vonr** [comment]
ffs

**Comment by dominikaaaa** [comment]
look i did it!!
