### ISSUE TITLE
StashFinder

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#430]
Decided to not do this with baritone

Log amount of each of these in a chunk
- [ ] chests 
- [ ] shulkers
- [ ] donkeys 

logger util added by #698

### ignore the rest of this issue, that's an old discussion

~~See the discussion here: https://github.com/ImpactDevelopment/ImpactIssues/issues/1951~~

~~Turns out #explore caches explored chunks and saves chests, with no easy way to export them. You can use the coord logger to instead log these and then use the module to interact with the barjtone API for exploring.~~

**Comment by freddiethemadlad** [comment]
Man I really want this on kami

**Comment by S-B99** [comment]
There is no reason to comment on random issues that you want it added.
