### ISSUE TITLE
Freecam rewrite and support Baritone

### ISSUE THREAD

**Issue by TobSick** [kami-blue/client#530]
**What mod?**
Baritone

**Issue**
Can't go into freecam while baritone or elytraflight is active.

**Planned** 
- [ ] rewrite
- [ ] baritone support
- [ ] vanilla creative speed 

Apparently you can mixin into the player camera and gltranslate it

**Comment by S-B99** [comment]
This is impossible to fix as baritone is not integrated.

**Comment by mothheart** [comment]
Does the code referenced from forgehax still work?

**Comment by dominikaaaa** [comment]
Forgehax freecam is not compatible, I was commenting on the idea of loading chunks in freecam. After some testing, it turns out that was completely placebo and it's impossible to do so without moving the original player (ofc).

**Comment by mothheart** [comment]
Would freecam support for baritone require an extensive rewrite? From what I recall wurst currently supports using freecam with baritone, it could be used as a base. I'm not sure about the Wurst part, I'll do some testing tonight and if I'm wrong I'll edit this comment.

**Comment by dominikaaaa** [comment]
I'd rather write a new one from scratch.

**Comment by dominikaaaa** [comment]
I'm a dumbo

https://github.com/ImpactDevelopment/ImpactIssues/issues/912

This actually explains how it works. I might get around to this then lmao

**Comment by GoodPro712** [comment]
Is it possible to show your own armor and items in the nametags when you freecam and look at yourself

**Comment by dominikaaaa** [comment]
Nametags already has that option
