### ISSUE TITLE
Disconnect confirm 

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#575]

**Comment by cookiedragon234** [comment]
Suggestion:

When the disconnect button is clicked change the text to "Are you sure?" and a second click will be required to finally disconnect.

Implementation (pseudocode):
```
boolean disconnecting = false;

fun onAttemptDisconnect() {
	if (disconnecting) {
		// peform disconnect logic
	} else {
		disconnecting = true
		disconnectingBtn.text = "Are you sure?"
	}
}
```

**Comment by S-B99** [comment]
That's literally what this issue is for, but I couldn't be asked to put a description

**Comment by cookiedragon234** [comment]
Oh I know, I was just trying to provide a concept of how to implement it

**Comment by S-B99** [comment]
thanks <3

**Comment by S-B99** [comment]
I just realised that's kotlin smh

**Comment by cookiedragon234** [comment]
Kotlin influenced pseudocode

**Comment by IronException** [comment]
https://www.youtube.com/watch?v=fASfSWqdr0A Here is more concept of how to implement it.

**Comment by iBuyMountainDew** [comment]
Done. 

See https://github.com/kami-blue/client/commit/8ebc53438c2427a785a204e4a8437df50224feda

**Comment by dominikaaaa** [comment]
Added in 8ebc53438c2427a785a204e4a8437df50224feda

**Comment by dominikaaaa** [comment]
god damnit i was about to do it

**Comment by iBuyMountainDew** [comment]
lmao
