### ISSUE TITLE
Update checker

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#587]
- [x] have server check what is latest commit 
- [x] remove the forge version checker (it doesn't work with the versioning system I use, and it's not that visible that the mod needs updating)

- [x] show current + new version on main menu 
  - [x] maybe have dates of each / commit difference?

**Comment by iBuyMountainDew** [comment]
It may not go by commit, but we really won't be needing that.
Version on the main menu could be added later as an enhancement, it's not crucial considering the Mods menu exists.
