### ISSUE TITLE
Use a consistent coding style and refactor existing code to fit it

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#588]
Todo
- [x] exclude idea formatting settings from gitignore 

To consider
- [x] 4 tab indentation with spaces
- [x] space before and after () 
- [x] break up annotations (eg module annotations)

**Comment by Tigermouthbear** [comment]
why don't you just auto refactor with intellij?

**Comment by S-B99** [comment]
I'd prefer a universal customizable solution.

**Comment by Tigermouthbear** [comment]
you can customize the code style in intellij. Just go to Settings > Editor > Code Style > Java. Then when you auto refactor it'll match those settings

**Comment by S-B99** [comment]
Is there a way to enforce this repo-wide, so when other people clone their editor also uses that style?

**Comment by Tigermouthbear** [comment]
The settings are stored in the .idea folder

**Comment by S-B99** [comment]
Thanks, I'll use that instead.

**Comment by cookiedragon234** [comment]
But dont commit the entire folder lol

**Comment by S-B99** [comment]
That's why i just edited the issue description xd

**Comment by S-B99** [comment]
Waiting for aura, xp and baritone branches to be merged.

**Comment by S-B99** [comment]
Almost ready, waiting for #242 and it's branch to merge and then I'm going to do this

**Comment by dominikaaaa** [comment]
There are now no other branchs so I'm waiting for Dew to push local before I do.
