### ISSUE TITLE
ElytraFlight improvements 

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#616]
- [x] send packet to open wings
- [x] Boost mode disable when at the magic pitch 
- [x] Highway mode slowed descend / ascend
- [x] Automatically disable when lagging back (ie stuck in a block) (this might not be possible honestly, the only way I can think of doing this is by having it disable when speed is less then 10km/h but then people can't stop while flying) (won't fix)
- [x] speed limit for boost mode (#665)
- [x] Automatically stop in new chunks (see #665, separate module)
- [x] Slow mode for taking off (won't fix, use timer slow mode, and takeoff was added)
- [x] fix easy takeoff
- [x] test on 2b2t

**Comment by Vonr** [comment]
for point 4 you could make a ghetto workaround by logging positions of current and last 2 ticks.
oldest tick position == current tick position =/= older tick position

**Comment by Vonr** [comment]
speed limit should be possible but i dont exactly see a reason for implementation

**Comment by dominikaaaa** [comment]
Someone wanted a speed limit because they go too fast on some servers 

Boost technically goes as fast as you want, up to 1k km/h from my testing

**Comment by Vonr** [comment]
point 3 could probably be done using a basic tick timer

**Comment by dominikaaaa** [comment]
I already did it on local

**Comment by iBuyMountainDew** [comment]
let's gooooo
