### ISSUE TITLE
crystalaura with autotool on switches to sword

### ISSUE THREAD

**Issue by epicfacethe3rd** [kami-blue/client#654]
**Is your feature request related to a problem? Please describe.**
when crystalaura and autotool is on, AT will automatically swap to the sword, stopping you from using tools to mine or place blocks. this can cause you to be unable to dig your way out of an autotrap or expose another player's foot level

**Describe the solution you'd like**
cause autotool to not swap to the sword when using CA (antiweakness will do this if you're hit with a weakness potion)

**Describe alternatives you've considered**
yes, you can turn off autotool, but it's a nice convenience to not have to select your tool when digging

**Additional context**
can i pwease code it myself and push it ;-;

**Comment by dominikaaaa** [comment]
You mean like, crystalaura with autotool enabled tries to break the crystal with a sword when antiweakness *isn't* enabled? Because crystalaura has a no tool break option :p

**Comment by epicfacethe3rd** [comment]
yes, autotool causes you to swap to the sword when hitting a crystal regardless of if you have weakness or not
antiweakness only causes you to use the sword when you have weakness

**Comment by dominikaaaa** [comment]
Well, autotool is doing that because it breaks the crystal faster

**Comment by epicfacethe3rd** [comment]
i'll test that real quick, but the minecraft wiki indicates otherwise. regardless the ability to use tools while in PVP is a pretty big deal, even if you can't break crystals while you're doing it
would coding a way to temporarily disable CA while using a pick be a better idea?

**Comment by dominikaaaa** [comment]
That's what no tool break does :p

Also it's using Minecraft math for if it's faster or not, not anything that I coded.

**Comment by epicfacethe3rd** [comment]
i think i need to read over CA again lol
