### ISSUE TITLE
AntiOverlay

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#655]
Prevents the rendering of stuff such as totem pops, nausea, blindness, nether portal's overlay.

**Comment by iBuyMountainDew** [comment]
Done. https://github.com/kami-blue/client/commit/ac01e6fc97e9c93158c79a8b4e364892ed37ebcc

**Comment by dominikaaaa** [comment]
What about the feature's what were actually suggested in the issue? I assume blocks is the nether portal, in which case it should be renamed and the rest aren't added?

**Comment by dominikaaaa** [comment]
Reopening this until the first 3 are added

**Comment by dominikaaaa** [comment]
Done in cc8eb34d4d249051c05a532a09aa9d445915e2ef and ce660d0b7a7fb16be2f2c866786a8cf7ef639a96
