### ISSUE TITLE
Surround Causing Client Rotation to go crazy

### ISSUE THREAD

**Issue by sylaxofficial** [kami-blue/client#657]
**Describe the bug**
When using surround, in certain situations, it makes the camera go in all different directions.

**To Reproduce**
1. Toggle Surround
2. Use surround while moving
3. >>

**Expected behavior**
Player rotation is not server sided only, changes clients,

**Screenshots**

**Additional context**

**Comment by dominikaaaa** [comment]
I can't reproduce this, it works fine for me.

**Comment by sylaxofficial** [comment]
I will try to find the source of the problem.

**Comment by sylaxofficial** [comment]
Use surround while walking

**Comment by dominikaaaa** [comment]
Ah. Well then enable spoof rotations.
