### ISSUE TITLE
Fast Surround

### ISSUE THREAD

**Issue by sylaxofficial** [kami-blue/client#658]
**Is your feature request related to a problem? Please describe.**
The surround in kami blue is pretty slow compared to other clients, and it is hard to surround while someone is using crystal aura because of this. 

**Describe the solution you'd like**
Some optimizations in the placement speed so that the player can avoid getting chain popped

**Describe alternatives you've considered**
Look at osiris' surround without spoof rotations

**Additional context**
_gg_

**Comment by sylaxofficial** [comment]
This is the same with auto center off.

**Comment by dominikaaaa** [comment]
Try AutoFeetPlace, which should continually place. Currently surround doesn't have any delays in place when placing except for the user-set ones, which you can configure in Surround's settings / AutoFeetPlace's settings

**Comment by sylaxofficial** [comment]
your modules are very confusing 🤔
