### ISSUE TITLE
Add EXP, GAP and TOTEM counters to gui

### ISSUE THREAD

**Issue by sylaxofficial** [kami-blue/client#659]
**Is your feature request related to a problem? Please describe.**
Add a counter for the three items so the player can instantly know how many they have. Stack ("4 stacks") or single (256) settings.

**Describe the solution you'd like**
The modules added to gui

**Comment by dominikaaaa** [comment]
This is already a thing in the InfoOverlay options

**Comment by sylaxofficial** [comment]
It is a bit hidden, and also the placements are locked with the other info overlays :~0

**Comment by dominikaaaa** [comment]
Wdym placements?

**Comment by dominikaaaa** [comment]
And there isn't any other way to make it more visible, as the Info settings are under the InfoOverlay module, but it is on a different page because there's too many settings under it.

**Comment by sylaxofficial** [comment]
it is attached to the info overlay, it would be better as a seperate overlay element

**Comment by sylaxofficial** [comment]
it is attached to the info overlay, it would be better as a seperate overlay element

**Comment by dominikaaaa** [comment]
I'd rather not because that clutters up the already cluttered UI. I wish there was a better solution, maybe when I implement #437
