### ISSUE TITLE
A bar showing health as gui option, showing how much damage can be dealt by sword, changing colour, predicting when you need to gap

### ISSUE THREAD

**Issue by sylaxofficial** [kami-blue/client#660]
**Is your feature request related to a problem? Please describe.**
It would be helpful to know when the right time is to eat a gapple when you are in a sword fight, because otherwise it can be easy to eat too early or too late.

**Describe the solution you'd like**
A togglable bar or change of heart color.

**Describe alternatives you've considered**
no other client has this

**Additional context**

**Comment by dominikaaaa** [comment]
The damage dealt by the sword is the same each time if you have delay mode in Aura turned on...

**Comment by dominikaaaa** [comment]
Unless you mean changing the color of health in nametags based on health?

**Comment by sylaxofficial** [comment]
Im saying the color of the health bar would change when you need to gap (predicts sword aura damage to totem pop)

**Comment by sylaxofficial** [comment]
or a gui health bar

**Comment by dominikaaaa** [comment]
Ah, well 'predicting' it based on what other players are doing is too unpredictable, ironically. I've tried doing this in the past and it wouldn't be feasible without a *huge* dataset and loads of computing power, which I don't think anyone would expend on a block game mod

**Comment by sylaxofficial** [comment]
??? Calculate damage by one sword hit then tps sync to see how often they hit then check tps to predict how long gap takes to eat put it all into one big calculation and put it in there ;)

**Comment by dominikaaaa** [comment]
Yes, the seeing how often they hit is extremely unpredictable without a large dataset.

**Comment by sylaxofficial** [comment]
Discover average gapple eat time based on tps times

Use those times with current tps to calculate average time to gap

Use tpssync to check how often they can hit you

Find out how much damage is dealt with a maxed sword


use the dmg/sec (for example 2 hearts / second)
x
then 2.5 seconds to eat gap

5 hp away

+1 or 0.5 heart for safety

5.5 hp away gap alert

**Comment by sylaxofficial** [comment]
I thought tpssync was a thing :|

**Comment by dominikaaaa** [comment]
Tps Sync can't "check how often they hit you", and as I said reliably predicting when they're going to hit you is practically impossible in real time. If I added it people would just shit on it and call it a cheap gimmick, as yes, it wouldn't be reliable.

**Comment by dominikaaaa** [comment]
As for how long actions take, you can just do `(20.0 / current tpsInTicks) * timeToDoAction)`, that part isn't difficult and you shouldn't measure it manually.
