### ISSUE TITLE
Multi Directional running

### ISSUE THREAD

**Issue by sylaxofficial** [kami-blue/client#661]
**Is your feature request related to a problem? Please describe.**
Add a feature where the client spoofs directions so that when the user is walking and not interacting with any blocks, that they can run backwards and in any direction.

**Describe the solution you'd like**
The client makes the server think the user is facing where they are going, when the user sees where they want.

**Describe alternatives you've considered**
bhop (but this isnt the same)

**Comment by dominikaaaa** [comment]
Duplicate of #633, as that's what #633 does

**Comment by sylaxofficial** [comment]
ok
