### ISSUE TITLE
Tracer Norender around crosshair diameter option

### ISSUE THREAD

**Issue by sylaxofficial** [kami-blue/client#675]
**Is your feature request related to a problem? Please describe.**
An option to not render the part of the tracer that is within a certain diameter from the crosshair. Increases visibility if there are a lot of tracers at once.

**Describe the solution you'd like**
A module option

**Comment by dominikaaaa** [comment]
You mean like, don't render tracers all the way to the crosshair?

**Comment by sylaxofficial** [comment]
like around the crosshair in -- diameter, the tracers dont render

**Comment by dominikaaaa** [comment]
Then that's not really possible as I don't want to calculate angles *and* radius to figure out where to stop rendering, sorry

**Comment by sylaxofficial** [comment]
BaD dEvElOpEr

**Comment by sylaxofficial** [comment]
but fr once I learn java I will try to make something like what I suggested
