### ISSUE TITLE
Implement Gui Scaling

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#68]
Temp solution: make your Minecraft GUI smaller

**Comment by S-B99** [comment]
//TODO

code in Gui class has a warning that checks for the minecraft gui size

**Comment by zeroeightysix** [comment]
The entirety of the GUI is scaled by the factor given by `DisplayGuiScreen`'s `getScale`: https://github.com/S-B99/KAMI/blob/da2ff767f9cff6fc0dcb635460ac966508e4057e/src/main/java/me/zeroeightsix/kami/gui/kami/DisplayGuiScreen.java#L104

**Comment by S-B99** [comment]
Someone suggested a seperate scale for right click menu, I don't think it's possible but having a scale in settings is

**Comment by S-B99** [comment]
I actually reverted that commit so uh oops

**Comment by Tigermouthbear** [comment]
You might be able to gl scale everything down to fit the scaled resolution before rendering

**Comment by S-B99** [comment]
no clue where it starts to render though

**Comment by S-B99** [comment]
To scale the rendered GUI elements (with the exception of my hacky inventory viewer, which I can change), you can add
```java
GlStateManager.scale(0.5f, 0.5f, 0.5f);
```
to UIRenderer.java
![2020-03-20-155322_360x471_scrot](https://user-images.githubusercontent.com/17222512/77201496-f384fc80-6ac2-11ea-8b19-75d786032b13.png)

**Comment by S-B99** [comment]
I didn't get much further then above, because the inside of ui frames seems to scale the text and box seperately and it completely breaks, and I couldn't figure out where those are rendered

**Comment by S-B99** [comment]
For now, I can check it the x of the frame is greater then the x of the window, and it so move it negative x

**Comment by S-B99** [comment]
In addition to that, [AbstractContainer.java#L39](https://github.com/S-B99/kamiblue/blob/feature/master/src/main/java/me/zeroeightsix/kami/gui/rgui/component/container/AbstractContainer.java#L39) calls this method [KamiFrameUI.java#L185](https://github.com/S-B99/kamiblue/blob/feature/master/src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiFrameUI.java#L185) which is used to determine where to place them, so I can also fix that to not put them off screen by default.

**Comment by S-B99** [comment]
For now, Gui elements **cannot** go off screen no matter what. Hopefully I'll get around to making a GUI scale someday.

**Comment by dominikaaaa** [comment]
As I've gotten better at GL since last commenting on this, you just push matrix, scale, and pop. The hard part is putting it into everything that renders.

**Comment by dominikaaaa** [comment]
Oops didn't mean to close

**Comment by dominikaaaa** [comment]
Moving this to later because after adding scaling (some stuff worked) as it turns out all the spacing and everything is hardcoded, oops

**Comment by dominikaaaa** [comment]
See #790.
