### ISSUE TITLE
Game crashing on start

### ISSUE THREAD

**Issue by pNoName1337** [kami-blue/client#682]
**Describe the bug**
Game crashing on start

**Game log**
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from KAMI Blue

**Additional context**
I'm using KAMI, Future, ForgeHax and Baritone API 2.1.13
It wasnt crashing before I updated it to "eae2721 commit" version

**Comment by dominikaaaa** [comment]
Provide the log file please.

**Comment by pNoName1337** [comment]
[KAMIZIP.zip](https://github.com/kami-blue/client/files/4464989/KAMIZIP.zip)
Here it is

**Comment by pNoName1337** [comment]
I see a newer version in discord, I will try to use it and check if it crash or not

**Comment by pNoName1337** [comment]
2ca21de commit crashes too

**Comment by dominikaaaa** [comment]
Your crash is with forgehax, not kami blue.

**Comment by pNoName1337** [comment]
okay then, do you have any opinion how to fix it? i use a lot of modules from forgehax

**Comment by dominikaaaa** [comment]
Ask in the forgehax repo

**Comment by pNoName1337** [comment]
It's crashing even without forgehax

**Comment by pNoName1337** [comment]
[logs.zip](https://github.com/kami-blue/client/files/4465004/logs.zip)
here's the logs

**Comment by dominikaaaa** [comment]
You need to wait for a new download then, I fixed this but Travis was offline

**Comment by pNoName1337** [comment]
Okay, thanks

**Comment by dominikaaaa** [comment]
Just checked, has to be 59ad632 or newer

**Comment by pNoName1337** [comment]
Now it works, thanks!
