### ISSUE TITLE
ChatTimestamps doesnt support colored text

### ISSUE THREAD

**Issue by pNoName1337** [kami-blue/client#683]
So when I enable timestamps all colored text become white
Enabled:
![image](https://user-images.githubusercontent.com/54634728/79050714-8b928380-7c34-11ea-92ff-55c5ad8a59d9.png)
Disabled:
![image](https://user-images.githubusercontent.com/54634728/79050721-9c42f980-7c34-11ea-8c52-30adbf2063b2.png)
Possible solution: dont force change text color to white after timestamp printed
*EDIT*
Also I'm using Elementars client too and it has timestamps that work with colored text
![image](https://user-images.githubusercontent.com/54634728/79050857-83871380-7c35-11ea-9ecd-1eb0e6f7286c.png)

**Comment by Tigermouthbear** [comment]
its bc it uses the unformatted text instead of formatted text

**Comment by pNoName1337** [comment]
I'm using Elementars client too and it has timestamps that work with colored text
![image](https://user-images.githubusercontent.com/54634728/79050857-83871380-7c35-11ea-9ecd-1eb0e6f7286c.png)

**Comment by dominikaaaa** [comment]
Yes, tiger just explained why. Due to me being dumb when writing it

**Comment by dominikaaaa** [comment]
![2020-04-11-144455_343x91_scrot](https://user-images.githubusercontent.com/17222512/79052239-08a50500-7c03-11ea-9ab5-b354e1a7e9cc.png)
