### ISSUE TITLE
Tooltips enhancement request

### ISSUE THREAD

**Issue by pNoName1337** [kami-blue/client#685]
So as we can see there is no tooltips in GUI, but they exist in the code so I have an idea
**Request**
Add command ".tooltip" or ".tt"

**How should it work**
User write in chat ".tooltip freecam" / ".tt freecam" and cheat prints the Freecam tooltip in the chat

**Comment by dominikaaaa** [comment]
Tooltips don't exist in the code. The GUI part is issue #78, but you can already see the descriptions with the .tooltip command, which already exists

**Comment by pNoName1337** [comment]
lol really? haha, ok my bad

**Comment by dominikaaaa** [comment]
gamer moment
