### ISSUE TITLE
I don't know how to bind commands to a specific key

### ISSUE THREAD

**Issue by dragarcher** [kami-blue/client#686]
Hey,

I tried to bind to specific keys but for some reason i can't do it.

If i type: '.commands' nothing happens
Maybe i'm doing something wrong.

**Comment by dominikaaaa** [comment]
Send a screenshot of the output of .commands

**Comment by dominikaaaa** [comment]
Make sure you're using the correct syntax and prefix. The default prefix is `;`, so the command would be `;bind module key`, as shown by the autocomplete in the chat when you type `;bind`
