### ISSUE TITLE
autowalk with elytrafly and entityspeed

### ISSUE THREAD

**Issue by fw4hre0xxq** [kami-blue/client#688]
**Is your feature request related to a problem? Please describe.**
When riding an entity, or using Future's elytrafly, KAMI Blue's autowalk doesn't work.

**Describe the solution you'd like**
Autowalk to move me forward when I'm using Future's elytrafly or when I'm riding an entity

**Describe alternatives you've considered**

Using Future's auto-walk won't work because Future's auto-walk isn't compatible with KAMI Blue because Future sets all their mixin priorities to two billion for some reason. See #677  

**Additional context**

This is useful even for non Future users, since KAMI Blue on it's own can't autowalk while riding an entity.

**Comment by dominikaaaa** [comment]
Works for me 
[video](https://cdn.discordapp.com/attachments/634012886930423818/698878564103356506/ezgif.com-video-to-gif.gif)

**Comment by dominikaaaa** [comment]
{Video of it working with EntitySpeed](https://cdn.discordapp.com/attachments/573955213879410689/698879948253036565/simplescreenrecorder-2020-04-12_08.56.46.mp4)
