### ISSUE TITLE
Migrate CreditsCommand to use a JSON

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#692]

**Comment by Vonr** [comment]
but why

**Comment by dominikaaaa** [comment]
Because right now hardcoding a list that needs to be manually updated and will become out of date if you don't update your client is bad. It isn't that much work to parse it either, Dewy made a web helper for the Mojang api which is the same but more work

**Comment by Vonr** [comment]
o i thought you meant a manually updated json. so you want to parse contributors from github?

**Comment by dominikaaaa** [comment]
I would like to use the Github API, as well as a JSON in the [kami-blue/assets](https://github.com/kami-blue/assets) repo because some contributors didn't use their github account, such as 0x2E

**Comment by Vonr** [comment]
right

**Comment by Vonr** [comment]
well if i have free time ill try to do it if you havent done it before me

**Comment by dominikaaaa** [comment]
o sure <3

**Comment by dominikaaaa** [comment]
go for it if you want

**Comment by Vonr** [comment]
unfortunately its a huge if because i do nit have free time right now lol

**Comment by iBuyMountainDew** [comment]
F

**Comment by Vonr** [comment]
im actually done with the api related stuff. havent tested yet though

**Comment by Vonr** [comment]
resolved through #693
