### ISSUE TITLE
KAMI Blue Discord Bot

### ISSUE THREAD

**Issue by iBuyMountainDew** [kami-blue/client#699]
Not exactly related to the client itself, but a dedicated Discord bot would be nice to have.

**Comment by Vonr** [comment]
ok go write one

**Comment by Vonr** [comment]
https://github.com/DV8FromTheWorld/JDA

**Comment by iBuyMountainDew** [comment]
ye ik

**Comment by dominikaaaa** [comment]
You should have permission to create a repo in kami-blue, I'll host it if you want

**Comment by dominikaaaa** [comment]
also please don't make it in java

**Comment by Vonr** [comment]
after that give me collab access to that repo

**Comment by Vonr** [comment]
so i can screw up all the code

**Comment by iBuyMountainDew** [comment]
Imma close this issue, any further issues to do with the bot are obv gonna be in the bot repo
