### ISSUE TITLE
Caught exception from KAMI Blue

### ISSUE THREAD

**Issue by LobsterRoast** [kami-blue/client#702]
So i was trying to log into MC one day but when i tried to launch forge, I got an error.
''The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from KAMI Blue''

Don't know if it helps, but the mods i have installed are:
KAMI Blue
Impact
Schematica
Lunatrius Core

I've also provided the crash report here
[crash-2020-04-14_17.37.08-client.txt](https://github.com/kami-blue/client/files/4477950/crash-2020-04-14_17.37.08-client.txt)

**Comment by dominikaaaa** [comment]
Download the latest version, I fixed this issue already.

**Comment by LobsterRoast** [comment]
> Download the latest version, I fixed this issue already.

I have Version 1.1.2, which to my knowledge is the latest version.

**Comment by dominikaaaa** [comment]
No, it's like 900 commits old. Don't use the release from GitHub, build the latest version yourself or download it from the discord.

**Comment by dominikaaaa** [comment]
I'm almost finished v1.1.3, and from then on I'll be properly releasing major versions often.

**Comment by cookiedragon234** [comment]
I mean you can’t expect people to look in the discord for releases. If the GitHub release is bugged and there is a fix, then update it.

**Comment by dominikaaaa** [comment]
I know, I'm waiting to properly release it. It shouldn't be more then a day or 2.
