### ISSUE TITLE
AutoSpawner Delay

### ISSUE THREAD

**Issue by ripSquid** [kami-blue/client#703]
**Is your feature request related to a problem? Please describe.**
I am playing on a server which (I think) dont allow fast block placement. (8b8t.xyz)

**Describe the solution you'd like**
I want to have a block place delay so it places the wither slower to make it more "real"

**Describe alternatives you've considered**
None.

**Comment by Vonr** [comment]
see: https://github.com/kami-blue/client/blob/master/src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoSpawner.java

**Comment by Vonr** [comment]
hold up
theres already a delay

**Comment by Vonr** [comment]
already there lmao

**Comment by dominikaaaa** [comment]
That's delay for spam mode, between placing them.

Also @Vonr please don't misuse the kanban labels, it can fuck up the board

**Comment by Vonr** [comment]
kek anyways ill do that rn

**Comment by dominikaaaa** [comment]
Nevermind, there is a delay.
