### ISSUE TITLE
AntiSpam Suggestion

### ISSUE THREAD

**Issue by actester1235** [kami-blue/client#716]
Is your feature request related to a problem? Please describe.
No its not a problem.

Describe the solution you'd like
Instead of just hiding whats in the chat message like a discord message just hide the entire message if they set of one of the things in the antispam so its less annoying.

Describe alternatives you've considered
?

Additional context
?

**Comment by dominikaaaa** [comment]
Could you elaborate? It already hides the entire chat message, it has options for how it hides it.
