### ISSUE TITLE
FancyChat Bug?

### ISSUE THREAD

**Issue by actester1235** [kami-blue/client#717]
Describe the bug
If you have FancyChat and the > green chat on if you say ? it wont say it with the green text.

To Reproduce
1. Go to FancyChat
2. Click on 'the >'
3. Say ? then it wont say it in green or anything at all

Expected behavior
I expected it to just say the ? with the green text

**Comment by dominikaaaa** [comment]
This isn't a bug, it's intentional. Enable commands if you want to type messages that begin with command prefixes.
