### ISSUE TITLE
DiscordRPC doesn't work until re-toggled after game restart

### ISSUE THREAD

**Issue by silverxd** [kami-blue/client#720]
**Describe the bug**
DiscordRPC doesn't work until re-toggled after game restart

**To Reproduce**
1. Enable DiscordRPC
2. Close game
3. Start game again
4. DiscordRPC shows as enabled, but doesn't work.

**Expected behavior**
DiscordRPC should now auto-start since it's been toggled on, but it doesn't auto-start at least for me.

**Screenshots**
Screenshots are added here.'
before re-toggle
![before re-toggle](https://user-images.githubusercontent.com/57298235/79630755-bc0a7e00-815c-11ea-9336-f3e29a51d5ea.png)
after re-toggle
![after re-toggle](https://user-images.githubusercontent.com/57298235/79630756-bd3bab00-815c-11ea-9177-f34c76dde528.png)

**Additional context**
Disabling and re-enabling DiscordRPC in game fixes the issue, but only until the game is restarted again. This has been happening for me from 1.1.2 all the way to latest beta, maybe an old broken cfg is the issue?

**Comment by dominikaaaa** [comment]
I can't reproduce this issue, and even if I could it's most likely discord's fault.
