### ISSUE TITLE
ChatEncryption enhancements

### ISSUE THREAD

**Issue by pNoName1337** [kami-blue/client#723]
- [x] DecryptOwn - being able to disable decryption for own messages to see how the encrypted message looks without using friend/alt accout
- [x] Edit key throught a chat, so if you type in chat `;cryptkey 123` the ChatEncryption key will be set to "123"
- [x] Custom Delimiter char `;delimiter &`
- [ ] Allow ChatEncryption encrypt/decrypt 'surrounded' words with Delimiter:
- example input: "base is &coords&, come here now!"
- example output: "base is fuiwuwib, come here now!"

And I have a question regarding this module: what is the maximum value for Key?

**Comment by dominikaaaa** [comment]
1. Is pretty easy to do
2. Use the `;set` command
3. Also easy to do 
4. That's a really good idea honestly. 

As for the last question, there isn't a limit on the setting.

**Comment by pNoName1337** [comment]
And also I have another request, is it possible to make FancyChat not "touch" the encrypted text that you send? Because if it's enabled i have this 2 chinese symbols before the actual text
![image](https://user-images.githubusercontent.com/54634728/79702032-73f97180-82aa-11ea-91df-dc49033ebce6.png)

**Comment by dominikaaaa** [comment]
Um, that would be a completely different problem. What fancychat options? That probably means that fancychat is modifying the already encrypted message when they're being sent, which will produce random characters.

**Comment by pNoName1337** [comment]
I have "mOcK" and ">" fancychat modes enabled

**Comment by dominikaaaa** [comment]
Fixed.

**Comment by dominikaaaa** [comment]
Because of FriendHighlight, having ChatEncryption change the username color is no longer reliable. I decided to make decrypted messages a bit more visible and make self decryption optional, how's this? @pNoName1337 
![2020-04-20-125731_553x40_scrot](https://user-images.githubusercontent.com/17222512/79778289-81dce000-8306-11ea-8886-a61502151fc9.png)

**Comment by pNoName1337** [comment]
epic! cant wait to test it

**Comment by pNoName1337** [comment]
This "Decrypt own" is so useful, now I dont have to use an alt account. Also, how about adding custom color for "DECRYPT:"?

**Comment by dominikaaaa** [comment]
I mean I could but I don't feel it would be that useful, it's already bold so you know a player didn't say it.

**Comment by pNoName1337** [comment]
In my opinion custom color editor or just not white would be better

**Comment by dominikaaaa** [comment]
Now, while I would *love* the last option, due to how the encryption algorithm works I would have to split up the String and rewrite the encryption detection and it would be too complicated to implement, so I don't think I'm fixing the last one for a while.

I would normally just close the issue but it is a really good idea and I'd like to see it in the future.

**Comment by pNoName1337** [comment]
And also there is another "bug", Shuffle encryption mode doesnt support russian symbols, so they are not encrypted
![image](https://user-images.githubusercontent.com/54634728/79784709-529c9200-834b-11ea-8814-7ef986336c93.png)

**Comment by dominikaaaa** [comment]
That's a limitation of the encoding which was chosen and I'm not fixing that as the majority of users are from the US, and most people don't even use chat encryption

**Comment by pNoName1337** [comment]
I found one bug with ChatEncryption, if I send one-lenght message in chat (for example `?`) I get this:
![image](https://user-images.githubusercontent.com/54634728/79797496-060f8180-8360-11ea-8a59-d60aa59ee870.png)

**Comment by dominikaaaa** [comment]
I thought I fixed that. Nice that NoPacketKick catches it :p 

It happens because the game tries sending a message 0 characters long

**Comment by pNoName1337** [comment]
but its 1 character long

**Comment by dominikaaaa** [comment]
No, it's cutting off the delimiter so the message that's being sent to the server is 0 characters long.

**Comment by pNoName1337** [comment]
So is there any way to check was delimiter sent or not?

**Comment by dominikaaaa** [comment]
What? It already does that.

**Comment by pNoName1337** [comment]
Because if i send just 1 long message for example `?` with `Decrypt own` enabled I get this error

**Comment by dominikaaaa** [comment]
> I thought I fixed that. Nice that NoPacketKick catches it :p
> 
> It happens because the game tries sending a message 0 characters long
