### ISSUE TITLE
Baritone pause when server is lagging

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#724]

**Comment by pNoName1337** [comment]
This would may cause some problems with Future's and Impact's baritone integration, but maybe its wrong

**Comment by dominikaaaa** [comment]
Unless they somehow mess up baritone pause, then no. You can manually do baritone pause with Impact while a Baritone-linked module is enabled.

**Comment by dominikaaaa** [comment]
This isn't sending chat commands, I'm waiting for Baritone integration to be released, which is mostly working, so I can use the Baritone API.

**Comment by pNoName1337** [comment]
I'm using Future btw, but I know some people who use Impact and KAMI Blue

**Comment by dominikaaaa** [comment]
Same thing. Unless Future somehow fucks up the pause feature of Baritone then it would work.

**Comment by iBuyMountainDew** [comment]
Completed in b4cc09fb0b19fe40b020577971d903e4f1b825f7 and tested.

**Comment by dominikaaaa** [comment]
Don't close until merged
