### ISSUE TITLE
Blink & Freecam using Steve skin instead of custom

### ISSUE THREAD

**Issue by pNoName1337** [kami-blue/client#726]
**Describe a bug**
So actually it uses default Minecraft skin instead of custom skin

**Screenshot**
![image](https://user-images.githubusercontent.com/54634728/79702842-5d561900-82b0-11ea-8451-fb7b304ad0cd.png)

**Comment by pNoName1337** [comment]
Same situation with Freecam

**Comment by natan515** [comment]
I just checked and it's perfect. 
![2020-11-29_22 57 43](https://user-images.githubusercontent.com/66911017/100553377-5fe10e00-3296-11eb-925d-febee079dd62.png)
Completly fine

**Comment by natan515** [comment]
With kami blue blink and freecam

**Comment by l1ving** [comment]
yea the new freecam probably fixed it. I don't know about blink tho

**Comment by natan515** [comment]
It looks ok..

**Comment by Xiaro** [comment]
Fake player doesn't. It only works for online player

**Comment by natan515** [comment]
![2020-11-29_22 59 54](https://user-images.githubusercontent.com/66911017/100553448-a20a4f80-3296-11eb-8407-81375019cb7b.png)
After /kill

**Comment by natan515** [comment]
And sometimes with no connections, I mean I just can't disable it, cus it's still there.

**Comment by natan515** [comment]
Logging out and in fix it.

**Comment by Xiaro** [comment]
That is Pyro's NameTags bug, it displays dead entity

**Comment by natan515** [comment]
But why is the entity even there.. It should be removed

**Comment by l1ving** [comment]
Read above

**Comment by l1ving** [comment]
Can't reproduce this issue anyways, closed as resolved.
