### ISSUE TITLE
No Item render to NoRender

### ISSUE THREAD

**Issue by pNoName1337** [kami-blue/client#734]
**Requested impovements**
No Item render to NoRender module

No Item render can be useful to reduce lag if a lot of stuff is dropped, for example if 32k looting sword was used

**Comment by dominikaaaa** [comment]
Could you please make separate issues for unrelated suggestions?

**Comment by dominikaaaa** [comment]
Also I think this is either the GEntity or Object options for NoRender

**Comment by iBuyMountainDew** [comment]
ez

**Comment by pNoName1337** [comment]
> Also I think this is either the GEntity or Object options for NoRender

I tried both, didnt work

**Comment by dominikaaaa** [comment]
You're right.

**Comment by pNoName1337** [comment]
> Could you please make separate issues for unrelated suggestions?

I'm sorry, I will do it next time

**Comment by dominikaaaa** [comment]
It's all good. I'd tell you to open a new issue for the Search colors but it's not really possible to do custom colors for it unfortunately.

**Comment by pNoName1337** [comment]
Hey @iBuyMountainDew , I'm sorry, but since b21ea89 commit is reverted due to kotlin crashing, can you please add No Items to NoRender again?

**Comment by dominikaaaa** [comment]
It wasn't reverted. I deleted the broken downloads from the discord. You'll need to wait until I fix them.

**Comment by pNoName1337** [comment]
Ok
