### ISSUE TITLE
Pause autospawner when player is not moving

### ISSUE THREAD

**Issue by sourTaste000** [kami-blue/client#735]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When auto spawner is enabled and the player is not moving, pause auto spawner.

**Comment by dominikaaaa** [comment]
Why would this be useful?

**Comment by sourTaste000** [comment]
lol

**Comment by sourTaste000** [comment]
should i reopen this

**Comment by dominikaaaa** [comment]
Well I was wondering why it would be useful to add. I changed the title back because the previous title was unprofessional
