### ISSUE TITLE
FriendHighlight Module Bug 

### ISSUE THREAD

**Issue by sourTaste000** [kami-blue/client#739]
**Describe the bug**
When you enable FriendHighlight and type something in chat, chat gives you an empty response.

**To Reproduce**
1. Go to click GUI
2. Click on FriendHighlight
3. Type messages

**Expected behavior**
It should only highlight a friend's name and what you have typed.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/47074495/79939229-6b707a80-8413-11ea-81a9-39ffdeaa3f7f.gif)

**Additional context**
I don't know if it's the server anti-cheat that blocked the module, or its a bug.

Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 459279472 bytes (438 MB) / 1124073472 bytes (1072 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
MixinLoaderForge (kamiblue-1.1.4-455e21f-release.jar)

**Comment by dominikaaaa** [comment]
The coloring is completely client side, and I can't reproduce this issue. Make sure you don't have AntiSpam or ChatFilter enabled.

**Comment by sourTaste000** [comment]
AntiSpam and ChatFilter both not enabled

**Comment by dominikaaaa** [comment]
Can you send a screenshot of `;enabled` and your friends list?

**Comment by sourTaste000** [comment]
If you have no friend in your friend list, the issue appears

**Comment by sourTaste000** [comment]
lol just found out

**Comment by dominikaaaa** [comment]
Ah, I see. I don't expect people to be using FriendHighlight without friends but I can fix this.

**Comment by sourTaste000** [comment]
i have no friends :(

**Comment by dominikaaaa** [comment]
you can add yourself as a friend :))

**Comment by dominikaaaa** [comment]
I'll fix the bug :p

**Comment by sourTaste000** [comment]
k

**Comment by iBuyMountainDew** [comment]
It's a bit dumb that you can add yourself as a friend lol

**Comment by dominikaaaa** [comment]
I mean you can do it if you want to see your name highlighted, or don't want Aura to hit yourself in Blink / Freecam (which should probably be fixed tbh)

**Comment by sourTaste000** [comment]
will be fixed soon™?

**Comment by dominikaaaa** [comment]
Yes.

**Comment by fw4hre0xxq** [comment]
> 
> 
> It's a bit dumb that you can add yourself as a friend lol

If you were sharing your config file or MC install across multiple accounts it could make sense to avoid your alts from killing each other.
