### ISSUE TITLE
FriendHighlight uses unformatted text

### ISSUE THREAD

**Issue by pNoName1337** [kami-blue/client#743]
So this is the same problem as with ChatTimestamps, probably
![image](https://user-images.githubusercontent.com/54634728/80156764-65be9480-85cd-11ea-987a-c863b93ce455.png)

**Comment by dominikaaaa** [comment]
Works in latest version. 
![2020-04-24-210120_683x193_scrot](https://user-images.githubusercontent.com/17222512/80267644-1aa98d80-8670-11ea-8d4e-19e32a4103d0.png)
