### ISSUE TITLE
AutoFeetPlace crashing

### ISSUE THREAD

**Issue by pNoName1337** [kami-blue/client#744]
It never crashed before, I was using it with Surrond, but now its crashing, idk why
game logs: 
[logs.zip](https://github.com/kami-blue/client/files/4528698/logs.zip)

**Comment by dominikaaaa** [comment]
> java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class me.zeroeightsix.kami.module.modules.combat.AutoFeetPlace
Thonked. 

Also for the future *please* just upload the `latest.log` to pastebin. I don't need to download an unzip an entire folder of logs.

**Comment by dominikaaaa** [comment]
Can't reproduce
Config: https://pastebin.com/raw/zWgJNrhH
