### ISSUE TITLE
ElytraReplace won't replace broken elytra midair

### ISSUE THREAD

**Issue by iBuyMountainDew** [kami-blue/client#746]
ElytraReplace won't automatically replace your elytra if it breaks at the moment.

**Comment by dominikaaaa** [comment]
Look at AutoMend for the code for checking durability, it should have like a 3% limit where it won't use that elytra and try to find another one

**Comment by dominikaaaa** [comment]
Also, while we're at it, ignea suggested a toggle mode.

The way this could work is enabling the module will switch elytra and chestplate, depending on which is enabled, and then it would disable itself (ie doesn't if you're onGround or not, unlike the default option)

**Comment by dominikaaaa** [comment]
Finished in a local branch, DO NOT work on this
