### ISSUE TITLE
OffHandGap crashes when crystal pvping

### ISSUE THREAD

**Issue by sourTaste000** [kami-blue/client#754]
**Describe the bug**
 OffHandGap crashes when crystal pvping 

**To Reproduce**
1. Go to 2b2tpvp
2. Choose kit infernopickaxe.
3. Start pvp someone
4. Crashes

~~_I know you can't reproduce it, but Bella told me to put the issue here_~~
**Expected behavior**
Hit people while eating golden apple.

**Screenshots**
N/A

**Additional context**
[Full Log](https://paste.ee/p/o3NSL)
[Only Error](https://paste.ee/p/Tepem)

	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 598156736 bytes (570 MB) / 1117257728 bytes (1065 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
         FML: 
	Loaded coremods (and transformers): 
                CocoaInputCorePlugin (CocoaInput-[1.9-1.12.2]-3.1.5.jar)
                com.Axeryok.CocoaInput.CocoaInputTransformer
                MixinLoaderForge (client-1.1.4-beta-release.jar)

Edit: Deleted uwu

**Comment by sourTaste000** [comment]
https://paste.ee/p/HUfWF

**Comment by sourTaste000** [comment]
btw i had autototem on

**Comment by sourTaste000** [comment]
i guess autototem and offhandgap had conflicts

**Comment by dominikaaaa** [comment]
Offhandgap literally relies on AutoTotem, they don't conflict.

**Comment by dominikaaaa** [comment]
https://www.mediafire.com/file/zqkj0jru608zf5r/2020-05-05-7.log/file
more logs

**Comment by dominikaaaa** [comment]
I spent about an hour trying to reproduce this, couldn't.
Config: https://pastebin.com/raw/zWgJNrhH
