### ISSUE TITLE
Make StashFinder save coordinates in .txt

### ISSUE THREAD

**Issue by xTMMDx** [kami-blue/client#759]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
It would be nice if StashFinder would add the function to save stashes coordinates in a separate text document, since leaving it in the AFK would be one of the good solutions, since sometimes there is no way to follow the chat.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by dominikaaaa** [comment]
It already does this.
