### ISSUE TITLE
Stashfinder counts enderchests as shulkers

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#761]

**Comment by dominikaaaa** [comment]
![2020-05-10-141519_671x647_scrot](https://user-images.githubusercontent.com/17222512/81507071-b241e980-92c8-11ea-8719-8676e277f243.png)
Can't reproduce

**Comment by cookiedragon234** [comment]
Can’t reproduce your own bug report 🤨

**Comment by dominikaaaa** [comment]
I made the bug report on behalf of someone else. I usually make issues here for people who don't have GitHub accounts.
