### ISSUE TITLE
Make GUI Support Unicode Font

### ISSUE THREAD

**Issue by sourTaste000** [kami-blue/client#765]
**Is your feature request related to a problem? Please describe.**
I'm used to Unicode font, but kami blue's GUI is incompatible with Unicode font.

**Describe the solution you'd like**
When you use unicode font:
<img width="203" alt="Screen Shot 2020-04-29 at 11 59 20 AM" src="https://user-images.githubusercontent.com/47074495/80635564-e687f100-8a10-11ea-82f3-90c25d780d42.png">

When you use normal font:
<img width="206" alt="Screen Shot 2020-04-29 at 12 00 00 PM" src="https://user-images.githubusercontent.com/47074495/80635615-f7d0fd80-8a10-11ea-9dfd-09ff52bdfed0.png">

The smaller text should be easier to read when you use Unicode font.

**Describe alternatives you've considered**
Don't use Unicode font.

**Comment by sourTaste000** [comment]
wrong tag maybe

**Comment by dominikaaaa** [comment]
While I'd like to fix it, it's not possible without antialiasing the unicode font like Impact does, which is loads of work. Putting this on long term.

**Comment by dominikaaaa** [comment]
See #790.
