### ISSUE TITLE
Spammer doesn't support cyrillic symbols

### ISSUE THREAD

**Issue by pNoName1337** [kami-blue/client#766]
**Is your feature request related to a problem? Please describe**
Yes

**Describe the solution you'd like**
Fix the issue if possible

**Comment by pNoName1337** [comment]
Sorry wrong template was used

**Comment by pNoName1337** [comment]
@dominikaaaa

**Comment by dominikaaaa** [comment]
Pinging me won't get it done faster. I was sleeping.
