### ISSUE TITLE
Modules that are incompatible with other mods

### ISSUE THREAD

**Issue by pNoName1337** [kami-blue/client#769]
- [ ] Crash with EyeFinder (Future or Rusherhack)
https://pastebin.com/5ru8T9hW

- [ ] Crash with AutoFeetPlace (Future or Rusherhack)
https://pastebin.com/FeqwiwrA

- [ ] Crash with AutoTrap (Future or Rusherhack)
https://pastebin.com/dbaHux0s

- [ ] Crash with CrystalAura (Future or Rusherhack)
https://pastebin.com/gsgbpBcf

- [ ] Crash with StorageESP (Future or Rusherhack)
https://pastebin.com/aLLezg6Z

- [x] InventoryMove Mixin (fixed!)
Causes Futures AutoWalk and AntiAfk to break 

- [x] BreakingWarning and ServerNotRespond
See #647

- [x] Impact StorageESP (won't fix)
It turns gray with blue installed, use blue's storage esp instead 

- [ ] Impact ESP (unconfirmed)
Black screen in f3

- [ ] Combined with schematica, Minecraft settings don't save (unconfirmed)

- [ ] PlayerModel crash with salhack (probably fixed, unconfirmed)
https://pastebin.com/832cCnJp

- [x] PlayerModel incompatible with Inventoryviewer (fixed)

**Comment by dominikaaaa** [comment]
Checked issues means fixed.

**Comment by dominikaaaa** [comment]
These should hopefully be fixed in latest. Try testing v1.1.7-a80bb58e

**Comment by dominikaaaa** [comment]
Closing this as kami tesselator has been rewritten in kotlin and cleaned up, and we have new 2d render utils. Most of these were unconfirmed, please reopen if you can reproduce any of these.
