### ISSUE TITLE
Add mixin for onUpdateWalkingPlayer (EntityPlayerSP)

### ISSUE THREAD

**Issue by ionar2** [kami-blue/client#779]
Useful for rotation modules rather than editing on packet listener. (AutoCrystal, surround, building mods etc)

**Comment by cookiedragon234** [comment]
Elaborate?

**Comment by dominikaaaa** [comment]
See this insightful conversation that explains exactly nothing but I'll still refer to it in the future: https://discord.com/channels/573954110454366214/634010567107149824/710267987956989956
