### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#78]
- [x] get component that's hovered 
  - [x] don't do anything if description is a setting
- [x] draw gui method 
- [x] combine said gui method and component hover
- [x] move them over if it goes off screen
- [x] fix the bug where they render for modules under (down) the component window 
- [x] don't render if setting window is opened

**[this](https://github.com/kami-blue/client/blob/6c9c55707b0c33c4b55fd7211089ee29621eaecc/src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootCheckButtonUI.java#L36) is where you make it do stuff!!!!**

**Comment by S-B99** [comment]
https://github.com/zeroeightysix/KAMI/issues/4#issuecomment-428218579
For reference

**Comment by RikyRuggi** [comment]
what about making a small description of the modules, maybe not all like aura that you know what it is but others like no holes ad so on idk

**Comment by S-B99** [comment]
All modules already have descriptions, just tooltips don't exist so you can't really see them

**Comment by S-B99** [comment]
![](https://cdn.discordapp.com/attachments/573955213879410689/694387508246478888/Screenshot_20200330-232755.png)

**Comment by Bluskript** [comment]
hover handling = add `onMouseHover` to `MouseListener` interface, add handler for it in `KamiGUI`,  then edit `kami/gui/rgui/GUI` to call `listener.onMouseHover` if `isHovered`

**Comment by S-B99** [comment]
I kind of want v1.1.3 to be a quality-of-life update, considering that I won't be spending so much time on it after I release it, now that I know how to do the listener making a gui part isn't that hard, so I'll work on this I guess.

**Comment by dominikaaaa** [comment]
Nevermind, messed around with how the GUI works and lets just say I've decided not to do this for 1.1.3, it's too complicated.

**Comment by dominikaaaa** [comment]
https://github.com/kami-blue/client/blob/8d9ae76dd73d29c3a517c48c3f7a97c082101eed/src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootCheckButtonUI.java
this class has a check for if a component (ie module) is hovered in the GUI

**Comment by Vonr** [comment]
epic, 1.1.4?

**Comment by dominikaaaa** [comment]
maybe, not sure yet

**Comment by dominikaaaa** [comment]
I've started working on this on a branch and now that I know how to get hovered and *render* something, i'll do it for v1.1.3!!
