### ISSUE TITLE
CrystalAura left on crash

### ISSUE THREAD

**Issue by zihasz** [kami-blue/client#788]
**Describe the bug**
When I accidentally leave CrystalAuraa turned on and close my game it won't launch until I go to the
settings file and disable it from there. (Maybe it's just a MultiMC bug.)

**To Reproduce**
Steps to reproduce the behaviour:
1. Turn on CrystalAura
2. Close the game
3. Try to start it
4. It won't launch

**Expected behaviour**
I expected it to launch.

**Additional context**
It doesn't always happen

**Comment by dominikaaaa** [comment]
Please provide a crash log so I can fix this.

**Comment by zihasz** [comment]
i think it fixed

**Comment by dominikaaaa** [comment]
??? ok

**Comment by dominikaaaa** [comment]
Comment on this if you get the issue again, with your crashlog
