### ISSUE TITLE
Looking for someone that codes a crafting system for hypixel skyblock (using chests)

### ISSUE THREAD

**Issue by LordFetznschaedl** [kami-blue/client#789]
if you can help me write under this topic and message me

**Comment by dominikaaaa** [comment]
What?? Lmao.

**Comment by iBuyMountainDew** [comment]
lmfaoooooo

**Comment by dominikaaaa** [comment]
god damnit the impact-user-intelligence kids are here

**Comment by dominikaaaa** [comment]
the profile pic is the cherry on the top
![2020-05-07-140210_330x349_scrot](https://user-images.githubusercontent.com/17222512/81328711-5a5a7700-906b-11ea-8884-f98e19cd7956.png)

# :joy_cat:

**Comment by iBuyMountainDew** [comment]
ananymos
