### ISSUE TITLE
New GUI suggestions and features. 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#790]
### Plan summary 12/05/20

my current plan for this:
hud elements (coords, radar etc) are resizable, closable, minimisable and pinnable. 
you can use different themes such as windows xp or mac os, etc

https://github.com/ocornut/imgui/issues/2109

basically like an entire desktop environment feel to it

### Minor update 11/05/20
I got 086's original jtcui implementation working, I think I'll be using that GUI library :package: 

***

I've decided to close all other GUI suggestions and put them here, as I don't think it would be worth the time implementing those instead of writing my own GUI from scratch in the *far* future (maybe in a few months)

- [x] Proper color pickers. You know, like the RGB(A) squares + vertical slider for brightness. 
- [x] Custom positioning for HUD elements (GUI elements position will be set, I'll release a mockup image sometime in the future?)
- [ ] A proper settings menu for GUI / Client stuff (don't forget #392)
- [x] Implement existing GUI features 
  - [x] (I will add these here once I start working on it)
  - [x] Baritone proc
- [ ] Themes + color customization. (Formerly #32)
- [x] Support for all setting types
  - [x] Boolean
  - [ ] Smaller boolean (eg "visible" setting)
  - [x] Binds 
  - [x] Enums
  - [x] Strings 
  - [x] Ints / Floats / Doubles
  - [x] Slider 
  - [ ] Infinite Slider (make this more intuitive, see below comment)
  - [x] Entering numbers / strings precisely
- [x] Custom font
  - [x] Custom font size
- [x] Support Minecraft default / unicode fonts
- [x] GUI Scaling
- [x] Being able to close HUD elements and reopen them
- [ ] Descriptions for settings
- [x] Searching settings
- [ ] Tutorial 
- [ ] Rofi!!
- [x] Custom windows
- [ ] maybe ability to open out single modules
- [ ] Frequently used / Favorites?
- [x] for location of some modules (PlayerModel, InventoryViewer), choosing the location should be sort of like an eyedropper 

If I find something else, I'll add it to this list. 

Feel free to comment something you'd like to see added.

**Comment by dominikaaaa** [comment]
You can make infinite sliders more intuitive with arrows on the sides or something
![image](https://user-images.githubusercontent.com/17222512/81591532-930b9080-938a-11ea-88ea-593086425897.png)

**Comment by dominikaaaa** [comment]
Just a thought, having a method to return a Color by passing an enum in, or a Map or something would be worlds better then what I do right now

```java
        glColor4f(toF(GuiC.buttonIdleN.color.getRed()), toF(GuiC.buttonIdleN.color.getGreen()), toF(GuiC.buttonIdleN.color.getBlue()), component.getOpacity());
```

**Comment by dominikaaaa** [comment]
- [ ] Another cool idea is built in themes
  - [ ] Windows XP
  - [ ] Windows 10 maybe?
  - [ ] OSX
  - [ ] Gnome or KDE?

**Comment by dominikaaaa** [comment]
One other idea I had while on a walk was having window buttons like close, minimize and maximize(?), along with a pin one to pin it on the HUD

**Comment by dominikaaaa** [comment]
- [ ] I think this is already on the list, but being able to close and reopen hud elements

**Comment by GrelTheL** [comment]
add popbob theme

**Comment by S0LDR** [comment]
https://user-images.githubusercontent.com/8225057/46304087-00035580-c5ae-11e8-8904-f27a9434574a.gif
I think this should be a theme, i like the default i think it is

**Comment by S0LDR** [comment]
- taskbar that the stuff goes to when you close them

**Comment by dominikaaaa** [comment]
The gif you linked is just the default imgui theme (which is linked in the issue lol), and I was planning on making my own GUI engine, but I might use imgui if I don't get as far as I'd like

**Comment by pNoName1337** [comment]
imgui is for c++

**Comment by dominikaaaa** [comment]
imgui works on Java and KAMI Fabric uses it

**Comment by pNoName1337** [comment]
lol what how LOL

**Comment by dominikaaaa** [comment]
magic and 086's drunk java install

**Comment by zeroeightysix** [comment]
The original C++ implementation of imgui does not work on Java. KAMI uses a full kotlin port of the library, hosted [here](https://github.com/kotlin-graphics/imgui).

**Comment by mothheart** [comment]
ClickGUI widget that could be used to rebind the key used to open clickgui. Currently the option for it is 
;bind clickgui [key]

**Comment by cristiioan** [comment]
Windows 10 GameBar support

**Comment by dominikaaaa** [comment]
what lmao????? 

1. Like exactly 0 of the major contributors (including me) don't use windows
2. Minecraft already supports it, just press Win + G

**Comment by sourTaste000** [comment]
windows lmao

**Comment by cristiioan** [comment]
@dominikaaaa Windows 10 gamebar has extensions. An extension for windows 10 gamebar

**Comment by dominikaaaa** [comment]
and what would that do lmao

**Comment by dominikaaaa** [comment]
rofi --dmenu

best idea in this thread so far

**Comment by dominikaaaa** [comment]
Rounded corners option

**Comment by jumboman32** [comment]
Resizeable Windows (or tabs whatever u call them) (dont know if this falls under the scaling suggestion)
Friend Tab Rewrite - add or remove friends instead of using the command
Color Customization - full color customization for the whole click gui
Less frequent snapping - moving stuff around seems laggy
Reset positions of tabs - resets everything to default
customizable radar
custom fonts + colors

**Comment by GoodPro712** [comment]
coords able to only show Y coord

**Comment by GoodPro712** [comment]
gui for server ip and another for server anticheat

**Comment by GoodPro712** [comment]
#1302 hding modules from the clickgui, useful for modules youre not going to use

**Comment by l1ving** [comment]
Seeing as I'd like to introduce flexible categories, it would be possible

**Comment by slashsynapse** [comment]
also make the gui size equal in all the kami gui sub gui thingies
![image](https://user-images.githubusercontent.com/60920165/97024108-0c332480-1574-11eb-8db8-896b90a91c09.png)
like wtf this is my ocd crying

**Comment by l1ving** [comment]
> also make the gui size equal in all the kami gui sub gui thingies

Actually there's currently a bug "fix" in place that relies on them being different sizes. This won't happen in the rewrite

**Comment by slashsynapse** [comment]
oki

**Comment by slashsynapse** [comment]
is there a search options for modules?

**Comment by l1ving** [comment]
Uh, no. `;toggle name` has a preview of available modules

**Comment by slashsynapse** [comment]
also, There is one more bug I think?  um sometimes, the description of the modules do not switch to the other side where there is space when the gui thing is on the edge of the screen

**Comment by l1ving** [comment]
This isn't a place to suggest bug fixes for the current GUI. If it's not a major bug it's not being fixed, wait for the new GUI

**Comment by slashsynapse** [comment]
ik but i couldn't help it :p

**Comment by l1ving** [comment]
All comments in this thread are superseded by #1648, thanks for all your suggestions!
