### ISSUE TITLE
Packet Mine

### ISSUE THREAD

**Issue by zisis912** [kami-blue/client#796]
packet mine is a module that allows you to click a block once, and as long as you stay close to it, it will be automatically mined without you even looking at it. It would make breaking obsidian in crystal pvp much more easier, as players that get in your way won't cancel the mining animation

**Comment by sourTaste000** [comment]
change hack to module plz

**Comment by dominikaaaa** [comment]
NoEntityTrace already prevents other people from stopping you from mining?

**Comment by zisis912** [comment]
well, not only for that, it would generally be a nice module to have
