### ISSUE TITLE
autoTPA breaks on colored names

### ISSUE THREAD

**Issue by mattymatty97** [kami-blue/client#798]
**Describe the bug**
AutoTPA will fail recognizing a friend if it has a colored name

**To Reproduce**
1. have a friend with colored name
2. enable AutoTPA on Deny mode
3. enable accept friends
4. let your friend request a tp to you
5. AutoTPA will deny it's request

**Comment by dominikaaaa** [comment]
Turns out this isn't related to colored names, the split doesn't work.
