### ISSUE TITLE
Intellij Run Configurations aren't being generated properly.

### ISSUE THREAD

**Issue by FireMasterK** [kami-blue/client#802]
**Describe the bug**
gradlew genIntellijRuns does not generate run configurations.

**To Reproduce**
git clone https://github.com/kami-blue/client/ KAMI
gradlew setupDecompWorkspace
Open the project once then close Intellij
gradlew genIntellijRuns

**Expected behavior**
I should be able to run the client through Intellij

**Logs**
Gradle Log: https://paste.ubuntu.com/p/NTvctc7TXC/

**Additional context**

**Comment by iBuyMountainDew** [comment]
Open and close IntelliJ and try again. If that still doesn't work, reimport the gradle project and open/close. This isn't even a Kami Blue problem; it's a ForgeGradle problem. If it persists, ask them.
