### ISSUE TITLE
Don't blame Forge for things that don't work

### ISSUE THREAD

**Issue by FinnT730** [kami-blue/client#803]
An hour ago, you sent someone to Forge, while not a problem, they don't support 1.12.2 anymore (Since January 1st) and they don't condole hacked clients. Don't blame something that works, that you guys hacked together to create a hacked client (as a mod even.....).
And a custom cape? This is against Mojang's EULA, so even more legal trouble.

**Comment by iBuyMountainDew** [comment]
The issue with genIntellijRuns is version independent and project independent. That is, I've run into this problem with different projects in all manor of versions. It's not a FORGE problem. It's a problem with the ForgeGradle gradle plugin, which is not dependent on the game in any way and is not tied to any specific version. He doesn't need to bring up KAMI Blue at all if he were to report this to the Forge devs as it's not specific to KAMI Blue.

As for capes, while against Mojang's EULA, they don't really ever go after mods with capes and other cosmetics of that sort, examples include Optifine and many PVP clients such as Lunar client. I see the capes issue similarly to servers selling pay to win elements, while not technically allowed, people just don't really care.

> Don't blame something that works, that you guys hacked together to create a hacked client (as a mod even.....).

What? We didn't hack together ForgeGradle, if that's what you're saying. Also, please note, this isn't a hacked client. It's a utility mod.
