### ISSUE TITLE
Criticals don't work on some servers

### ISSUE THREAD

**Issue by Bluestacker** [kami-blue/client#810]
**Describe the bug**

Criticals basically dont work, i just hit normal damage with it ON

**To Reproduce**
1. Go to 'menu'
2. Enable 'Criticals'
3. Have more than 100 ping below 200
4. Criticals wont work

**Expected behavior**

It should work, i use impact + kami and i have to use impacts criticals with kami, so i dont think its a user issue or something.

**Comment by dominikaaaa** [comment]
What server?

**Comment by Bluestacker** [comment]
2b2tpvp

**Comment by cookiedragon234** [comment]
Describe the bug
A clear and concise description of what the bug is

**Comment by Bluestacker** [comment]
Criticals basically dont work, i just hit normal damage with it ON
