### ISSUE TITLE
AutoBlock

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#821]
Makes a wall with obsidian when a crystal is placed. It sounds lame at first but after some discussion I think this is a genuinely good idea, at least it would be fun to code.

![](https://cdn.discordapp.com/attachments/573955213879410689/709979622099517471/Screenshot_20200513-000230.png)

**Comment by elan69** [comment]
its actually a very good idea, even wurst has it lel

**Comment by zisis912** [comment]
I don't understand, how could this be useful?

**Comment by l1ving** [comment]
Holefiller 🗿
