### ISSUE TITLE
Aimbot with elytra

### ISSUE THREAD

**Issue by Bluestacker** [kami-blue/client#822]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when...

When i could bowspam someone in air but i cant

**Describe the solution you'd like**
Bowspam with aimbot flying with elytra

**Describe alternatives you've considered**
Maybe just add a module on aimbot to elytras that works with fastuse

**Additional context**
I just saw a guy doing 2vs1 while flying with elytras, he was just bowspamming and no one could attack him, so this seems to be op

**Comment by dominikaaaa** [comment]
This already has aimbot
