### ISSUE TITLE
LoginMessage doesn't run more then once

### ISSUE THREAD

**Issue by suretic** [kami-blue/client#827]
**Describe the bug**
LoginMessage causes an Internal Exception: java.lang.NullPointerException when trying to connect to a server (connection also gets lost)

**To Reproduce**
1. Enable LoginMessage
2. Connect to a server (you might need to restart the game before that)
3. Bug occurs

**Expected behavior**
Send login message

**Screenshots**
https://prnt.sc/sgbspz

**Additional context**
Logs https://pastebin.com/y9gbuLRL

**Comment by dominikaaaa** [comment]
I can't reproduce the NPE but LoginMessage doesn't run more then once period

**Comment by suretic** [comment]
I've tested joining different servers and noticed that the NPE only appears when joining a paper server. I'm able to join vanilla servers without getting a NPE. I don't know if it's related to that.

**Comment by dominikaaaa** [comment]
This should be fixed, let me know if this still happens

**Comment by suretic** [comment]
not happening for me anymore 👍
