### ISSUE TITLE
The Server Ips setting in the AntiSpam module filters non-ipaddresses.

### ISSUE THREAD

**Issue by Sorzon** [kami-blue/client#828]
The problem is created by this regex: "^(?:http(?:s)?:\\/\\/)?(?:[^\\.]+\\.)?.*\\..*\\..*$"
Due to how most elements in this regex are optional, a lot of non-url and non-ip messages in chat can also be filtered.
Disallow spaces and forcing content between '.' characters should improve the filtering.
Examples of messages that get filtered unexpectedly are:

> Lorem... Lorem Ipsum? Dolor sit. Amet consectetur adipiscing elit. Aliquam ut viverra lorem

> Nunc eget, Fermentum. Sagittis, consectetur adipiscing? Sagittis? Sagit! Sagit! Sagit. > Sagit

> NUNC eget arcu eget nisl fringilla ullamcorper. Nec'odio semper 3 pellentesque id iaculis sit amet.

> ETIAM A EROS AC TORTOR..

**Comment by l1ving** [comment]
The regex should be gone entirely now
