### ISSUE TITLE
LegCrystal

### ISSUE THREAD

**Issue by Bluestacker** [kami-blue/client#835]
This is a suggestion about a new module called LegCrystal.

**Describe the solution you'd like**
When you trap someone and break the obsidian, this new module would override CA and will spam crystals on their legs level (this could work with the pickaxe so they wont have time to place obsidian)

Ex: you trapped someone, you have LegCrystal ON, so you gonna use your pickaxe to destroy the obsidian, LegCrystal should detect the destroyed obsidian and automatically spam the crystals with 0 delay

**Describe alternatives you've considered**
none

**Additional context**
-

**Comment by dominikaaaa** [comment]
I'm closing this as won't fix, because the crystalaura should already target vulnerable players as long as the crystal won't kill you as well.
