### ISSUE TITLE
OffHandGap overrides manual offhand Crystal

### ISSUE THREAD

**Issue by Bluestacker** [kami-blue/client#836]
**Describe the bug**
Using OffhandGap + AutoTotem > Custom Item > Crystal, wont let you place crystals manually

**To Reproduce**
1. Go to 'menu'
2. Click on 'OffhandGap, enable everything inside OffhandGap Module, even crystal check | set AutoTotem to custom item > Crystals '
3. See error

**Expected behavior**
Well, when you right click, OffhandGap is basically changing your offhand crystal to a gapple, so you cant place the crystal, idk honestly how it could be fixed, i have a toggle with Aura + OffhandGap, so i just disable Aura and enable CA, i shouldnt be doing that, so thats why i think its a bug.

**Additional context**

**Comment by dominikaaaa** [comment]
What settings in offhandgap?

**Comment by Bluestacker** [comment]
All enabled and disable in 4.0

**Comment by dominikaaaa** [comment]
Send a screenshot

**Comment by dominikaaaa** [comment]
Also what are you holding when it happens?

**Comment by Bluestacker** [comment]
A sword
https://cdn.discordapp.com/attachments/677135239667122176/711011101692919869/20200515_211818.jpg

**Comment by dominikaaaa** [comment]
Does the behavior change when you disable crystal check?

**Comment by Bluestacker** [comment]
it doesnt
