### ISSUE TITLE
Minimap (edit: just warning you it is going to be huge. Read it last)

### ISSUE THREAD

**Issue by zisis912** [kami-blue/client#841]
I know you rarely even find minimaps in hacked clients these days... but here is my idea.

First of all, to avoid confusion, I will say the minimap (the small map on the top of your screen), the minimap module (the module itself), and the bigmap (when the map covers your whole screen). 

Ok, let's start. The minimap module won't have a bind for on/off, but it will have 2 binds. One bind is to open the bigmap (default set to T), and one bind for landmark tracers (default set to none). When you open the bigmap, it will show you a map of all the chunks you have ever loaded (something like most minimap mods). In the down right corner, you will also see the coords of the location you are hovering on. In the bigmap, you will be able to add a landmark to any location you have or haven't seen (locations that you haven't seen are gray). You can put a name in a landmark, adjust its color, adjust its size(if possible), and turn it on/off (if it is off it will have 35% optacity and its colors will turn to half grey). Now is the point where the tracers come into play. If you press the bind to toggle the landmark tracers on, tracers will appear that will drive you to the coordinates of your landmarks (that you have set to on, not off). Each tracer is going to be colored with the color of the landmark it is driving you to. 

**Extra Notes:** to turn the small minimap on/off, you have to open the menu, like the radar.
                       you are also able to change the default color of the landmarks

**Comment by dominikaaaa** [comment]
Just use a minimap mod, this is forge anyways.
