### ISSUE TITLE
Auto-waterMLG

### ISSUE THREAD

**Issue by zisis912** [kami-blue/client#842]
will automatically switch to the slot with a water bucket in your hotbar, and automatically do a Water MLG if you take more than the Minimum Damage option. If you have no bucket in your hotbar, but you have a water bucket in your inventory, it will automatically switch your current hotbar slot to a waterbucket at the last 3 seconds of the fall, do the MLG, and then replace the waterbucket in your hotbar with the item you had before. Because why not.

**Comment by Sorzon** [comment]
This is a nice feature, and is already in the client, under Player > NoFall, and then switch to mode 'bucket'. The specified delay you mention can be configured there as well!

**Comment by dominikaaaa** [comment]
NoFall already does this
