### ISSUE TITLE
Stack Refiller (rename it however you want)

### ISSUE THREAD

**Issue by zisis912** [kami-blue/client#848]
So, I thought, auto-totem will automatically move totems from your inventory to offhand, meaning that clients have the ability to move stuff around your inventory. My idea is a block refiller.Let me explain.

Supposing you have 64 obsidian in your hotbar, and another 6 stacks of obsidian in your inventory. You turn the hack on. Once you place a single obsidian, and the stack is at 63, obsidian is automatically taken from your inventory to automatically refill the stack to 64. This will happen to any stackable item in your hotbar. So you never need to open your inventory, just to replace the stack of obsidian you jsut placed with a new one. I don't know if this is possible, but it would make life a lot easier. Especially with crystals in crystal pvp. Also, one of its advantages, is that if you don't see that you have 64 of a block, it means that you will run out of it soon. So it is a warning at the same time.

**Comment by dominikaaaa** [comment]
This is already a feature

**Comment by zisis912** [comment]
wtf if this is already a feature why did you just add this to the next update

**Comment by dominikaaaa** [comment]
no, it's been a thing for a few months. it's called AutoReplenish

**Comment by zisis912** [comment]
I am asking why did you add this to 1.1.4
![image](https://user-images.githubusercontent.com/65046191/82127095-d5353780-97b9-11ea-9d69-17775ab56477.png)

**Comment by dominikaaaa** [comment]
Because I answered the question in the current milestone. I don't leave anything unmilestoned

**Comment by zisis912** [comment]
oh ok
