### ISSUE TITLE
Movement blocker

### ISSUE THREAD

**Issue by zisis912** [kami-blue/client#850]
Isn't it annoying when you are chasing someone on skywars, and he places a block, and it blocks your sprint, so you have to jump and resprint just to continue chasing him?

That's exactly what this hack will do. When you are being chased, you can turn this hack on and it will automatically put a block in front of any player sprinting. (in the direction they are looking at). This will slow players down, and will allow you to escape when being chased in land much faster.

**Comment by dominikaaaa** [comment]
I don't see how this is useful for anarchy with step hacks and pearls and scaffold and everything
