### ISSUE TITLE
DQS Integration / Support

### ISSUE THREAD

**Issue by iBuyMountainDew** [kami-blue/client#853]
**Additional features and utilities for those subscribed to DQS (https://discord.gg/8mWZqv5) to KAMI Blue would make for a unique, integrated experience with the product unlike a standard proxy.**

Things like protecting against joining 2b when you have an active instance (which can break things), a button to direct connect to dqs.dewy.dev, and a disconnect screen displaying options for either disconnecting COMPLETELY and shutting down the instance or handing over control to DQS.

These utilities will only be seen by registered DQS users, as otherwise it would be intrusive and a bit ge.

**Comment by Tigermouthbear** [comment]
just make a separate mod

**Comment by dominikaaaa** [comment]
this lmao

**Comment by iBuyMountainDew** [comment]
Well yes, but the thing is...

Kami blue: 40000
DQS Mod: 0

**Comment by Tigermouthbear** [comment]
dqs mod would be better bc many people wouldn't want to be forced to use kami blue

**Comment by dominikaaaa** [comment]
I'm honestly in favor. it would bloat kami blue even more for non dqs users

**Comment by cookiedragon234** [comment]
Yep, tigers right, this is out of scope for kami blue
