### ISSUE TITLE
Aimbot problems

### ISSUE THREAD

**Issue by GalteXx** [kami-blue/client#856]
Every time i turn aimbot on nonexisting hotbar cell is being choosen (if hotbar goes from 0 to 8, this cell is -1)
To see this bug just turn on aimbot(combat > aimbot > *click*)

![image](https://user-images.githubusercontent.com/65533265/82190973-85aa5500-98fa-11ea-8299-d65b7fdee7e5.png)
If it happens on the server I instantly get kicked.

**Comment by iBuyMountainDew** [comment]
Working on a fix, it's because you have now only mode on when there's no bow in your hotbar. Still needs fixing tho.

**Comment by iBuyMountainDew** [comment]
Looks like I'm a bit of a special stinker; you're running an extremely old version of KAMI Blue. Please update to the latest release.
