### ISSUE TITLE
Hitting Close File in WorldDownloader crashes the game

### ISSUE THREAD

**Issue by DrOzons** [kami-blue/client#863]
-Describe the bug
Disabling WorldDownloader crashes the game.

-To Reproduce
Leave WorldDownloader enabled an leave the game.
When you get on again, try hitting CloseFile, the game crashes.

-Expected behavior
WorldDownloader should be disabled

-Crash Report
https://pastebin.com/k5qtvUyk

-Latest.log
https://pastebin.com/w0ApGuVH

**Comment by dominikaaaa** [comment]
Reverted changes in 64c9222cf7ef66b4f5a5f367457535a039a5e449
