### ISSUE TITLE
Mid-air rubber banding

### ISSUE THREAD

**Issue by BumleDK** [kami-blue/client#867]
**Describe the bug**
When you fly around and stops for a second to look around, it starts to rubber band your view to the direction you stoppet mid air

**To Reproduce**
1.  Takeoff
2. Fly anywhere then just stop and hold  altitude and then look around

**Expected behavior**
Should be able to look around with ease without rubber banding. Did work fine before the “20 May patch”

**Comment by BumleDK** [comment]
I switched to Future instead of Impact, and seems like it does not have this issue while being in the air with Elytra

**Comment by dominikaaaa** [comment]
Disable hover, 2b2t patched hover. Working on a fix.

**Comment by BumleDK** [comment]
Hover is disabled and using Default settings, and it actually still rubber banding with future. not using and never used AntiForceLock

**Comment by dominikaaaa** [comment]
Oh I didn't read the issue correctly. Enable AntiForceLook, that's exactly what it fixes.
