### ISSUE TITLE
AntiBookKick does not work

### ISSUE THREAD

**Issue by thankyoutybg** [kami-blue/client#870]
I turned on AntiBookKick and put my trust that it won't kick me when I move the books in my echest. It didn't.

1. Get on 2b2t
2. Get a signed book
3. Turn on AntiBookKick
4. Click on the book

I expected it to not allow me to click on books so I had to shift-click them.

**Comment by dominikaaaa** [comment]
![maim-2020-05-25-16-27-07](https://user-images.githubusercontent.com/17222512/82841611-bbc07980-9ea4-11ea-8004-6fecd33b584e.png)
fixed
