### ISSUE TITLE
Adding delay to Autoreply and AntiAfk's autoreply

### ISSUE THREAD

**Issue by Xiaro** [kami-blue/client#871]
**Is your feature request related to a problem? Please describe.**
If another player has their auto reply module on, They can force you to spam the server by send a whisper to you. And Server will kick both players for spamming whispers

**Describe the solution you'd like**
Adding option to set a delay between each auto reply message. So the server won't kick you for spamming it.

**Describe alternatives you've considered**
Adding a message filter to auto reply. Stop auto replying if a player keep spamming the same message to you.

**Additional context**

**Comment by dominikaaaa** [comment]
If you enable AntiSpam with filter duplicates then it won't reply because it won't get the message

**Comment by l1ving** [comment]
Right now there's a chat queueing system, this should be resolved.
