### ISSUE TITLE
When using XRay, the screen goes black very rarely. Toggling fixes it

### ISSUE THREAD

**Issue by dusberendguy** [kami-blue/client#880]
when using xray sometimes the screen gets black.

xray

I have a video of the problem, please contact me (dusberendguy) for the video. in the video I also show it is a problem from kami, by using kami's xray and impact's xray.

**Comment by dominikaaaa** [comment]
This is impacts fault, only use kami blues x-ray.

**Comment by dominikaaaa** [comment]
Reopening, got a video.

It's fixed by toggling the x-ray. 

https://youtu.be/v7HBwKrunD4

**Comment by l1ving** [comment]
This should be fixed by #1510

**Comment by l1ving** [comment]
This is no longer an issue.
