### ISSUE TITLE
ElytraFlight Easy Takeoff C Bug

### ISSUE THREAD

**Issue by Oecher1** [kami-blue/client#881]
**Describe the bug**
if you go on ElytraFlight mode control turn on easy takeoff c and if you dont have a elytra when you walk off a block like 3 blocks up or something it will try to make you glide or something its weird

**To Reproduce**
1. Go to ElytraFlight
2. Turn on control mode with easy take off c on
3. go up like 5 blocks walk off and
4. it will try to make you glide even without wearing a elytra

**Expected behavior**
i expected it wouldn't try to make me glide without having a elytra on

**Screenshots**
no

**Additional context**
no

**Comment by dominikaaaa** [comment]
Toggle the module on and off. I'll add a check later.

**Comment by dominikaaaa** [comment]
Toggle the module on and off. I'll add a check later.
