### ISSUE TITLE
Nofall

### ISSUE THREAD

**Issue by Oecher1** [kami-blue/client#882]
**Is your feature request related to a problem? Please describe.**
Make it compatiable with elytras so like when your falling and you have nofall on you can open the elytra cause right now when you try to it will just close the elytra

**Describe the solution you'd like**
Just make it so you can open elytras when your falling with nofall on

**Describe alternatives you've considered**
?

**Additional context**
no

**Comment by dominikaaaa** [comment]
> That's because the server requires you to be falling to open an elytra, and NoFall tries to hide the fact that you're falling from the server, therefore the elytra won't open.

#304
