### ISSUE TITLE
Improve PacketFly to work for clipping and the such 

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#888]
Example [video](https://cdn.discordapp.com/attachments/634010567107149824/715221802342809730/bandicam_2020-05-27_18-15-27-610.mp4)

**Comment by pNoName1337** [comment]
it worked before https://cdn.discordapp.com/attachments/710891361615740948/715305092798087198/bandicam_2020-05-27_23-45-00-454.mp4
