### ISSUE TITLE
Freecam does not place blocks on constantiam.net

### ISSUE THREAD

**Issue by epicfacethe3rd** [kami-blue/client#894]
**Describe the bug**
Freecam does not place blocks on constantiam.net

**To Reproduce**
1. log onto constantiam.net
2. get something to place
3. go into freecam
4. try to place blocks and fail horribly

**Expected behavior**
you should be able to place blocks in freecam you could otherwise reach normally

**Screenshots**

**Additional context**
i'm running future as well, but that shouldn't affect anything (i think)

**Comment by dominikaaaa** [comment]
Won't fix, see #530. Will keep it in mind though.
