### ISSUE TITLE
'Drop like a brick mode' when exiting elytrafly.

### ISSUE THREAD

**Issue by fw4hre0xxq** [kami-blue/client#900]
**Is your feature request related to a problem? Please describe.**
When exiting control mode elytrafly, it keeps you in elytra mode coasting forward, even if you're at a stop when you deactivate elytrafly. This means you have to land far away from intended, in an ocean and/or flying around in circles for a long time to kill momentum and/or crashing.

**Describe the solution you'd like**
Either as an option in the elytraflight module, or a separate module, the ability to either automatically when deactivating elytrafly, or by hotkey, send a packet to the server indicating that the player is on the ground, to kill forward momentum, making the player drop straight down, for faster, more precise landings.

**Describe alternatives you've considered**
None 

**Additional context**
See discussion between hifunc and dominika in discord #general

**Comment by fw4hre0xxq** [comment]
I realized it doesn't have to do anything with packets, just add an option to the efly module, or a hotkey or something to unequip and re-equip the elytra real quick when it gets turned off, that will also make you drop like a brick.

**Comment by Xiaro** [comment]
Looking down will also give your the same effect

**Comment by dominikaaaa** [comment]
uwu https://cdn.discordapp.com/attachments/634010583527587840/730116746111090748/Auto_Landing.mp4
