### ISSUE TITLE
Crashing when opening the game

### ISSUE THREAD

**Issue by Podrock-ian** [kami-blue/client#901]
**Describe the bug**
I am using Kami Blue v1.1.4 with Future, Baritone, Wdlforge, CreativeCore, LunatriusCore, Schematica and Optifine. For the past few days this has worked fine but now when I launch my game it crashes before I reach the menu the game closes and I get the error message:
"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from KAMI Blue"
Deleting Kami Blue from my mods folder fixes the issue.

**To Reproduce**
1. Download all the mods I have
2. Open forge through the minecraft launcher.
3. Get the error. 

**Expected behavior**
The game will open then close and read "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from KAMI Blue"

**Screenshots**
My mods folder (I also have the latest version of Future as well) : https://imgur.com/a/DgqcigN

**Comment by Podrock-ian** [comment]
Replacing my Future folder with an older backup of it fixed the problem

**Comment by cookiedragon234** [comment]
Just don’t use future

**Comment by dominikaaaa** [comment]
this is the correct answer

**Comment by elan69** [comment]
ah yes pay money to cheat in a block game
