### ISSUE TITLE
Baritone Integration and Safewalk

### ISSUE THREAD

**Issue by chickenjoel** [kami-blue/client#903]
**Description**
When you have safewalk on and use baritone, when you get to the edge of a block with a 1 or more block drop, baritone stops moving due to safewalk.

**To Reproduce**
Steps to reproduce the behaviour:
1. Turn on safewalk when standing near an edge
2. Try to baritone off the edge
3. Notice baritone will walk to the edge and attempt to continue walking until it reaches the edge of the block with a drop

**Expected behavior**
Baritone to ignore/disable safewalk

**Comment by mattymatty97** [comment]
;b set assumesafewalk true

**Comment by mattymatty97** [comment]
or # instead of ;b

**Comment by dominikaaaa** [comment]
Yes, but it would be nice if it was integrated, like the Jesus modules enables / disables walking on water in baritone

**Comment by mattymatty97** [comment]
ok that good

**Comment by chickenjoel** [comment]
Yeah so the command exists, but the problem with it is that approx. 3% of the people who use Baritone know how to use the advanced commands - I probably should have put this in suggestions sorry.
