### ISSUE TITLE
noslow and baritone can cause falling off stuff

### ISSUE THREAD

**Issue by fw4hre0xxq** [kami-blue/client#905]
**Describe the bug**
If you have the nowslowdown module on and use baritone in a tight area with 1 block bridges and long drops, you'll fall

**To Reproduce**
Unsure how to describe
**Expected behavior**
You shouldn't fall to your death when using baritone with the noslowdown module on.
**Screenshots**

**Additional context**

**Comment by dominikaaaa** [comment]
Disable sneak in noslowdown, if it didn't happen while eating. 

I'd like a proper solution but baritone doesn't support any form of speed mods in any way.
