### ISSUE TITLE
add multiple profiles

### ISSUE THREAD

**Issue by zisis912** [kami-blue/client#906]
Add mulyiple setting profiles. For example, you have your 2b2t profile, with a lot of hacks that aren't allowed on most servers, then you got your Mineplex profile, with less violent hacks, and more. Profiles will both save the toggle state of the modules and their settings diferrently. I don't know naything about coding, but I guess that to make this you will need multiple config.txt files (or however they're called0

**Comment by iBuyMountainDew** [comment]
The kami blue project contains no hacks or cheats, it is a utility mod, and one that is specifically designed and meant to be used on anarchy servers. I don't think this will really be necessary.

**Comment by mattymatty97** [comment]
isn't there the ;config command
that let's you save/load different config files?

**Comment by dominikaaaa** [comment]
Yes there is. Just edit the last config file and then reload.
