### ISSUE TITLE
AntiHunger or fix freecam

### ISSUE THREAD

**Issue by HaekThor023** [kami-blue/client#910]
**Is your feature request related to a problem? Please describe.**
Yes. When i enable freecam when using baritone baritone goes crazy and thinks my freecam is my actual position. When i then exit freecam after 3 seconds i am left with 3 hunger bars

**Describe the solution you'd like**
Make freecam compatible with such things as baritone(ik this is possible since it works without problems on impact

**Describe alternatives you've considered**
Antihunger module
.

**Comment by dominikaaaa** [comment]
This already has AntiHunger, and as for compatibility, see #530
