### ISSUE TITLE
AutoQMain Says that I am on a singleplayer world when I am in 2b2t queue.

### ISSUE THREAD

**Issue by ollieobama** [kami-blue/client#911]
When I am on 2b2t and toggle autoqmain, it gives me a error saying that I am in singleplayer.

How to reproduce:
Go on 2b2t and toggle autoqmain

**Comment by dominikaaaa** [comment]
```kotlin
        if (mc.getCurrentServerData() == null && connectionWarning.value) {
            sendMessage("&l&6Error: &r&6You are in singleplayer")
            return
        }
```
this is pretty much impossible unless you connected to a null server
