### ISSUE TITLE
AutoWalk Bug

### ISSUE THREAD

**Issue by Oecher1** [kami-blue/client#915]
**Describe the bug**
accidentally found this when elytra flying so basically fly with elytra have autowalk on mode baritone turn it on and it will turn off with a message in chat then change the mode of autowalk to like forward or backwards and with the module not even on if its forward you will start going forward and backwards you go backwards lol

**To Reproduce**
1. Said it above and im tired at 3 am so im not gonna type anymore

**Expected behavior**
didn't expect it to make me move forward or backwards when changing the modes even though the module was off

**Screenshots**
no

**Additional context**
no

**Comment by dominikaaaa** [comment]
I can confirm this issue still happens
