### ISSUE TITLE
Autofish doesn't catch fish.

### ISSUE THREAD

**Issue by mothheart** [kami-blue/client#919]
**Describe the bug**
Autofish doesn't catch fish through bounces and ripple effects. Currently not working as intended.

**To Reproduce**
1. Turn on autofish
2. Cast line.
3. No fish catched at bounces and ripples.

**Expected behavior**
Fish is expected to be catched at bounces and ripple effects..

**Additional context**
Initially tested on constantiam.net with the latest beta version.

**Comment by dominikaaaa** [comment]
Can you please provide a video?

**Comment by mothheart** [comment]
I'll make one later tonight. No worries

**Comment by mothheart** [comment]
Not able to reproduce with latest github commit. Apparently just a bug in the beta release? I've built a custom version and I'm no longer seeing the issue.
