### ISSUE TITLE
Infinite chat

### ISSUE THREAD

**Issue by Sjoerd1812** [kami-blue/client#920]
**Is your feature request related to a problem? Please describe.**
i cant see all the chat, and WWE has infinite chat so maybe this would be nice

**Describe the solution you'd like**
Being able to scroll up to the beginning of you joining instead of havinf a limit

**Describe alternatives you've considered**
Ok

**Additional context**
No

**Comment by dominikaaaa** [comment]
How does this work?

**Comment by cookiedragon234** [comment]
You’re the developer lol

**Comment by dominikaaaa** [comment]
I closed the last issue as won't fix, and I wouldn't know how it works. It doesn't seem all that useful enough to spend time trying to find out how

**Comment by mattymatty97** [comment]
minecraft chat has a limit in size for it's history, if you fill the history it will start deleting the oldest lines

i too know that WWE had a module to expand the history size, called Infinite chat

i don't think it is useful or worth if done that way.

**Comment by dominikaaaa** [comment]
Yea I would've figured out just mixin into whatever class does that and cancel it

**Comment by mattymatty97** [comment]
in my opinion it would be more useful make something different on the new GUI you're working on

like a Log widnow with toggles to hide some type of entries:
- chat
- commands
- kami-logs
- DMs
excetera...

**Comment by dominikaaaa** [comment]
Not sure why you'd want to toggle dms, but toggling kami messages is already an option and it would be ported over to a proper GUI. Having them grouped in 1 menu would be nice though

**Comment by mattymatty97** [comment]
![immagine](https://user-images.githubusercontent.com/33039934/83761769-085f3e00-a677-11ea-8d3d-368a050280f7.png)
i meant something like this but with in game chat, events like deaths joins leaves , and other toggles and possibly even the search box to find something in the log

**Comment by mattymatty97** [comment]
should i write those as another issue maybe?

**Comment by dominikaaaa** [comment]
ehhh antispam already has options to filter those, and people can already search their logs just fine

**Comment by mattymatty97** [comment]
anti-spam deletes them complelty so if you toggle anti-spam off you wont see the deleted ones,
what i was suggesting was instead to be able to toggle to show/hide even previous ones

**Comment by dominikaaaa** [comment]
Being able to reshow and hide old messages would require a LOT more work then just cancelling the event
