### ISSUE TITLE
OffHandCrystal option for crystalaura

### ISSUE THREAD

**Issue by zisis912** [kami-blue/client#922]
Add an option for AutoCrystal where the crystals go in your offhand, and once your health is less than the set amount (default to14 HP), it automatically puts totems in your offhand. Reference video: https://www.youtube.com/watch?v=LG9gi8jRk54

**Comment by dominikaaaa** [comment]
Autototem already has an option for this

**Comment by zisis912** [comment]
does autototem have an HP option where it will automatically switch from crystals to totems?

**Comment by dominikaaaa** [comment]
Yes.

**Comment by zisis912** [comment]
bruh you have thought of everything im out of ideas :p

**Comment by zisis912** [comment]
@dominikaaaa can you tell me exactly which module on which settings do I have to turn on? (send a screenshot with the settings to do this)

**Comment by dominikaaaa** [comment]
Autototem with custom item enabled

**Comment by zisis912** [comment]
pls show a screenshot of the settings/commands you did, i cant find it anywhere
