### ISSUE TITLE
Scaffold range option

### ISSUE THREAD

**Issue by zisis912** [kami-blue/client#924]
Future has a thing called autobuilder, and it automatically builds stuff you set it to. It's best use is to set it on flat and then hold TNT, its very good for griefing. Add it, as it will be quite useful

**Comment by dominikaaaa** [comment]
`;b click`
`b sel set tnt`

**Comment by zisis912** [comment]
it would be easier if there was a module for it...

**Comment by dominikaaaa** [comment]
I don't see why there should be a separate module for something that already exists as an option. It makes sense because it's AutoTotem, but it uses a custom item (like the name of the option) unless your HP is too low

**Comment by dominikaaaa** [comment]
I don't see how I could possibly know with a module what the player wants to build

**Comment by zisis912** [comment]
for now make it just make flats, like used in this video 
https://www.youtube.com/watch?v=3-fR-C1wxK8

**Comment by dominikaaaa** [comment]
So sort of like a large scaffold I guess.

**Comment by zisis912** [comment]
yes... I guess large scaffold is a way to call it
