### ISSUE TITLE
I'd like Auto Fly as a setting for ElytraFly

### ISSUE THREAD

**Issue by Himes0-0** [kami-blue/client#928]
**Is your feature request related to a problem? Please describe.**
I'd like a way to be able to fly without having to be totally active so flying places far out takes less time. it would work by flying with ElytraFly and you can be afk and you will still be flying. This could also be able to be disabled with a click of a button.

**Describe the solution you'd like**
Like I said I want it to work by being able to fly without having to be active and it would fly for you like auto walk or Baritone but with elytra.

**Describe alternatives you've considered**
I haven't seen any other auto fly's and this is one of my clients so I'd like this client to have it.

**Additional context**
I don't know any way of showing it... so yeah

**Comment by dominikaaaa** [comment]
https://github.com/kami-blue/tenor
