### ISSUE TITLE
CoordUtil use dimension and server IP

### ISSUE THREAD

**Issue by zfih** [kami-blue/client#933]
**Is your feature request related to a problem? Please describe.**
When using StashFinder and logging to file I can't distinguish between logs in the overworld and the nether, as well as not knowing what server it logged it on, as I play on a couple Anarchy servers.

**Describe the solution you'd like**
Simply log a bit more information, such as server IP and dimension, either as more data or in the name.

**Describe alternatives you've considered**
I have considered modifying the log myself when I see it logging in chat, but that is somewhat cumbersome.

**Additional context**
No

**Comment by dominikaaaa** [comment]
Duplicate in favor of #1111
