### ISSUE TITLE
Inventory Viewer overlays tab menu 

### ISSUE THREAD

**Issue by Himes0-0** [kami-blue/client#934]
**Describe the bug**
The items in the Inventory Viewer gets overlaid on top of the tab menu

**To Reproduce**
1. Turn on ExtraTab.
2. Enabled the Inventory Viewer and put it in the general area as seen in the screenshot below:
![Screenshot_2020-06-07_16-23-27](https://user-images.githubusercontent.com/64826538/83982440-8faceb80-a8db-11ea-8191-18e8f26bba51.png)
3. Hit Tab and see the items overlaid on top of the tab menu as seen in this screenshot below:
![Screenshot_2020-06-07_16-12-51](https://user-images.githubusercontent.com/64826538/83982511-f3371900-a8db-11ea-9720-062a5bf0fb2f.png)
4. You can see the error.

**Expected behavior**
The items in the Inventory Viewer overlays behind the Tab Menu.

**Screenshots**
I added screenshots in the To Reproduce section.

**Additional context**
none.

**Comment by Xiaro** [comment]
Already fixed in 995252f
![image](https://user-images.githubusercontent.com/62033805/98396602-f4f03e80-202b-11eb-9d63-4d8e9620b954.png)
