### ISSUE TITLE
Speedhack

### ISSUE THREAD

**Issue by mothheart** [kami-blue/client#935]
**Is your feature request related to a problem? Please describe.**
Currently, Kami Blue has no on-foot speedhacks. It would be convenient to be support baritone to have on foot speedhacks.

**Describe the solution you'd like**
An implementation of on-foot speedhacks in the same way as Impact or Future implements it, especially for the Boost/LowHop/AAC modes.

**Describe alternatives you've considered**
Sprint + autojump currently does the job somewhat, but it isn't quite as efficient.

**Additional context**
It could be possible to base the new speedhack implementation on [Wurst's own](https://github.com/Wurst-Imperium/Wurst7/blob/master/src/main/java/net/wurstclient/hacks/SpeedHackHack.java), which is under the same license as Kami Blue. Wurst's speedhack implementaiton also supports every modes mentionned in the solution section as well as a couple more that aren't in either Future or Impact. It has some of the best speedhack implementations ~~(Even if the client generally sucks lol)~~

**Comment by dominikaaaa** [comment]
#852
