### ISSUE TITLE
Greatly optimize GUI performance in the laziest way possible

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#937]
I'll be real here, I don't wanna work on kamigui. I really dislike the code personally, though there is some cool stuff that I do like how it was done. 

On init, in the KamiGUI class, it creates a tick listener for all 140 modules individually that does this

which does 3 things
- update button name with module name
- update button enabled with module enabled
- update button description with module description

number 3 should be completely removable, only do it once

number 2 should theoritically be removable, as the state should be updated when pressed anyways?

number 1 could be removed if renaming modules was removed. *but* instead the rename module method could also (and reload config) instead call a manual update to it, instead of updating that every tick

**Comment by mothheart** [comment]
I could lend a hand on that. The code isn't too messy and I can understand it.

**Comment by cookiedragon234** [comment]
🤦

**Comment by dominikaaaa** [comment]
I only made this issue for myself really

**Comment by mattymatty97** [comment]
isn't possible to make Modules generate events when those values change and make the gui only subscribe to those events and so react to the changes only?
( PS: i hate not having time to try code my suggestions myself )

**Comment by dominikaaaa** [comment]
Of course it's possible, but it currently doesn't. That's why closeSettings() exists, whenever the settings are modified by code with .setValue(), I manually close the settings so the new values are forced to be shown.

**Comment by dominikaaaa** [comment]
https://github.com/kami-blue/client/commit/f56bf63ddb5f847a46ca1529456fface6e137937

i cba to work on this, if someone wants to continue where i left off by making a custom listener to call onToggle and on ;renamemodule command, go ahead
