### ISSUE TITLE
Autofish failing on 9b9t and 2b2t 

### ISSUE THREAD

**Issue by ISGL** [kami-blue/client#940]
Autofish manages to fish 1-4 times then stops working until you turn the cheat of and on again.

What I did everytime:
1.turn on autofish (settings didn’t matter)
2. Right click on the water to cast (enchantments didn’t matter)
3. Let it fish normally a couple of times (1-4 times)
4.watch it stop catching 

It should’ve just kept fishing like it does on single player but it didn’t

**Comment by dominikaaaa** [comment]
there's several ways of fixing this. 1 is listening to sound packets for splashes

another is checking the change in Y for the bobber entity
