### ISSUE TITLE
AutoTPA doesn't work on 0b due to the detection format 

### ISSUE THREAD

**Issue by phaboydave** [kami-blue/client#941]
**Describe the bug**
There is a bug concerning the AutoTPA module which causes it not to work on servers such as 0b0t (not sure if it usually works on other servers).

**To Reproduce**
1. Go to 0b0t.org
2. Click on AutoTPA (doesnt matter if friends are enables or not)
3. Wait for friend or non-friend to send a tpa request.

**Expected behavior**
I expected it to simply function as described and intended. To accept tpa requests.

**Additional context**
I talked to dominika about it thus making her aware of the issue before this bug report.

**Comment by dominikaaaa** [comment]
Correct regex for this would be `"^([0-9A-z_])+ wants to teleport to you\\..*"` instead of `"^([0-9A-z_])+ has requested to teleport to you\\..*"`
