### ISSUE TITLE
Elytra Speed C bug

### ISSUE THREAD

**Issue by Xiaro** [kami-blue/client#942]
**Describe the bug**
The actual flying speed has random offset to what it should be based on the speed c setting

**To Reproduce**
1. Set Speed C to something that is close to 1.81 (36.2m/s, which is the speed limit on 2B)
2. Move around, your speed will be different in each diretion.
3. There is a chance that the speed will be faster than the value you set for speed c

**Expected behavior**
The speed should be exact the same as the the speed c
Or at least not going above speed c

**Screenshots**
![image](https://user-images.githubusercontent.com/62033805/84186533-ad568e00-aa5e-11ea-9d31-30c0f3cab504.png)
_I have my speed c set to 1.809, which should be 36.18m/s, but my speed is 36.207m/s_
![image](https://user-images.githubusercontent.com/62033805/84188507-b7c65700-aa61-11ea-80a4-9c48850c6bbf.png)
_Same setting but now the speed is 36.18m/s_

**Additional context**
This is only tested on 2b, not sure if it happens on other server.

**Comment by dominikaaaa** [comment]
When you're moving diagonally, technically you're travelling more distance but actually going the same speed. The speed counter uses the pythagorean theorem to calculate speed, you can do the math yourself to see that it indeed does check out, you're not actually going that fast.
