### ISSUE TITLE
trajectories doesn't calculate snowballs, eggs and exp bottles properly

### ISSUE THREAD

**Issue by zisis912** [kami-blue/client#944]
im way too bored to talk, just check the screenshots
![image](https://user-images.githubusercontent.com/65046191/84241390-13e3b680-ab08-11ea-90cd-b0460eefd5df.png)
![image](https://user-images.githubusercontent.com/65046191/84241423-2100a580-ab08-11ea-9790-81418290d523.png)

**Comment by dominikaaaa** [comment]
Since it wasn't calculating *anything* properly (image attached) since render update, I've removed the line render code

![2020-08-12_13 16 53](https://user-images.githubusercontent.com/17222512/90049169-70975500-dca2-11ea-83fc-c0e2e652eafb.png)

**Comment by Xiaro** [comment]
Closed in https://github.com/kami-blue/client/commit/cdf178096a1ad21785feba98fefecaf25d7222db
