### ISSUE TITLE
Invisible Module List

### ISSUE THREAD

**Issue by jaxhldn** [kami-blue/client#945]
When I press Y, my module list used to open without any problems. But for the past few weeks, when I press Y, radar dissapears but the module list becomes invisible. THe game acts like the list is open though, as I cannot walk around or look around. I can still drag around the inventory viewer but it is imppossible to change modules for which I do not have a keybind. I am stuck with Salhack, which has a very shitty takeoff for elytra flight. Hopefully you can show me how to fix this.

**Comment by dominikaaaa** [comment]
Please provide a video of the issue.

**Comment by zisis912** [comment]
I don't think invisible module list is a title for that problem. When I saw invisible module list I thought it was a list of all the modules that have the visible option to off

**Comment by dominikaaaa** [comment]
Closed due to no response. Please comment with the requested information and this will be reopened.
