### ISSUE TITLE
Mod not loading

### ISSUE THREAD

**Issue by UltraBlackLinux** [kami-blue/client#950]
So I just put the 1.1.5 kami blue jar in my mods folder and run it with forge. it tells me that it didnt get loaded, cause of to new forge. Found this though:

[m[33m[16:23:18] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file Mod File: /home/maus/.local/share/multimc/instances/Kami Blue 1.15/.minecraft/mods/KAMI-Blue-v1.1.5-release.jar is missing mods.toml file
[m[33m[16:23:18] [main/WARN] [ne.mi.fm.lo.mo.ModDiscoverer/SCAN]: File /home/maus/.local/share/multimc/instances/Kami Blue 1.15/.minecraft/mods/KAMI-Blue-v1.1.5-release.jar has been ignored - it is invalid

[m[33m[16:23:29] [Server-Worker-2/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Configuration file /home/maus/.local/share/multimc/instances/Kami Blue 1.15/.minecraft/config/forge-client.toml is not correct. Correcting
[m[33m[16:23:29] [Server-Worker-2/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key client.experimentalForgeLightPipelineEnabled was corrected from false to null

**Comment by dominikaaaa** [comment]
Send a screenshot of your other mods, and forge version

**Comment by UltraBlackLinux** [comment]
no other mods, and I tried 31.2.0 and 31.1.22

**Comment by UltraBlackLinux** [comment]
![Screenshot_20200615_183101](https://user-images.githubusercontent.com/62404294/84682738-5f49fa80-af36-11ea-8210-7783df9a7db6.png)

**Comment by dominikaaaa** [comment]
Isn't that 1.15 forge?

**Comment by UltraBlackLinux** [comment]
yap
is there a problem w/ that?

**Comment by dominikaaaa** [comment]
KAMI Blue is 1.12.2 *only*

**Comment by UltraBlackLinux** [comment]
what?! oooh... now I understand - my bad. it confused me cause the name is, like baritone, a version hint....

**Comment by dominikaaaa** [comment]
Baritone's versioning system is a huge meme 
![maim-2020-06-15-12-35-56](https://user-images.githubusercontent.com/17222512/84683155-c8b11580-af04-11ea-85f2-4019b6b8b30f.png)

**Comment by UltraBlackLinux** [comment]
i kinda understood that xD
but I now transferred my knowlage to kami - would like a 1.15 version though :)

**Comment by dominikaaaa** [comment]
https://vasya.dominikaaaa.org/
