### ISSUE TITLE
Stash logger

### ISSUE THREAD

**Issue by AssasinsGinger** [kami-blue/client#952]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but an enhancement to afk stash finder

**Describe the solution you'd like**
As the feature in salhack, it logs the coordinates where chests are found to a text file

**Describe alternatives you've considered**
Log the coordinates to a different file

**Additional context**
In salhack, there's a feature to afk stashfinder, where it logs the coordinates of multiple chests to a text file in the .minecraft folder. Make something similar or same to this

**Comment by dominikaaaa** [comment]
Um. This is literally built in.

**Comment by dominikaaaa** [comment]
Of course salhack tries to be the special kid of the class and makes a 1 line of code change into an entirely seperate module
