### ISSUE TITLE
In-game aspect ratio changer (like in csgo hacks)

### ISSUE THREAD

**Issue by phonkplugg** [kami-blue/client#954]
it will be a new slider, that can change an in-game aspect ratio without restarting the game

**Comment by dominikaaaa** [comment]
what aspect ratio???

**Comment by phonkplugg** [comment]
like this https://youtu.be/wSVY5i1P0e4

**Comment by dominikaaaa** [comment]
I don't see why that would be useful, and I don't think that's even possible with Java applications. The zoom module already exists and is pretty similar

**Comment by cookiedragon234** [comment]
?? Java does not prevent you from changing aspect ratio?? And anway opengl is written in C++.

Look at `glViewport` if you actually want to implement this.

**Comment by dominikaaaa** [comment]
I had a hunch it was a gl thing but quite frankly I don't think this is useful in any way

**Comment by cookiedragon234** [comment]
What do you mean you had a hunch? The game uses opengl for rendering, of course its going to be opengl.

And its very useful, see https://steamcommunity.com/sharedfiles/filedetails/?id=442426976

**Comment by dominikaaaa** [comment]
By "I had a hunch" I meant, I presumed that's how I thought it worked but I cba to actually see how it works.
