### ISSUE TITLE
minecraft 1.7.9 compatibility

### ISSUE THREAD

**Issue by Paralusion** [kami-blue/client#955]
**Is your feature request related to a problem? Please describe.**
yes, i am unable to launch the game with kami blue on version 1.7.9

**Describe the solution you'd like**
a new kami blue version, on minecraft 1.7.9

**Describe alternatives you've considered**
compatibility for ALL minecraft versions, perhaps?

**Additional context**
a screenshot showing that kami blue does not work on minecraft 1.7.9: https://imgur.com/a/8qqRFun

**Comment by dominikaaaa** [comment]
no

**Comment by Paralusion** [comment]
why not?

**Comment by dominikaaaa** [comment]
anarchy servers don't run on 1.7.9

**Comment by dominikaaaa** [comment]
also it would require a complete rewrite due to kami blue relying on forge events

**Comment by cookiedragon234** [comment]
Actually I play 1.7.9 anarchy sometimes, there are servers that run it
