### ISSUE TITLE
MapPreview Should show the name

### ISSUE THREAD

**Issue by ajgrinds** [kami-blue/client#957]

**Comment by dominikaaaa** [comment]
I tried to do that but it would render *under* the map itself and I couldn't figure out why for the life of me, so I left it as is.

**Comment by ajgrinds** [comment]
Personally under is better than not at all

**Comment by dominikaaaa** [comment]
No, I mean quite literally under. Like. If you held a bunch of papers together
```
map
---
map frame
--- 
map name
```
and imagine you're looking down from the top

you literally cannot see the map name, but it's there

**Comment by cookiedragon234** [comment]
I assume that when in your map preview code you wrote `this.itemRender.zLevel = 300.0F;` you understood that you were telling it to render above everything else?

**Comment by dominikaaaa** [comment]
No, I just tried using (psudocode) `Minecraft.fontRenderer.draw(map.name, 0, 0)`

**Comment by cookiedragon234** [comment]
As I said, since you specifically set the z value in the map rendering code to 300, it will render 300 layers above the text. So, if you want to render text above the map, you will need to render it at layer >= 300.

**Comment by dominikaaaa** [comment]
Um, where??

**Comment by cookiedragon234** [comment]
What do you mean um where? Take a look at the code...

**Comment by dominikaaaa** [comment]
![maim-2020-06-18-17-40-39](https://user-images.githubusercontent.com/17222512/85074616-d8da2680-b18a-11ea-8d5f-b741dffdccdb.png)

**Comment by cookiedragon234** [comment]
oh my I am very dumb I was looking at the shulker preview code LOL

**Comment by dominikaaaa** [comment]
# :monkey:

**Comment by cookiedragon234** [comment]
but the point still stands, you specifically told it to render above everything else
`glDepthRange(0, 0.01); // fix drawing under other layers, just draw over everything`

**Comment by dominikaaaa** [comment]
Yes, I did that to the text and it didn't work

**Comment by dominikaaaa** [comment]
I'm not *that* stupid.

**Comment by cookiedragon234** [comment]
What exactly do you mean when you say you "did that to the text"

**Comment by dominikaaaa** [comment]
```
glDepthRange(0, 0.01);
// draw text
glDepthRange(0, 1.0);
```

**Comment by cookiedragon234** [comment]
was that before or after you called
`GlStateManager.disableDepth()`

**Comment by dominikaaaa** [comment]
I tried with and without messing with depth.

**Comment by cookiedragon234** [comment]
wdym by "messing with depth", I just asked if you had depth testing enabled when you attempted to set the depth range?

**Comment by dominikaaaa** [comment]
I tried with depth enabled and with depth disabled

**Comment by cookiedragon234** [comment]
Why did you add in the depth ranges to the map code in the first place? It is clearly that that is intefering with the text rendering.

**Comment by dominikaaaa** [comment]
Because without it, the map renders under the frame, instead of over, and it has coloring issues.

**Comment by cookiedragon234** [comment]
Have you tried simply translating the z coordinates?

**Comment by dominikaaaa** [comment]
Believe me, I don't like fucking with GL code when I don't know why it works, but the final committed code is what worked and the bare minimum of what worked. If I remove one of those lines there's a damn good chance that something about it breaks

**Comment by dominikaaaa** [comment]
Umm, yes. If I render the text at -10 -10 you can see that it's being rendered under the map

**Comment by cookiedragon234** [comment]
Well I guess Ill just do it for you then

Firstly, you call info.cancel() to prevent minecraft from drawing the original tooltip. If you dont cancel it, then minecraft will render the map name itself, resulting in this:
![](https://i.binclub.dev/kblbw1dp.png)
Code:
```Java
	@Inject(method = "renderToolTip", at = @At("HEAD"), cancellable = true)
	public void renderToolTip(ItemStack stack, int x, int y, CallbackInfo info) {
		if (stack.getItem() instanceof ItemMap) {
			ItemMap map = (ItemMap)stack.getItem();
			MapData mapData = map.getMapData(stack, mc.world);
			if (mapData != null) {
				int xl = x + 6;
				int yl = y + 6;
				
				GlStateManager.pushMatrix();
				GlStateManager.color(1f, 1f, 1f);
				RenderHelper.enableGUIStandardItemLighting();
				GlStateManager.disableDepth();
				
				
				GlStateManager.translate(xl, yl, 0.0);
				GlStateManager.scale(1f, 1f, 1f);
				mc.getTextureManager().bindTexture(RES_MAP_BACKGROUND);
				
				// Draw Frame
				{
					Tessellator tessellator = Tessellator.getInstance();
					BufferBuilder bufferbuilder = tessellator.getBuffer();
					bufferbuilder.begin(7, DefaultVertexFormats.POSITION_TEX);
					bufferbuilder.pos(-7.0D, 135.0D, 0.0D).tex(0.0D, 1.0D).endVertex();
					bufferbuilder.pos(135.0D, 135.0D, 0.0D).tex(1.0D, 1.0D).endVertex();
					bufferbuilder.pos(135.0D, -7.0D, 0.0D).tex(1.0D, 0.0D).endVertex();
					bufferbuilder.pos(-7.0D, -7.0D, 0.0D).tex(0.0D, 0.0D).endVertex();
					tessellator.draw();
				}
				
				// Draw Map
				mc.entityRenderer.getMapItemRenderer().renderMap(mapData, false);
				
				GlStateManager.enableDepth();
				RenderHelper.disableStandardItemLighting();
				GlStateManager.popMatrix();
			}
		}
	}
```

Otherwise, if you want to render the name yourself, thats easy enough:
![](https://i.binclub.dev/kblc58dm.png)
Code:
```Java
		if (stack.getItem() instanceof ItemMap) {
			ItemMap map = (ItemMap)stack.getItem();
			MapData mapData = map.getMapData(stack, mc.world);
			if (mapData != null) {
				info.cancel();
				int xl = x + 6;
				int yl = y + 6;
				
				GlStateManager.pushMatrix();
				GlStateManager.color(1f, 1f, 1f);
				RenderHelper.enableGUIStandardItemLighting();
				GlStateManager.disableDepth();
				
				
				GlStateManager.translate(xl, yl, 0.0);
				GlStateManager.scale(1f, 1f, 1f);
				mc.getTextureManager().bindTexture(RES_MAP_BACKGROUND);
				
				// Draw Frame
				{
					Tessellator tessellator = Tessellator.getInstance();
					BufferBuilder bufferbuilder = tessellator.getBuffer();
					bufferbuilder.begin(7, DefaultVertexFormats.POSITION_TEX);
					bufferbuilder.pos(-7.0D, 135.0D, 0.0D).tex(0.0D, 1.0D).endVertex();
					bufferbuilder.pos(135.0D, 135.0D, 0.0D).tex(1.0D, 1.0D).endVertex();
					bufferbuilder.pos(135.0D, -7.0D, 0.0D).tex(1.0D, 0.0D).endVertex();
					bufferbuilder.pos(-7.0D, -7.0D, 0.0D).tex(0.0D, 0.0D).endVertex();
					tessellator.draw();
				}
				
				// Draw Map
				mc.entityRenderer.getMapItemRenderer().renderMap(mapData, false);
				
				mc.fontRenderer.drawString(stack.getDisplayName(), 0, -6, Color.BLACK.getRGB());
				
				GlStateManager.enableDepth();
				RenderHelper.disableStandardItemLighting();
				GlStateManager.popMatrix();
			}
		}
```

**Comment by l1ving** [comment]
I don't know why I didn't revisit this issue earlier, sorry about being stupid with the GL stuff. I was really impatient to learn stuff properly then.
