### ISSUE TITLE
Yaw lock option to not go on diags

### ISSUE THREAD

**Issue by ajgrinds** [kami-blue/client#959]

**Comment by dominikaaaa** [comment]
That's what the angle setting is for

**Comment by ajgrinds** [comment]
If you move your mouse enough you can force it to turn 45 degrees. There should be an option to only go on axis

**Comment by dominikaaaa** [comment]
Yes, you can do that. If you mean a 4 axis instead of an 8 axis, as I said, change the angle setting. As for moving your mouse to change it, disable auto
