### ISSUE TITLE
unfairly banned from the Discord

### ISSUE THREAD

**Issue by Paralusion** [kami-blue/client#967]
**Describe the bug**
Today, I was unfairly banned on the Discord. I'm not too sure about the details, it just happened and haven't received any reason except for "rule8"

**To Reproduce**
1. Go to '...' Kami Blue Discord
2. Click on '....' Join
3. Scroll down to '....' not too sure
4. See error the ban was a error? maybe?

**Expected behavior**
I was trying to help a friend of mine out in the Discord, after he (in my opinion) got muted unfairly. As a civilized person, I requested for him to be either unmuted or for his punishment to be shortened. Dominika, a member of the Discord told me that it was not unfair. When I tried to get an explanation as to why the mute was fair, I got banned.

**Screenshots**
https://imgur.com/a/yJ0vu7U

**Additional context**
-

**Comment by Ilidumb** [comment]
mfw

**Comment by cookiedragon234** [comment]
Ｐｗｅａｓｅ ｐｗｏｖｉｄｅ ａ ｃｗｅａｗ ａｎｄ ｃｏｎｃｉｓｅ ｄｅｓｃｗｉｐｔｉｏｎ ｏｆ ｗｈａｔ ｔｈｅ ｂｕｇ ｉｓ。 Ｉｎｃｗｕｄｅ ｓｃｗｅｅｎｓｈｏｔｓ ｉｆ ｎｙｅｅｄｅｄ。

**Comment by Tigermouthbear** [comment]
this ban was heterophobic and racist towards trolls #unbanpara

**Comment by dominikaaaa** [comment]
1. This is not a bug
2. You weren't unfairly banned. You've been banned 4 times now, and the council made a unanimous decision to ban you. You broke rule 8 knowingly and repeatedly, along with rule 1.
