### ISSUE TITLE
Add a gapp chug module

### ISSUE THREAD

**Issue by ajgrinds** [kami-blue/client#976]
I am always frustrated when I'm about to die and I want to be that guy and drop my stuff in my echest but I can't stop eating gapps.

My idea was a module which makes it so you don't do that so I can piss off the people I am fighting.

Edit: this is slightly a joke but also slightly serious

**Comment by dominikaaaa** [comment]
What?? what are you even asking for

**Comment by ajgrinds** [comment]
add an auto gapp module which automatically eats gapples at the perfect time like auto potion.

**Comment by dominikaaaa** [comment]
uhhh use offhandgap and just constantly hold down right click
