### ISSUE TITLE
Storage ESP improvements 

### ISSUE THREAD

**Issue by Cap-with-a-k** [kami-blue/client#979]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
i think it would be cool that with storage esp a storage block will not show up with esp unless something is in the item, this is useful so we dont need to waste our time going for an empty chest
**Describe alternatives you've considered**
an alternative to this could be having empty storage blocks show up as another colour maybe? 
**Additional context**
no more context needed

**Comment by dominikaaaa** [comment]
That's not possible, chest packets aren't sent until you right click it
