### ISSUE TITLE
Player stuck

### ISSUE THREAD

**Issue by Ericy1** [kami-blue/client#988]
**Describe the bug**
Had only used v.1.1.6 stable release for a few minutes, and then I suddenly got "stuck" on a block. Breaking the block below you and moving will not work. The player is continually teleported back to the location. I have confirmed the bug is with kami blue and not a glitch within minecraft, as after I switched clients everything went back to normal. I'm sticking to v.1.1.5 for now.

**To Reproduce**
1. Every time I log in and join a world, I am immediately unable to move, permanently stuck on the login location.

**Expected behavior**
Be able to move.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by dominikaaaa** [comment]
this isn't kami blues fault lol

mine the blocks under you, you're stuck in a block or something

**Comment by Ericy1** [comment]
No, I don't think you understand the issue. Let me clarify. First of all, the issue is completely gone if I use a client like Impact or the previous stable release of your client, v1.1.5. If I switch to v.1.1.6, not only am I not able to move, I cannot even rotate the player to view my surroundings. I'm literally stuck in the same orientation and position. Any movement is automatically rejected and you are immediately pulled back to the exact same orientation/position. Furthermore, I haven't changed any of the client settings before downloading the new stable release. 

If you need video proof, I can record a video and upload it unlisted to youtube showing you a comparison of v.1.1.5 vs v.1.1.6.

**Comment by dominikaaaa** [comment]
you did look at the changelog, right?

just provide a screenshot of ;tsc

**Comment by Ericy1** [comment]
I figured out the issue. Disabling "PortalGodMod" fixes the issue. Hope this helps.

**Comment by dominikaaaa** [comment]
that's not an issue, that's what portal god mode does, completely intentionally.

**Comment by dominikaaaa** [comment]
switching between versions literally wouldn't affect that anyways. bruh

**Comment by Ericy1** [comment]
Lol chill bro, just trying to help out. If it ain't an issue then that's great.
