### ISSUE TITLE
Ground elytra/elytra speed

### ISSUE THREAD

**Issue by Muhannad0AlAbrash** [kami-blue/client#990]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Adding Ground elytra/elytra speed well help bypass the anticheat of most if not all anarchy servers.

**Describe alternatives you've considered**
Its like elytra fly but it launches on the ground + has step(go up a block automatically) if possible. 

**Additional context**
None

**Comment by dominikaaaa** [comment]
Step is a seperate suggestion. If you want taking off from the ground, control mode has an easy takeoff option that does exactly that, and it can also fit in 1x1s meaning you can be as close to the ground as walking.

**Comment by dominikaaaa** [comment]
not to mention the fact that control mode already bypasses on every server
