### ISSUE TITLE
Impact colors won't display properly when used with Kami Blue 1.1.5+ and optifine

### ISSUE THREAD

**Issue by peppershot** [kami-blue/client#993]
Impact's StorageESP, newchuncks and baritone pathfinding Line indicator when used with Kami Blue 1.1.5+ and optifine only show a pale grey colour instead of the colors they are intended to show
And an openGL error message appears in chat

**To Reproduce**
1. Download the latest version of Impact into the mods folder
2. Download optifine 1.12.2 into mods folder
3. Download any version above Kami Blue 1.1.5
4. Run Forge
5. Turn on Impact's StorageESP

**Expected behavior**
For impact's colors to display as intended

**Additional context**
it is not the settings that are wrong, I tried changing colours, yet the grey color stayedj

**Comment by dominikaaaa** [comment]
This isn't kami blue's fault

**Comment by peppershot** [comment]
it is tho, I just removed optifine and it's still doing the same thing

**Comment by dominikaaaa** [comment]
It's caused by the Baritone API being included inside KAMI Blue, not KAMI Blue itself. It's also already reported in a *pinned* issue, #769. 
![maim-2020-06-29-13-02-06](https://user-images.githubusercontent.com/17222512/86034522-bfe23880-ba08-11ea-8d59-35fedd6deb21.png)
Use KAMI Blue's StorageESP
