### ISSUE TITLE
Native mode for AutoEZ

### ISSUE THREAD

**Issue by luyten-h** [kami-blue/client#994]
An AutoEZ Target System for KillAura, CrystalAura, etc. Just to make it better and more accurate.
Also I did not forget, this can be toggleable in the settings of the module.

ex. When your CrystalAura chooses a target, there's put an AutoEZ target too. When that person has been killed by you the AutoEZ message is sent in chat and the AutoEZ target is removed. If the person has killed you, the AutoEZ target gets reset with no message sent. If the AutoEZ target setting is enabled, it does the process of targetting the user. When it isn't enabled, it doesn't do anything. And that's all.

**Comment by iSeros** [comment]
I forgot to say, when the setting in the AutoEZ module of target isn't enabled, it just does the good ol' inaccurate AutoEZ.

**Comment by dominikaaaa** [comment]
Ah. Since CrystalAura now actually changes mc.player.lastAttackedEntity, this would be super easy to do, so you would literally just have a listener for mc.player.lastAttackedEntity, store the current one, and if it changes to null, send the AutoEZ message.
