### ISSUE TITLE
PlayerModel enchant glint breaks with InventoryViewer

### ISSUE THREAD

**Issue by Muhannad0AlAbrash** [kami-blue/client#995]
**Describe the bug**

**To Reproduce**
1. Go to Render
2. Click on PlayerModel 
3. Then the PlayerModel loades but it is fliped 

**Expected behavior**
Expected it to work normally

**Screenshots**
![image](https://user-images.githubusercontent.com/49660804/86054539-5540f500-ba28-11ea-83e0-eb5675acb0f9.png)

**Additional context**
I tried it on linux and it worked normally.

**Comment by dominikaaaa** [comment]
uhhhh what other mods do you have

**Comment by dominikaaaa** [comment]
the red enchantment glint is probably impact, so idk if the enchanting being broken is impact or kami blue's fault

**Comment by Muhannad0AlAbrash** [comment]
Impact + salhack+ KamiBlue + a minimap mode.

**Comment by Muhannad0AlAbrash** [comment]
The red enchantment was using a program a long time ago

**Comment by dominikaaaa** [comment]
Send a screenshot what happens without any other mods

**Comment by Muhannad0AlAbrash** [comment]
![image](https://user-images.githubusercontent.com/49660804/86055464-cf25ae00-ba29-11ea-8116-896653158edc.png)

(the only mod on is Kamiblue)

**Comment by dominikaaaa** [comment]
doesn't happen to me ngl

**Comment by Muhannad0AlAbrash** [comment]
I tried it on linux it works normally there. maybe its the java ver. ?

**Comment by dominikaaaa** [comment]
the java version wouldn't affect it, that's a gl thing

send a screenshot of ;tsc

**Comment by dominikaaaa** [comment]
wait what operating systems does it not work on then

**Comment by Muhannad0AlAbrash** [comment]
The issue occurs on win 10

**Comment by Muhannad0AlAbrash** [comment]
![image](https://user-images.githubusercontent.com/49660804/86057974-1877fc80-ba2e-11ea-9c4d-27a004982c20.png)

**Comment by dominikaaaa** [comment]
uhhh yea then I can't fix that, it's up to someone else to fix it

**Comment by cookiedragon234** [comment]
You need to stop blaming stuff on operating systems that is clearly caused by your code, literally just fix the gl colour state

**Comment by dominikaaaa** [comment]
if the issue only happens on windows, there's nothing I personally can do to fix it

**Comment by dominikaaaa** [comment]
also it's not my code, I'm literally just using a minecraft render function.

**Comment by Muhannad0AlAbrash** [comment]
Its not only enchantments even without them this is how it looks 
![image](https://user-images.githubusercontent.com/49660804/86061978-bde29e80-ba35-11ea-9f9f-d1be316b09ee.png)

**Comment by cookiedragon234** [comment]
Yep, literally just fix your gl flags Bella, saying it works on Linux isn’t an excuse lmao

**Comment by dominikaaaa** [comment]
How am I supposed to fix it if I can't reproduce the issue on my operating system :monkey:

**Comment by Muhannad0AlAbrash** [comment]
what operating system do u use btw (for gaming and programing)?

**Comment by dominikaaaa** [comment]
Arch. I personally like it but I wouldn't recommend it to people really.

**Comment by Muhannad0AlAbrash** [comment]
I have linux on my 2nd laptop cuz it wont work on my pc. (the gpu drivers wont work I get like 20 fps with a 1050ti on windows I get about 100 to 150 with mods)

**Comment by dominikaaaa** [comment]
Ehhh that sounds like a you problem. Ubuntu 20.04 has working drivers out of the box, you just have to tick a setting once installed for the official Nvidia ones

**Comment by Muhannad0AlAbrash** [comment]
true, still windows is better for gaming(more games run on it) in my opinion. 
If u could change the Playermodel code to a different one I could try multiple ones and the one that works u can add it to kamiblue

**Comment by dominikaaaa** [comment]
it's not as simple as "just change it to a different set of code", i'm using 1 method from minecraft's code to do it. I'm going have to boot up a vm or ask someone else to test my changes and that's pretty time consuming.

**Comment by dominikaaaa** [comment]
cooker kept bothering me about it :rage:

**Comment by cookiedragon234** [comment]
Push matrix, reset Color and enable depth before you call drawEntityOnScreen
Then pop matrix after

**Comment by cookiedragon234** [comment]
> Arch. I personally like it but I wouldn't recommend it to people really.

The way arch users gatekeep to seem elite is hilarious

**Comment by dominikaaaa** [comment]
I wouldn't recommend it because it's a pain in the ass to setup and to use on a daily basis, and is only worth it if you have the time to do so. It's not gatekeeping, it's protecting people's spare time

**Comment by cookiedragon234** [comment]
🐒 if you have enough time then other people do

**Comment by dominikaaaa** [comment]
it's still a pain in the ass to use on a daily basis for most people

**Comment by cookiedragon234** [comment]
Arch user logic:

WTH you’re using windows LOL peasant everyone knows arch is the only good operating system 

Ok what should I use?

Oh dont use arch

🙉

**Comment by dominikaaaa** [comment]
it's really a small minority that does the "btw I use arch" thing. I use it because I personally really love the AUR, if it wasn't for that I would be using Ubuntu Server. I recommend people don't use it because it isn't the best choice for the majority of people.

If you think you have the time to deal with using it, knock yourself out

**Comment by golfermatt** [comment]
It appears that this issue is caused by inventory viewer

**Comment by dominikaaaa** [comment]
confirmed by xiaro
