### ISSUE TITLE
Possibility of Custom Fonts

### ISSUE THREAD

**Issue by iSeros** [kami-blue/client#996]
Alrighty so, time to start explaining. Not to forget, this can be a module in CLIENT named CustomFont and you can enable/disable it. Makes kami blue look cooler if we had the possibility of custom fonts.

This will change Kami Blue's clickgui, info overlay, text radar, and all of that stuff. Not the commands, and also not the radar coordinate text (z+, x+, z-, x-), just those.

Make it possible so that you have a option to choose certain custom fonts that you have put in a certain folder, let's say KamiFonts/FONT.ttf, and that there will be a customfont command to choose the font, ex. ";font FONT.ttf" and it will search in the folder for that font, if the font name is valid then every text in Kami Blue will be changed to that font. If it's invalid it'll send a error message.

And that's it!

**Comment by dominikaaaa** [comment]
#790
